act_code: '128653'
requisite: Решение акима Аватского сельского округа Енбекшиказахского района Алматинской области от 24 декабря 2018 года № 12-85. Зарегистрировано Департаментом юстиции Алматинской области 16 января 2019 года № 5001
title:
  rus: О переименовании улиц в селе Ават Аватского сельского округа
  kaz: Ават ауылдық округінің Ават ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '154012001002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128653/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128653/rus/24.12.2018
