act_code: '216598'
requisite: Решение акима Отенайского сельского округа города Талдыкорган области Жетісу от 29 сентября 2025 года № 225
title:
  rus: О присвоении наименований составным частям села Отенай Отенайского сельского округа
  kaz: Өтенай ауылдық округі Өтенай ауылының құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-29
approved_by:
- '154002002002'
version_date:
  kaz: 2025-09-29
  rus: 2025-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/216598/kaz/29.09.2025
  rus: https://zan.gov.kz/client/#!/doc/216598/rus/29.09.2025
