act_code: '151024'
requisite: Решение Алматинского областного маслихата от 15 декабря 2020 года № 64-339. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2020 года № 5841
title:
  rus: Об областном бюджете Алматинской области на 2021-2023 годы
  kaz: Алматы облысының 2021-2023 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '154000000002'
version_date:
  kaz: 2021-10-29
  rus: 2021-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/151024/kaz/29.10.2021
  rus: https://zan.gov.kz/client/#!/doc/151024/rus/29.10.2021
caused_by:
  code: '159987'
  requisite: Решение маслихата Алматинской области от 29 октября 2021 года № 9-52. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 ноября 2021 года № 25024
  title:
    rus: О внесении изменений в решение Алматинского областного маслихата от 15 декабря 2020 года № 64-339 «Об областном бюджете Алматинской области на 2021-2023 годы»
    kaz: Алматы облыстық мәслихатының 2020 жылғы 15 желтоқсандағы № 64-339 «Алматы облысының 2021-2023 жылдарға арналған облыстық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159987/rus
