act_code: '99624'
requisite: Решение акима Аксенгирского сельского округа Жамбылского районного маслихата Алматинской области от 05 февраля 2016 года № 02-5. Зарегистрировано Департаментом юстиции Алматинской области 22 февраля 2016 года № 3739
title:
  rus: О переименований улиц села Жайсан Аксенгирского сельского округа
  kaz: Ақсеңгір селолық округінің Жайсан ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-05
approved_by:
- '154018003001'
version_date:
  kaz: 2016-02-05
  rus: 2016-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/99624/kaz/05.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99624/rus/05.02.2016
