act_code: '163212'
requisite: Решение Талгарского районного маслихата Алматинской области от 30 декабря 2021 года № 18-62
title:
  rus: О бюджетах города Талгар и сельских округов Талгарского района на 2022-2024 годы
  kaz: Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2022-2024 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '154013000002'
version_date:
  kaz: 2021-12-30
  rus: 2021-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163212/kaz/30.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163212/rus/30.12.2021
