act_code: '118421'
requisite: Решение Уйгурского районного маслихата Алматинской области от 20 декабря 2017 года № 6-23-141. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2017 года № 4456
title:
  rus: «О бюджете Уйгурского района на 2018-2020 годы»
  kaz: Ұйғыр ауданының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '154008000002'
version_date:
  kaz: 2018-11-20
  rus: 2018-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/118421/kaz/20.11.2018
  rus: https://zan.gov.kz/client/#!/doc/118421/rus/20.11.2018
caused_by:
  code: '126664'
  requisite: Решение Уйгурского районного маслихата Алматинской области от 20 ноября 2018 года № 6-40-239. Зарегистрировано Департаментом юстиции Алматинской области 26 ноября 2018 года № 4882
  title:
    rus: О внесении изменений в решение Уйгурского районного маслихата от 20 декабря 2017 года № 6-23-141 «О бюджете Уйгурского района на 2018-2020 года»
    kaz: Ұйғыр аудандық мәслихатының 2017 жылғы 20 желтоқсандағы «Ұйғыр ауданының 2018-2020 жылдарға арналған бюджеті туралы» № 6-23-141 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126664/rus
