act_code: '51529'
requisite: Алматы облысы Қарасай ауданы Қарағайлы ауылдық округінің әкімдігінің 2010 жылғы 2 наурыздағы № 3-7 шешімі. Алматы облысы Қарасай ауданының Әділет басқармасында 2010 жылғы 1 сәуірде № 2-11-85 тіркелді
title:
  rus: Қарағайлы ауылына қарасты Алтын Заң көшесінің атауын өзгерту туралы
  kaz: Қарағайлы ауылына қарасты Алтын Заң көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-02
approved_by:
- '154015005002'
version_date:
  kaz: 2010-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/51529/kaz/02.03.2010
