act_code: '44892'
requisite: Алматы облысы Қарасай аудандық мәслихатының 2009 жылғы 14 қаңтардағы № 19-3 шешімі. Алматы облысының Әділет департаменті Қарасай ауданының Әділет басқармасында 2009 жылы 30 қаңтарда № 2-11-63 тіркелді
title:
  rus: 2009 жылға кесімді салық ставкаларын белгілеу туралы
  kaz: 2009 жылға кесімді салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-14
approved_by:
- '154015000002'
version_date:
  kaz: 2009-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/44892/kaz/14.01.2009
