act_code: '218609'
requisite: Решение акима Каргалинского сельского округа Жамбылского района Алматинской области от 25 ноября 2025 года № 11-174
title:
  rus: Об установлении публичного сервитута для размещения газопровода среднего давления ТОО «Өрлеу GROUP»
  kaz: Орта қысымды газ құбырын орналастыру үшін «Өрлеу GROUP» ЖШС-не жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-25
approved_by:
- '154018024002'
version_date:
  kaz: 2025-11-25
  rus: 2025-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/218609/kaz/25.11.2025
  rus: https://zan.gov.kz/client/#!/doc/218609/rus/25.11.2025
