act_code: '48325'
requisite: Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 15 қазандағы № 28-123 шешімі. Алматы облысының әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 29 қазанда № 2-12-131 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2010 жылғы 21 қыркүйектегі № 39-189 шешімімен
title:
  rus: Қаратал ауданы бойынша ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін бюджет қаражаты есебінен әлеуметтік көмек беру туралы
  kaz: Қаратал ауданы бойынша ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін бюджет қаражаты есебінен әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-15
approved_by:
- '154009000002'
version_date:
  kaz: 2009-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/48325/kaz/15.10.2009
