act_code: '4698'
requisite: Решение акима Алматинской области от 29 июля 1997 года № 7-292. Зарегистрировано Управлением юстиции Алматинской области 1 сентября 1998 года № 56. Утратило силу - решением акима Алматинской области от 29 сентября 2004 года № 9-95
title:
  rus: О Программе по адресной социальной защите населения области на 1997-1998 гг.
  kaz: Облыс халқын бәсірелік әлеуметтік қорғау жөніндегі 1997-1998 жылдарға арналған бағдарлама туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-07-28
approved_by:
- '154000000003'
version_date:
  kaz: 1997-07-28
  rus: 1997-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/4698/kaz/28.07.1997
  rus: https://zan.gov.kz/client/#!/doc/4698/rus/28.07.1997
