act_code: '40804'
requisite: Алматы облысы Іле аудандық мәслихатының 2008 жылғы 5 маусымдағы № 9-29 шешімі. Алматы облысының Әділет департаментінде 2008 жылғы 17 шілдеде № 2-10-78 тіркелді
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-05
approved_by:
- '154017000002'
version_date:
  kaz: 2008-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/40804/kaz/05.06.2008
