act_code: '103070'
requisite: Решение Алакольского районного маслихата Алматинской области от 29 апреля 2016 года № 3-5. Зарегистрировано Департаментом юстиции Алматинской области 27 мая 2016 года № 3855. Утратило силу решением Алакольского районного маслихата Алматинской области от 14 декабря 2020 года № 80-2
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Алакольского района
  kaz: Алакөл ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-29
approved_by:
- '154003000002'
version_date:
  kaz: 2016-04-29
  rus: 2016-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/103070/kaz/29.04.2016
  rus: https://zan.gov.kz/client/#!/doc/103070/rus/29.04.2016
