act_code: '78201'
requisite: Решение маслихата Уйгурского района Алматинской области от 28 февраля 2014 года N 29-1. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2014 года N 2627. Утратило силу решением Уйгурского районного маслихата Алматинской области от 30 мая 2014 года № 34-1
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Уйгурскому району
  kaz: Ұйғыр ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй  көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-02-28
approved_by:
- '154008000002'
version_date:
  kaz: 2014-02-28
  rus: 2014-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/78201/kaz/28.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78201/rus/28.02.2014
