act_code: '128390'
requisite: Решение акима Мынбаевского сельского округа Жамбылского района Алматинской области от 25 декабря 2018 года № 12-108. Зарегистрировано Департаментом юстиции Алматинской области 14 января 2019 года № 4999
title:
  rus: О присвоении наименований новым улицам Мынбаевского сельского округа
  kaz: Мыңбаев ауылдық округінің жаңа көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '154018012002'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128390/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128390/rus/25.12.2018
