act_code: '212129'
requisite: Решение акима Жандосовского сельского округа Карасайского района Алматинской области от 9 июля 2025 года № 60
title:
  rus: Карасайский район Жандосовский сельский округ Село Шалкар Наименование улиц
  kaz: Қарасай ауданы Жандосов ауылдық округі Шалқар ауылының көшелері атау беру
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-09
approved_by:
- '154015002002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/212129/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212129/rus/09.07.2025
