act_code: '94735'
requisite: Решение Илийского районного маслихата Алматинской области от 03 сентября 2015 года № 48-227. Зарегистрировано Департаментом юстиции Алматинской области 13 октября 2015 года № 3480. Утратило силу решением Илийского районного маслихата Алматинской области от 4 мая 2018 года № 27-134
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Илийскому району
  kaz: Іле ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-03
approved_by:
- '154017000002'
version_date:
  kaz: 2016-02-02
  rus: 2016-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/94735/kaz/02.02.2016
  rus: https://zan.gov.kz/client/#!/doc/94735/rus/02.02.2016
caused_by:
  code: '100197'
  requisite: Решение Илийского районного маслихата Алматинской области от 02 февраля 2016 года № 54-254. Зарегистрировано Департаментом юстиции Алматинской области 04 марта 2016 года № 3743. Утратило силу решением Илийского районного маслихата Алматинской области от 4 мая 2018 года № 27-134
  title:
    rus: О внесении изменения в решение Илийского районного маслихата от 3 сентября 2015 года № 48-227 «О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Илийскому району»
    kaz: Іле аудандық мәслихатының 2015 жылғы 3 қыркүйектегі «Іле ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» № 48-227 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100197/rus
