act_code: '94735'
requisite: Решение Илийского районного маслихата Алматинской области от 03 сентября 2015 года № 48-227. Зарегистрировано Департаментом юстиции Алматинской области 13 октября 2015 года № 3480. Утратило силу решением Илийского районного маслихата Алматинской области от 4 мая 2018 года № 27-134
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Илийскому району
  kaz: Іле ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-03
approved_by:
- '154017000002'
version_date:
  kaz: 2015-09-03
  rus: 2015-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/94735/kaz/03.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94735/rus/03.09.2015
