act_code: '40607'
requisite: Алматы облысы Еңбекшіқазақ ауданы Есік қаласы әкімінің 2008 жылғы 2 сәуірдегі № 99 шешімі. Алматы облысының Әділет департаменті Еңбешіқазақ ауданының әділет басқармасында 2008 жылы 7 мамырда № 2-8-84 тіркелді
title:
  rus: Есік қаласындағы "Луговая" атындағы көшенің атауын "Ханкелді батыр" көшесі деп өзгерту туралы
  kaz: Есік қаласындағы "Луговая" атындағы көшенің атауын "Ханкелді батыр" көшесі деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-02
approved_by:
- '154012026002'
version_date:
  kaz: 2008-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/40607/kaz/02.04.2008
