act_code: '54556'
requisite: Алматы облысы Жамбыл ауданы Дегерес селолық округінің әкімінің 2010 жылғы 18 тамыздағы № 8-32 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 20 қыркүйекте № 2-7-109 тіркелді
title:
  rus: Дегерес селолық округіне қарасты Бесмойнақ ауылындағы көше атауын беру туралы
  kaz: Дегерес селолық округіне қарасты Бесмойнақ ауылындағы көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-18
approved_by:
- '154018007002'
version_date:
  kaz: 2010-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/54556/kaz/18.08.2010
