act_code: '160190'
requisite: Решение Уйгурского районного маслихата Алматинской области от 22 октября 2021 года № 7-14-68. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 ноября 2021 года № 25154
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Уйгурском районе
  kaz: Ұйғыр ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-22
approved_by:
- '154008000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/160190/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/160190/rus/13.12.2023
caused_by:
  code: '190053'
  requisite: Решение Уйгурского районного маслихата Алматинской области от 13 декабря 2023 года № 8-13-73. Зарегистрировано Департаментом юстиции Алматинской области 14 декабря 2023 года № 6055-05
  title:
    rus: О внесении изменений в решение Уйгурского  районного маслихата от 22 октября  2021 года № 7-14-68 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Уйгурском районе»
    kaz: Ұйғыр аудандық мәслихатының 2021 жылғы 22 қазандағы № 7-14-68 «Ұйғыр ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190053/rus
