act_code: '108849'
requisite: Решение Талгарского районного маслихата Алматинской области от 22 декабря 2016 года № 10-57. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2015 года № 4053
title:
  rus: О бюджете Талгарского района на 2017-2019 годы
  kaz: Талғар ауданының 2017-2019 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '154013000002'
version_date:
  kaz: 2017-06-09
  rus: 2017-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/108849/kaz/09.06.2017
  rus: https://zan.gov.kz/client/#!/doc/108849/rus/09.06.2017
caused_by:
  code: '113266'
  requisite: Решение Талгарского районного маслихата Алматинской области от 9 июня 2017 года № 15-87. Зарегистрировано Департаментом юстиции Алматинской области 21 июня 2017 года № 4253
  title:
    rus: О внесении изменений в решение Талгарского районного маслихата от 22 декабря 2016 года № 10-57 «О бюджете Талгарского района на 2017-2019 годы»
    kaz: Талғар аудандық мәслихатының 2016 жылғы 22 желтоқсандағы «Талғар ауданының 2017-2019 жылдарға арналған бюджеті туралы» № 10-57 шешіміне өзгерістер енгізу туралы» № 15-87 шешімі
  link: https://zan.gov.kz/client/#!/doc/113266/rus
