act_code: '23166'
requisite: Решение акима Алматинской области от 3 февраля 2005 года № 24. Зарегистрировано Департаментом юстиции Алматинской области 3 марта 2005 года № 1912
title:
  rus: О закреплении рыбопромысловых участков и распределении лимита вылова рыбы между природопользователями в озере Балхаш, и дельты р.Или, Капчагайском водохранилище и Алакольской системе озер на 2005 год
  kaz: Балқаш көлі, Іле өзені сағасы, Қапшағай су қоймасы және Алакөл көлдер жүйесінің табиғат пайдаланушылары арасында 2005 жылы балық аулау лимитін бөлу және кәсіптік балық учаскелерін бөліп беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-02-03
approved_by:
- '154000000003'
version_date:
  kaz: 2005-02-03
  rus: 2005-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/23166/kaz/03.02.2005
  rus: https://zan.gov.kz/client/#!/doc/23166/rus/03.02.2005
