act_code: '49410'
requisite: Алматы облысы Еңбекшіқазақ ауданы әкімінің 2009 жылғы 16 қарашадағы № 11-148 шешімі. Алматы облысы Әділет департаменті Еңбекшіқазақ ауданының әділет басқармасында 2009 жылы 11 желтоқсанда № 2-8-130 тіркелді. Күші жойылды - Алматы облысы Еңбекшіқазақ ауданы әкімінің 2010 жылғы 03 желтоқсандағы № 12-163 шешімімен
title:
  rus: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
  kaz: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-16
approved_by:
- '154012000003'
version_date:
  kaz: 2009-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/49410/kaz/16.11.2009
