act_code: '148199'
requisite: Решение Райымбекского районного маслихата Алматинской области от 23 октября 2020 года № 76-360. Зарегистрировано Департаментом юстиции Алматинской области 5 ноября 2020 года № 5729
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Райымбекском районе
  kaz: Райымбек ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-23
approved_by:
- '154016000002'
version_date:
  kaz: 2024-08-20
  rus: 2024-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/148199/kaz/20.08.2024
  rus: https://zan.gov.kz/client/#!/doc/148199/rus/20.08.2024
caused_by:
  code: '200024'
  requisite: Решение Райымбекского районного маслихата Алматинской области от 20 августа 2024 года № 29-162. Зарегистрировано Департаментом юстиции Алматинской области 22 августа 2024 года № 6152-05
  title:
    rus: О внесении изменения в решение Райымбекского районного маслихата от 23 октября 2020 года № 76-360 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Райымбекском районе»
    kaz: Райымбек аудандық мәслихатының 2020 жылғы 23 қазандағы «Райымбек ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» № 76-360 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200024/rus
