act_code: '102572'
requisite: Решение Аксусского районного маслихата Алматинской области от 14 апреля 2016 года № 2-9. Зарегистрировано Департаментом юстиции Алматинской области 17 мая № 3835. Утратило силу решением Аксуского районного маслихата Алматинской области от 30 марта 2017 года № 13-61
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса "Б" аппарата Аксуского районного маслихата
  kaz: Ақсу аудандық мәслихаты аппаратының "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-04-14
approved_by:
- '154011000002'
version_date:
  kaz: 2016-04-14
  rus: 2016-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/102572/kaz/14.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102572/rus/14.04.2016
