act_code: '46331'
requisite: Талғар аудандық мәслихатының 2009 жылғы 22 сәуірдегі № 20-116 шешімі. Алматы облысы Талғар ауданының Әділет басқармасында 2009 жылғы 3 маусымда № 2-18-85 тіркелді
title:
  rus: Талғар ауданының ауылдық жерлерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының қызметкерлеріне отын сатып алу үшін 2009 жылға әлеуметтік көмек төлеу туралы
  kaz: Талғар ауданының ауылдық жерлерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының қызметкерлеріне отын сатып алу үшін 2009 жылға әлеуметтік көмек төлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '154013000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46331/kaz/22.04.2009
