act_code: '37931'
requisite: Алматы облысы Райымбек аудандық мәслихатының 2008 жылғы 30 қаңтардағы № 8-44 шешімі. Алматы облысының Әділет департаменті Райымбек ауданының Әділет басқармасында 2008 жылдың 11 ақпанында № 2-15-52 тіркелді. Күші жойылды - Алматы облысы Райымбек аудандық мәслихатының 2009 жылғы 31 наурыздағы № 22-110 шешімімен
title:
  rus: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
  kaz: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-30
approved_by:
- '154016000002'
version_date:
  kaz: 2008-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/37931/kaz/30.01.2008
