act_code: '57157'
requisite: Алматы облысы Жамбыл ауданы әкімінің 2010 жылғы 31 желтоқсандағы № 12-100 шешімі. Алматы облысының Әділет департаменті Жамбыл ауданының Әділет басқармасында 2011 жылдың 31 қаңтарында № 2-7-114 тіркелді. Күші жойылды - Алматы облысы Жамбыл ауданы әкімінің 2012 жылғы 15 ақпандағы № 2-10 шешімімен
title:
  rus: 1994 жылы туылған азаматтарды әскерге  шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскерге  шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-31
approved_by:
- '154018000003'
version_date:
  kaz: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/57157/kaz/31.12.2010
