act_code: '14813'
requisite: Решение Алматинского областного маслихата от 24 января 2003 года № 32-175. Зарегистрировано Департаментом юстиции Алматинской области 14 февраля 2003 года № 1032. Утратило силу решением Алматинского областного маслихата от 21 декабря 2004 года № 13-89
title:
  rus: О кредитовании сельскохозяйственных товаропроизводителей
  kaz: Ауыл шаруашылығы товарларын өндірушілерге кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-01-24
approved_by:
- '154000000002'
version_date:
  kaz: 2003-01-24
  rus: 2003-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/14813/kaz/24.01.2003
  rus: https://zan.gov.kz/client/#!/doc/14813/rus/24.01.2003
