act_code: '206465'
requisite: Решение Талгарского районного маслихата Алматинской области от 31 декабря 2024 года № 36-134
title:
  rus: О бюджетах города Талгар и сельских округов Талгарского района на 2025-2027 годы
  kaz: Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '154013000002'
version_date:
  kaz: 2024-12-31
  rus: 2024-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/206465/kaz/31.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206465/rus/31.12.2024
