act_code: '128848'
requisite: Решение Талгарского районного маслихата Алматинской области от 27 декабря 2018 года № 38-176. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2019 года № 5009
title:
  rus: О бюджете Талгарского района на 2019-2021 годы
  kaz: Талғар ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '154013000002'
version_date:
  kaz: 2019-09-11
  rus: 2019-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/128848/kaz/11.09.2019
  rus: https://zan.gov.kz/client/#!/doc/128848/rus/11.09.2019
caused_by:
  code: '134925'
  requisite: Решение Талгарского районного маслихата Алматинской области от 11 сентября 2019 года № 49-221. Зарегистрировано Департаментом юстиции Алматинской области 20 сентября 2019 года № 5249
  title:
    rus: О внесении изменений в решение Талгарского районного маслихата от 27 декабря 2018 года № 38-176 «О бюджете Талгарского района на 2019-2021 годы»
    kaz: Талғар аудандық мәслихатының 2018 жылғы 27 желтоқсандағы «Талғар ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 38-176 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134925/rus
