act_code: '51410'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 05 ақпандағы № 31-3 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 17 наурызда № 2-19-91 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-7 шешімімен
title:
  rus: Ұйғыр ауданы жерлерін өңірлерге бөлу сызбасы мен 2010 жылғы базалық ставкаларды ықшамдаудың нақты мөлшерін бекіту туралы
  kaz: Ұйғыр ауданы жерлерін өңірлерге бөлу сызбасы мен 2010 жылғы базалық ставкаларды ықшамдаудың нақты мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-05
approved_by:
- '154008000002'
version_date:
  kaz: 2010-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51410/kaz/05.02.2010
