act_code: '102992'
requisite: Решение Коксуского районного маслихата Алматинской области от 06 мая 2016 года № 3-4. Зарегистрировано Департаментом юстиции Алматинской области 31 мая 2016 года № 3870. Утратило силу решением Коксуского районного маслихата Алматинской области от 7 апреля 2020 года № 60-12
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Коксуского района
  kaz: Көксу ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2016-05-06
approved_by:
- '154007000002'
version_date:
  kaz: 2016-05-06
  rus: 2016-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/102992/kaz/06.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102992/rus/06.05.2016
