act_code: '19969'
requisite: Решение Алматинского областного маслихата от 13 апреля 2004 года № 5-36. Зарегистрировано Департаментом юстиции Алматинской области 24 мая 2004 года № 1634. Утратил силу решением Алматинского областного маслихата от 14 января 2005 года № 14-101
title:
  rus: Об утверждении Положения о размере и порядке оказания жилищной помощи в Алматинской области
  kaz: Алматы облысында тұрғын үй көмегін көрсету мөлшері және тәртібі жөніндегі Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2004-04-12
approved_by:
- '154000000002'
version_date:
  kaz: 2004-04-12
  rus: 2004-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/19969/kaz/12.04.2004
  rus: https://zan.gov.kz/client/#!/doc/19969/rus/12.04.2004
