act_code: '76766'
requisite: Решение маслихата Панфиловского района Алматинской области от 19 декабря 2013 года N 5-25-170. Зарегистрировано Департаментом юстиции Алматинской области 31 декабря 2013 года N 2549
title:
  rus: О районном бюджете Панфиловского района на 2014-2016 годы
  kaz: Панфилов ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-19
approved_by:
- '154004000001'
version_date:
  kaz: 2014-10-14
  rus: 2014-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/76766/kaz/14.10.2014
  rus: https://zan.gov.kz/client/#!/doc/76766/rus/14.10.2014
caused_by:
  code: '84090'
  requisite: Решение Панфиловского районного маслихата Алматинской области от 14 октября 2014 года N 5-38-250. Зарегистрировано Департаментом юстиции Алматинской области 24 октября 2014 года N 2877
  title:
    rus: О внесении изменений в решение Панфиловского районного маслихата от 19 декабря 2013 года № 5-25-170 "О районном бюджете Панфиловского района на 2014-2016 годы"
    kaz: Панфилов аудандық мәслихатының 2013 жылғы 19 желтоқсандағы "Панфилов ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы" № 5-25-170 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84090/rus
