act_code: '140054'
requisite: Решение Капшагайского городского маслихата Алматинской области от 25 февраля 2020 года № 66-235. Зарегистрировано Департаментом юстиции Алматинской области 5 марта 2020 года № 5433. Утратило силу решением Капшагайского городского маслихата Алматинской области от 14 октября 2020 года № 78-275
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта,  ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими и работающим в сельских населенных пунктах, а также указанным специалистам, работающим в государственных организациях, финансируемых из местных бюджетов города Капшагай
  kaz: Қапшағай қаласының азаматтық  қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға, сондай-ақ жергілікті бюджеттерден қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін аталған мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-25
approved_by:
- '154020000002'
version_date:
  kaz: 2020-02-25
  rus: 2020-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/140054/kaz/25.02.2020
  rus: https://zan.gov.kz/client/#!/doc/140054/rus/25.02.2020
