act_code: '51071'
requisite: Алматы облысы Көксу аудандық мәслихатының 2010 жылғы 23 ақпандағы № 36-9 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2010 жылы 10 наурызда № 2-14-91 тіркелді. Күші жойылды - Алматы облысы Көксу аудандық мәслихатының 2011 жылғы 28 наурыздағы № 54-2 шешімімен
title:
  rus: Көксу ауданы бойынша жер салығының 2010 жылға арналған базалық ставкасын бекіту туралы
  kaz: Көксу ауданы бойынша жер салығының 2010 жылға арналған базалық ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-23
approved_by:
- '154007000002'
version_date:
  kaz: 2010-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/51071/kaz/23.02.2010
