act_code: '49678'
requisite: Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 15 желтоқсандағы № 31-141 шешімі. Алматы облысының әділет департаменті Қаратал ауданының әділет басқармасында 2010 жылы 05 қаңтарда № 2-12-137 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2011 жылғы 29 наурыздағы № 47-228 шешімімен
title:
  rus: Қаратал ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Қаратал ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-15
approved_by:
- '154009000002'
version_date:
  kaz: 2010-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/49678/kaz/20.08.2010
caused_by:
  code: '54235'
  requisite: Алматы облысы Қаратал аудандық мәслихатының 2010 жылғы 20 тамыздағы № 38-180 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының Әділет басқармасында 2010 жылы 27 тамызда № 2-12-156 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2011 жылғы 29 наурыздағы № 47-228 шешімімен
  title:
    rus: Қаратал аудандық мәслихатының 2009 жылғы 15 желтоқсандағы "Қаратал ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 31-141 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қаратал аудандық мәслихатының 2009 жылғы 15 желтоқсандағы "Қаратал ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 31-141 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54235/rus
