act_code: '65734'
requisite: Решение маслихата Ескельдинского района Алматинской области от 17 апреля 2012 года № 5-27. Зарегистрировано Управлением юстиции Ескельдинского района Департамента юстиции Алматинской области 22 мая 2012 года № 2-9-137. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 12 декабря 2014 года № 46-250
title:
  rus: Об установлении специалистам Ескельдинского района работающим в сельских населенных пунктах в сфере здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии надбавки к окладам и тарифным ставкам в размере двадцати пяти процентов
  kaz: Ескелді ауданы бойынша ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария мамандарына жиырма бес процент жоғары айлықақы мен тарифтік ставкалар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-17
approved_by:
- '154006000002'
version_date:
  kaz: 2012-09-06
  rus: 2012-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/65734/kaz/06.09.2012
  rus: https://zan.gov.kz/client/#!/doc/65734/rus/06.09.2012
caused_by:
  code: '67930'
  requisite: Решение маслихата Ескельдинского района Алматинской области от 06 сентября 2012 года № 12-64. Зарегистрировано Департаментом юстиции Алматинской области 05 октября 2012 года № 2142. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 12 декабря 2014 года № 46-250
  title:
    rus: О внесении изменений в решение Ескельдинского районного маслихата от 17 апреля 2012 года N 5-27 "Об установлении повышенных тарифных ставок в размере двадцати пяти процентов специалистам здравоохранения, социального обеспечения, образования, культуры и спорта работающим в сельских населенных пунктах Ескельдинского района"
    kaz: Ескелді ауданы мәслихатының 2012 жылғы 17 сәуірдегі N 5-27 "Ескелді ауданының ауылдық елді мекендерінде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына жиырма бес процент мөлшерінде жоғарылатылған тарифтік ставкалар белгілеу туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67930/rus
