act_code: '175565'
requisite: Решение Карасайского районного маслихата Алматинской области от 15 декабря 2022 года № 30-4
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Карасайскому району на 2023-2024 годы
  kaz: Қарасай ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-15
approved_by:
- '154015000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/175565/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175565/rus/15.12.2022
