act_code: '138382'
requisite: Решение Райымбекского районного маслихата Алматинской области от 25 декабря 2019 года № 63-302. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2020 года № 5397
title:
  rus: О бюджете Райымбекского района на 2020-2022 годы
  kaz: Райымбек ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '154016000002'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138382/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138382/rus/08.09.2020
caused_by:
  code: '146295'
  requisite: Решение Райымбекского районного маслихата Алматинской области от 8 сентября 2020 года № 74-353. Зарегистрировано Департаментом юстиции Алматинской области 14 сентября 2020 года № 5647
  title:
    rus: О внесении изменений в решение Райымбекского районного маслихата от 25 декабря 2019 года № 63-302 «О бюджете Райымбекского района на 2020-2022 годы»
    kaz: Райымбек аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 63-302 «Райымбек ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146295/rus
