act_code: '117387'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 22 декабря 2017 года № 23-156. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2017 года № 4458
title:
  rus: О бюджете Ескельдинского района на 2018-2020 годы
  kaz: Ескелді ауданының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '154006000002'
version_date:
  kaz: 2018-04-28
  rus: 2018-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/117387/kaz/28.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117387/rus/28.04.2018
caused_by:
  code: '121874'
  requisite: Решение Ескельдинского районного маслихата Алматинской области от 28 апреля 2018 года № 30-198. Зарегистрировано Департаментом юстиции Алматинской области 16 мая 2018 года № 4704
  title:
    rus: О внесении изменений в решение Ескельдинского районного маслихата от 22 декабря 2017 года № 23-156 «О бюджете Ескельдинского района на 2018-2020 годы»
    kaz: Ескелді аудандық мәслихатының 2017 жылғы 22 желтоқсандағы «Ескелді ауданының 2018-2020 жылдарға арналған бюджеті туралы» № 23-156 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121874/rus
