act_code: '111911'
requisite: Решение Аксуского районного маслихата Алматинской области от 30 марта 2017 года № 13-61. Зарегистрировано Департаментом юстиции Алматинской области 27 апреля 2017 года года № 4201. Утратило силу решением Аксуского районного маслихата Алматинской области от 26 марта 2018 года № 26-126
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Аксуского районного маслихата
  kaz: Ақсу аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2017-03-30
approved_by:
- '154011000002'
version_date:
  kaz: 2017-03-30
  rus: 2017-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/111911/kaz/30.03.2017
  rus: https://zan.gov.kz/client/#!/doc/111911/rus/30.03.2017
