act_code: '81320'
requisite: Решение акима Бастобинского сельского округа Каратальского района Алматинской области от 30 июня 2014 года № 20. Зарегистрировано Департаментом юстиции Алматинской области 10 июля 2014 года № 2766. Утратило силу - решением акима Бастобинского сельского округа Каратальского района Алматинской области от 03 октября 2014 года № 29
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-30
approved_by:
- '154009007002'
version_date:
  kaz: 2014-06-30
  rus: 2014-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/81320/kaz/30.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81320/rus/30.06.2014
