act_code: '103495'
requisite: Решение Каратальского районного маслихата Алматинской области от 08 июня 2016 года № 6-21. Зарегистрировано Департаментом юстиции Алматинской области 14 июня 2016 года № 3887. Утратило силу решением Каратальского районного маслихата Алматинской области от 31 марта 2020 года № 68-243
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Каратальского района
  kaz: Қаратал ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2016-06-08
approved_by:
- '154009000002'
version_date:
  kaz: 2016-06-08
  rus: 2016-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/103495/kaz/08.06.2016
  rus: https://zan.gov.kz/client/#!/doc/103495/rus/08.06.2016
