act_code: '69789'
requisite: Решение маслихата Карасайского района Алматинской области от 24 декабря 2012 года № 14-3. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2012 года № 2276. Утратило силу решением Карасайского районного маслихата Алматинской области от 06 августа 2014 года № 33-7
title:
  rus: О районном бюджете Карасайского района на 2013-2015 годы
  kaz: Қарасай ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-24
approved_by:
- '154015000002'
version_date:
  kaz: 2013-09-30
  rus: 2013-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/69789/kaz/30.09.2013
  rus: https://zan.gov.kz/client/#!/doc/69789/rus/30.09.2013
caused_by:
  code: '74722'
  requisite: Решение маслихата Карасайского района Алматинской области от 30 сентября 2013 года № 23-3. Зарегистрировано Департаментом юстиции Алматинской области 07 октября 2013 года № 2453. Утратило силу решением Карасайского районного маслихата Алматинской области от 06 августа 2014 года № 33-7
  title:
    rus: О внесении изменений в решение Карасайского районного Маслихата от 24 декабря  2012 года N 14-3 "О районном бюджете Карасайского района на 2013-2015 годы"
    kaz: Қарасай аудандық мәслихатының 2012 жылғы 24 желтоқсандағы "Қарасай ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы" N 14-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/74722/rus
