act_code: '128705'
requisite: Решение Жамбылского районного маслихата Алматинской области от 27 декабря 2018 года № 47-220. Зарегистрировано Департаментом юстиции Алматинской области 16 января 2019 года № 5004
title:
  rus: О бюджете Жамбылского района на 2019-2021 годы
  kaz: Жамбыл ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '154018000002'
version_date:
  kaz: 2019-03-19
  rus: 2019-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128705/kaz/19.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128705/rus/19.03.2019
caused_by:
  code: '130124'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 19 марта 2019 года № 51-238. Зарегистрировано Департаментом юстиции Алматинской области 29 марта 2019 года № 5077
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 27 декабря 2018 года № 47-220 «О бюджете Жамбылского района на 2019-2021 годы»
    kaz: Жамбыл аудандық мәслихатының 2018 жылғы 27 желтоқсандағы «Жамбыл ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 47-220 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130124/rus
