act_code: '140511'
requisite: Решение Уйгурского районного маслихата Алматинской области от 17 марта 2020 года № 6-61-350. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2020 года № 5441. Утратило силу решением Уйгурского районного маслихата Алматинской области от 11 октября 2023 года № 8-10-52
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Уйгурского района
  kaz: Ұйғыр ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-17
approved_by:
- '154008000002'
version_date:
  kaz: 2020-03-17
  rus: 2020-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/140511/kaz/17.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140511/rus/17.03.2020
