act_code: '55453'
requisite: Алматы облысы Алакөл ауданы Ырғайты ауылдық округі әкімінің 2010 жылғы 22 қазандағы № 68 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 17 қарашада № 2-5-133 тіркелді
title:
  rus: Ырғайты округіне қарасты Ақши ауылындағы атаусыз көшеге ат қою туралы
  kaz: Ырғайты округіне қарасты Ақши ауылындағы атаусыз көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-22
approved_by:
- '154003023002'
version_date:
  kaz: 2010-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/55453/kaz/22.10.2010
