act_code: '42479'
requisite: Алматы облысы Қапшағай қалалық мәслихатының 2008 жылғы 14 қарашадағы № 99-17 шешімі. Алматы облысы әділет департаменті Қапшағай қаласының әділет басқармасында 2008 жылы 26 қарашада № 2-2-71 тіркелді. Күші жойылды - Алматы облысы Қапшағай қалалық мәслихатының 2009 жылғы 26 наурыздағы № 137-24 шешімімен
title:
  rus: Қапшағай қаласының ауылдық елді мекендерінде тұратын және жұмыс істейтін мәдениет қызметкерлеріне отын сатып алу үшін әлеуметтік көмек беру туралы
  kaz: Қапшағай қаласының ауылдық елді мекендерінде тұратын және жұмыс істейтін мәдениет қызметкерлеріне отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-14
approved_by:
- '154020000002'
version_date:
  kaz: 2008-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/42479/kaz/14.11.2008
