act_code: '56335'
requisite: Алматы облысы Көксу аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 48-2 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2010 жылы 30 желтқсанда № 2-14-102 тіркелді. Күші жойылды - Алматы облысы Көксу аудандық мәслихатының 2013 жылғы 05 маусымдағы № 15-3 шешімімен
title:
  rus: Көксу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Көксу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '154007000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56335/kaz/22.12.2010
