act_code: '127066'
requisite: Решение акима Балхашского района Алматинской области от 14 декабря 2018 года № 12-3. Зарегистрировано Департаментом юстиции Алматинской области 14 декабря 2018 года № 4953
title:
  rus: Об образовании избирательных участков на территории Балхашского района
  kaz: Балқаш ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '154014000003'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/127066/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/127066/rus/31.03.2026
caused_by:
  code: '223859'
  requisite: Решение акима Балхашского района Алматинской области от 31 марта 2026 года № 3-1
  title:
    rus: «Проведение голосования в Балхашском районе и избирательных участков для подсчета голосов акима Балхашского района» о создании от 14 декабря 2018 года о внесении изменений в решение № 12-3
    kaz: «Балқаш ауданында дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы» Балқаш ауданы әкімінің 2018 жылғы 14 желтоқсанындағы № 12-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223859/rus
