act_code: '127066'
requisite: Решение акима Балхашского района Алматинской области от 14 декабря 2018 года № 12-3. Зарегистрировано Департаментом юстиции Алматинской области 14 декабря 2018 года № 4953
title:
  rus: Об образовании избирательных участков на территории Балхашского района
  kaz: Балқаш ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '154014000003'
version_date:
  kaz: 2020-07-02
  rus: 2020-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/127066/kaz/02.07.2020
  rus: https://zan.gov.kz/client/#!/doc/127066/rus/02.07.2020
caused_by:
  code: '144541'
  requisite: Решение акима Балхашского района Алматинской области от 2 июля 2020 года № 07-01. Зарегистрировано Департаментом юстиции Алматинской области 3 июля 2020 года № 5557
  title:
    rus: О внесении изменений в решение акима Балхашского района от 14 декабря 2018 года № 12-3 «Об образовании избирательных участков для проведения голосования и подсчета голосов по Балхашскому району»
    kaz: Балқаш ауданы әкімінің 2018 жылғы 14 желтоқсандағы № 12-3 «Балқаш ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144541/rus
