act_code: '127066'
requisite: Решение акима Балхашского района Алматинской области от 14 декабря 2018 года № 12-3. Зарегистрировано Департаментом юстиции Алматинской области 14 декабря 2018 года № 4953
title:
  rus: Об образовании избирательных участков на территории Балхашского района
  kaz: Балқаш ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '154014000003'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127066/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/127066/rus/29.12.2022
caused_by:
  code: '176710'
  requisite: Решение акима Балхашского района Алматинской области от 29 декабря 2022 года № 12-02. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2022 года № 31365
  title:
    rus: О внесении изменений в решение акима Балхашского района от 14 декабря 2018 года № 12-3 «Об образовании избирательных участков для проведения голосования и подсчета голосов по Балхашскому району»
    kaz: «Балқаш ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы» Балқаш ауданы әкімінің 2018 жылғы 14 желтоқсандағы № 12-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176710/rus
