act_code: '48602'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2009 жылғы 9 қазандағы № 136 шешімі. Алматы облысының әділет департаменті Талдықорған қаласының әділет басқармасында 2009 жылы 12 қарашада № 2-1-105 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2013 жылғы 05 маусымдағы № 134 шешімімен
title:
  rus: Талдықорған қаласы бойынша бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Талдықорған қаласы бойынша бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-09
approved_by:
- '154002000002'
version_date:
  kaz: 2009-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/48602/kaz/09.10.2009
