act_code: '120277'
requisite: Решение Каратальского районного маслихата Алматинской области от 16 марта 2018 года № 31-134. Зарегистрировано Департаментом юстиции Алматинской области 6 апреля 2018 года № 4628. Утратило силу решением Каратальского районного маслихата области Жетісу от 22 ноября 2023 года № 14-49
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Каратальского района
  kaz: Қаратал ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-03-16
approved_by:
- '154009000002'
version_date:
  kaz: 2020-04-07
  rus: 2020-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/120277/kaz/07.04.2020
  rus: https://zan.gov.kz/client/#!/doc/120277/rus/07.04.2020
caused_by:
  code: '141740'
  requisite: Решение Каратальского районного маслихата Алматинской области от 7 апреля 2020 года № 69-247. Зарегистрировано Департаментом юстиции Алматинской области 15 апреля 2020 года № 5479. Утратило силу решением Каратальского районного маслихата области Жетісу от 22 ноября 2023 года № 14-49
  title:
    rus: О внесении изменений и дополнения в решение Каратальского районного маслихата от 16 марта 2018 года № 31-134 «Об утверждении Правил оказания социальной помощи,установления размеров и определения перечня отдельных категорий нуждающихся граждан Каратальского района»
    kaz: Қаратал аудандық мәслихатының 2018 жылғы 16 наурыздағы № 31-134 «Қаратал ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141740/rus
