act_code: '99246'
requisite: Решение Коксуского районного маслихата Алматинской области от 05 февраля 2016 года № 52-2. Зарегистрировано Департаментом юстиции Алматинской области 17 февраля 2016 года № 3731. Утратило силу решением Коксуского районного маслихата Алматинской области от 1 сентября 2021 года № 11-2
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Коксуском районе
  kaz: Көксу ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-05
approved_by:
- '154007000002'
version_date:
  kaz: 2016-02-05
  rus: 2016-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/99246/kaz/05.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99246/rus/05.02.2016
