act_code: '117305'
requisite: Решение Илийского районного маслихата Алматинской области от 27 мая 2015 года № 46-217
title:
  rus: О признании утратившим силу решения Илийского районного маслихата
  kaz: Іле аудандық мәслихат шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-27
approved_by:
- '154017000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/117305/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/117305/rus/27.05.2015
