act_code: '1469'
requisite: Решение акима Алматинской области от 7 ноября 1995 года № 1-52. Зарегистрировано Управлением юстиции Алматинской области 17 августа 1998 года № 39. Утратило силу решением акима Алматинской области от 29 сентября 2004 года № 9-96
title:
  rus: О реализации Постановления Кабинета Министров Республики Казахстан N 1230 от 05.09.95г. "О мерах по регулированию численности отдельных видов хищников в республике"
  kaz: Қазақстан Республикасы Министрлер Кабинетiнiң "Республикада жыртқыштардың жекелеген түрлерiнiң санын реттеу жөнiндегi шаралар туралы" 1995 жылғы 5 қыркүйектегi N 1230 қаулысын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1995-11-07
approved_by:
- '154000000003'
version_date:
  kaz: 1995-11-07
  rus: 1995-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/1469/kaz/07.11.1995
  rus: https://zan.gov.kz/client/#!/doc/1469/rus/07.11.1995
