act_code: '56343'
requisite: Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-1 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 31 желтоқсанда № 2-8-167 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2012 жылғы 19 сәуірдегі № 6-12 шешімімен
title:
  rus: Еңбекшіқазақ ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Еңбекшіқазақ ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '154012000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56343/kaz/22.12.2010
