act_code: '124101'
requisite: Решение Алматинского областного маслихата от 25 июля 2018 года № 34-175. Зарегистрировано Департаментом юстиции Алматинской области 8 августа 2018 года № 4781. Утратило силу решением Алматинского областного маслихата от 20 марта 2025 года № 35-190 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда Алматинской области
  kaz: Алматы облысының мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-25
approved_by:
- '154000000002'
version_date:
  kaz: 2018-07-25
  rus: 2018-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/124101/kaz/25.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124101/rus/25.07.2018
