act_code: '160650'
requisite: Решение Жамбылского районного маслихата Алматинской области от 23 ноября 2021 года № 12-72. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 ноября 2021 года № 25353
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границы оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Жамбылского района
  kaz: Жамбыл ауданының жерлерін аймақтарға бөлу жобасын (схемасын), елді мекендердегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2021-11-23
approved_by:
- '154018000002'
version_date:
  kaz: 2021-11-23
  rus: 2021-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/160650/kaz/23.11.2021
  rus: https://zan.gov.kz/client/#!/doc/160650/rus/23.11.2021
