act_code: '74335'
requisite: Решение маслихата Алматинской области от 09 августа 2013 года № 21-133. Зарегистрировано Департаментом юстиции Алматинской области 06 сентября 2013 года № 2446. Утратило силу решением маслихата Алматинской области от 8 августа 2022 года № 24-120
title:
  rus: Об утверждении границ охранных зон, зон регулирования застройки и зон охраняемого природного ландшафта объектов историко-культурного наследия  Республиканского государственного казенного предприятия "Государственный  историко-культурный заповедник-музей "Иссык" Комитета культуры  Министерства культуры и информации Республики Казахстан
  kaz: Қазақстан Республикасы Мәдениет министрлігі Мәдениет комитетінің "Есік" мемлекеттік тарихи-мәдени қорық-мұражайы" республикалық мемлекеттік қазыналық кәсіпорнының тарихи-мәдени мұра объектілерінің қорғау аймақтарының, құрылыс салуды реттеу аймақтары мен қорғалатын табиғат ландшафты аймақтарының шекараларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-09
approved_by:
- '154000000002'
version_date:
  kaz: 2013-08-09
  rus: 2013-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/74335/kaz/09.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74335/rus/09.08.2013
