act_code: '85659'
requisite: Решение №42-1 от 19.12.2014, Маслихат Уйгурского района
title:
  rus: 'ИМПОРТ: "О районном бюджете Уйгурского района на 2015-2017 годы"'
  kaz: 'ИМПОРТ: Ұйғыр ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154008000002'
version_date:
  kaz: 2014-12-19
  rus: 2014-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85659/kaz/19.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85659/rus/19.12.2014
