act_code: '85617'
requisite: Решение №279 от 18.12.2014, Маслихат г. Талдыкоргана
title:
  rus: О бюджете города Талдыкорган на 2015-2017 годы
  kaz: 'Талдықорған қаласының 2015-2017 жылдарға арналған бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-18
approved_by:
- '154002000002'
version_date:
  kaz: 2015-10-30
  rus: 2015-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/85617/kaz/30.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85617/rus/30.10.2015
caused_by:
  code: '95564'
  requisite: Решение от 30.10.2015 №347, Маслихат г. Талдыкоргана
  title:
    rus: О внесении изменений и дополнений в решение Талдыкорганского городского маслихата от 18 декабря 2014 года № 279 "О бюджете города Талдыкорган на 2015-2017 годы"
    kaz: Талдықорған қалалық мәслихатының 2014 жылғы 18 желтоқсандағы "Талдықорған қаласының 2015-2017 жылдарға арналған бюджеті туралы" № 279 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95564/rus
