act_code: '129185'
requisite: Решение Кегенского районного маслихата Алматинской области от 21 января 2019 года № 15-52. Зарегистрировано Департаментом юстиции Алматинской области 21 января 2019 года № 5018
title:
  rus: О бюджете Кегенского района на 2019-2021 годы
  kaz: Кеген ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-21
approved_by:
- '154021000002'
version_date:
  kaz: 2019-03-19
  rus: 2019-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/129185/kaz/19.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129185/rus/19.03.2019
caused_by:
  code: '130356'
  requisite: Решение Кегенского районного маслихата Алматинской области от 19 марта 2019 года № 17-63. Зарегистрировано Департаментом юстиции Алматинской области 1 апреля 2019 года № 5082
  title:
    rus: О внесении изменений в решение Кегенского районного маслихата от 21 января 2019 года № 15-52 «О бюджете Кегенского района на 2019-2021 годы»
    kaz: Кеген аудандық мәслихатының 2019 жылғы 21 қаңтардағы «Кеген ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 15-52 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130356/rus
