act_code: '49362'
requisite: Алматы облысы Ақсу ауданы Жансугуров поселкелік округі әкімінің 2009 жылғы 26 қарашадағы № 2 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2009 жылы 20 желтоқсанда № 2-4-96 тіркелді
title:
  rus: Жансүгіров ауылындағы атауы жоқ көшеге Есенқұл Маманұлы атындағы көше атауын беру туралы
  kaz: Жансүгіров ауылындағы атауы жоқ көшеге Есенқұл Маманұлы атындағы көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-26
approved_by:
- '154011018001'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49362/kaz/26.11.2009
