act_code: '40501'
requisite: Алматы облысы Қаратал ауданы Қаңбақты округі әкімінің 2008 жылғы 12 маусымдағы № 1 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының әділет басқармасында 2008 жылы 30 маусымда № 2-12-84 тіркелді
title:
  rus: Алмалы ауылындағы Г. Жуков көшесінің атын өзгерту туралы
  kaz: Алмалы ауылындағы Г. Жуков көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-12
approved_by:
- '154009004002'
version_date:
  kaz: 2008-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/40501/kaz/12.06.2008
