act_code: '1577'
requisite: Решение акима Алматинской области от 11 июня 1997 года № 6-194. Зарегистрировано Управлением юстиции Алматинской области 19 августа 1998 года № 41. Утратило силу решением акима Алматинской области от 30 января 2004 года № 1-14
title:
  rus: О программе работ по выполнению постановления Правительства Республики Казахстан от 21 января 1997 года № 89 "Об основных направлениях по улучшению условий и охраны труда в отраслях экономики Республики Казахстан на 1997-2000 годы" в Алматинской области
  kaz: Қазақстан Республикасы Үкiметiнiң "Қазақстан Республикасының экономикасы салаларында еңбек жағдайларымен оны қорғауды жақсарту жөнiндегi 1997-2000 жылдарға арналған негiзгi бағыттары туралы" 1997 жылғы 21 қаңтардағы № 89 қаулысына сәйкес жасалған Алматы облысының бағдарламасы жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-06-10
approved_by:
- '154000000003'
version_date:
  kaz: 1997-06-10
  rus: 1997-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/1577/kaz/10.06.1997
  rus: https://zan.gov.kz/client/#!/doc/1577/rus/10.06.1997
