act_code: '49677'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2009 жылғы 21 желтоқсандағы N 4-25-159 шешімі. Алматы облысының әділет департаменті Панфилов ауданының әділет басқармасында 2009 жылы 29 желтоқсанда N 2-16-99 тіркелді. Күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 4-38-243 шешімімен
title:
  rus: Панфилов ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Панфилов ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '154004000002'
version_date:
  kaz: 2010-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49677/kaz/03.02.2010
caused_by:
  code: '50777'
  requisite: Алматы облысы Панфилов аудандық мәслихатының 2010 жылғы 03 ақпандағы № 4-26-170 шешімі. Алматы облысының әділет департаменті Панфилов ауданының әділет басқармасында 2010 жылы 18 ақпанда № 2-16-101 тіркелді. Күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 4-38-243 шешімімен
  title:
    rus: 2009 жылғы 21 желтоқсандағы "Панфилов ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 4-25-159 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылғы 21 желтоқсандағы "Панфилов ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 4-25-159 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50777/rus
