act_code: '54538'
requisite: Алматы облысы Қаратал ауданы Бастөбе ауылдық округі әкімінің 2010 жылғы 10 тамыздағы № 8-07 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының Әділет басқармасында 2010 жылы 16 қыркүйекте № 2-12-157 тіркелді
title:
  rus: Жылыбұлақ ауылындағы Ленин көшесінің атауын өзгерту туралы
  kaz: Жылыбұлақ ауылындағы Ленин көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-10
approved_by:
- '154009007002'
version_date:
  kaz: 2009-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/54538/kaz/10.08.2009
