act_code: '13159'
requisite: Решение акима Алматинской области от 19 июля 2002 года № 7-179. Зарегистрировано Управлением юстиции Алматинской области 02 сентября 2002 года № 798. Утратило силу решением акима Алматинской области от 02 июня 2004 года № 6-58
title:
  rus: О создании Координационного Совета при Акимате Алматинской области
  kaz: Алматы облысы әкімдігінің жанындағы Үйлестіру Кеңесін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-07-18
approved_by:
- '154000000003'
version_date:
  kaz: 2002-07-18
  rus: 2002-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/13159/kaz/18.07.2002
  rus: https://zan.gov.kz/client/#!/doc/13159/rus/18.07.2002
