act_code: '126998'
requisite: Решение акима сельского округа Жолбарыс батыра Каратальского района Алматинской области от 11 декабря 2018 года № 29. Зарегистрировано Департаментом юстиции Алматинской области 19 декабря 2018 года № 4965
title:
  rus: О снятии ограничительных мероприятий в селе Кальпе по улицам Т. Рыскулова, Т. Даулетярова сельского округа Жолбарыс батыра
  kaz: Жолбарыс батыр ауылдық округі Кәлпе ауылының Т. Рысқұлов, Т. Даулетяров көшелерінде шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-11
approved_by:
- '154009005002'
version_date:
  kaz: 2018-12-11
  rus: 2018-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/126998/kaz/11.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126998/rus/11.12.2018
