act_code: '193788'
requisite: Решение акима Каратурыкского сельского округа Енбекшиказахского района Алматинской области от 28 февраля 2024 года № 1-06/8
title:
  rus: О переименовании улиц Каратурыкского сельского округа в селах Каратурык, Ащысай, Таукаратурык
  kaz: Қаратұрық ауылдық округінің Қаратұрық, Ащысай, Тауқаратұрық ауылдарындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-28
approved_by:
- '154012012002'
version_date:
  kaz: 2024-02-28
  rus: 2024-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/193788/kaz/28.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193788/rus/28.02.2024
