act_code: '119774'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 23 февраля 2018 года № 24-9. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2018 года № 4583. Утратило силу решением Енбекшиказахского районного маслихата Алматинской области от 13 октября 2023 года № VIII-8-41
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Енбекшиказахскому  району
  kaz: Еңбекшіқазақ ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-02-23
approved_by:
- '154012000002'
version_date:
  kaz: 2018-02-23
  rus: 2018-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/119774/kaz/23.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119774/rus/23.02.2018
