act_code: '119774'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 23 февраля 2018 года № 24-9. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2018 года № 4583. Утратило силу решением Енбекшиказахского районного маслихата Алматинской области от 13 октября 2023 года № VIII-8-41
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Енбекшиказахскому  району
  kaz: Еңбекшіқазақ ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-02-23
approved_by:
- '154012000002'
version_date:
  kaz: 2022-02-11
  rus: 2022-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/119774/kaz/11.02.2022
  rus: https://zan.gov.kz/client/#!/doc/119774/rus/11.02.2022
caused_by:
  code: '164742'
  requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 11 февраля 2022 года № 17-82. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 февраля 2022 года № 26874. Утратило силу решением Енбекшиказахского районного маслихата Алматинской области от 13 октября 2023 года № VIII-8-41
  title:
    rus: О внесении изменения в решение Енбекшиказахского районного маслихата от 23 февраля 2018 года № 24-9 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Енбекшиказахскому району»
    kaz: Еңбекшіқазақ аудандық мәслихатының 2018 жылғы 23 ақпандағы № 24-9 «Еңбекшіқазақ ауданының әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекiту туралы» шешiмiне өзгеріс енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/164742/rus
