act_code: '49675'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 30-1 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 05 қаңтарда № 2-19-86 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-7 шешімімен
title:
  rus: Ұйғыр ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Ұйғыр ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '154008000002'
version_date:
  kaz: 2010-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49675/kaz/22.06.2010
caused_by:
  code: '53387'
  requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 маусымдағы № 35-1 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 30 маусымда № 2-19-102 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-7 шешімімен
  title:
    rus: 2009 жылғы 21 желтоқсандағы "Ұйғыр ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 30-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылғы 21 желтоқсандағы "Ұйғыр ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 30-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53387/rus
