act_code: '50261'
requisite: Алматы облысы Іле аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 28-101 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 27 қаңтарда № 2-10-110 тіркелді. Күші жойылды - Алматы облысы Іле аудандық мәслихатының 2011 жылғы 18 мамырдағы № 47-197 шешімімен
title:
  rus: Салық төлеушілер үшін 2010 жылға арналған бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Салық төлеушілер үшін 2010 жылға арналған бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154017000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50261/kaz/23.12.2009
