act_code: '3466'
requisite: Решение акима Алматинской области от 14 января 1999 года № 1-9. Зарегистрировано Управлением юстиции Алматинской области 26 февраля 1999 года № 94. Утратило силу решением акима Алматинской области от 9 октября 1999 года № 9-282
title:
  rus: Об утверждении Порядка розничной торговли алькогольной продукцией с объемным содержанием этилового спирта более 12 процентов на территории Алматинской области
  kaz: Алматы облысы аумағында этил спиртінің кұлемдік құрамы 12 проценттен астам алкогольді өнімдерді б-лшек саудада сату тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-14
approved_by:
- '154000000003'
version_date:
  kaz: 1999-01-14
  rus: 1999-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/3466/kaz/14.01.1999
  rus: https://zan.gov.kz/client/#!/doc/3466/rus/14.01.1999
