act_code: '191734'
requisite: Решение Илийского районного маслихата Алматинской области от 29 декабря 2023 года № 18-50
title:
  rus: О бюджетах поселка Боралдай и сельских округов Илийского района на 2024-2026 годы
  kaz: Іле ауданының Боралдай кенті және ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '154017000002'
version_date:
  kaz: 2023-12-29
  rus: 2023-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/191734/kaz/29.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191734/rus/29.12.2023
