act_code: '53142'
requisite: Алматы облысы Алакөл ауданы Қызылащы ауылдық округі әкімінің 2010 жылғы 28 мамырдағы № 8 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 10 маусымда № 2-5-108 тіркелді
title:
  rus: Жұмахан Балапанов ауылындағы көше атауларын өзгерту туралы
  kaz: Жұмахан Балапанов ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-28
approved_by:
- '154003017002'
version_date:
  kaz: 2010-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/53142/kaz/28.05.2010
