act_code: '120759'
requisite: Решение Райымбекского районного маслихата Алматинской области от 15 марта 2018 года № 34-160. Зарегистрировано Департаментом юстиции Алматинской области 6 апреля 2018 года № 4629. Утратило силу решением Райымбекского районного маслихата Алматинской области от 14 ноября 2023 года № 13-73
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Райымбекского района
  kaz: Райымбек ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-03-15
approved_by:
- '154016000002'
version_date:
  kaz: 2019-03-27
  rus: 2019-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/120759/kaz/27.03.2019
  rus: https://zan.gov.kz/client/#!/doc/120759/rus/27.03.2019
caused_by:
  code: '130349'
  requisite: Решение Райымбекского районного маслихата Алматинской области от 27 марта 2019 года № 47-217. Зарегистрировано Департаментом юстиции Алматинской области 2 апреля 2019 года № 5091. Утратило силу решением Райымбекского районного маслихата Алматинской области от 14 ноября 2023 года № 13-73
  title:
    rus: О внесении изменений в решение Райымбекского районного маслихата от 15 марта 2018 года № 34-160 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Райымбекского района»
    kaz: Райымбек ауданы мәслихатының 2018 жылғы 15 наурыздағы Райымбек ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жеклеген санаттарының тізбесін айқындаудың қағидаларын бекіту № 34-160 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130349/rus
