act_code: '210334'
requisite: Решение Кегенского районного маслихата Алматинской области от 14 мая 2025 года № 34-157
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Кегенскому району на 2025-2026 годы
  kaz: Кеген ауданы бойынша 2025-2026 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-14
approved_by:
- '154021000002'
version_date:
  kaz: 2025-05-14
  rus: 2025-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/210334/kaz/14.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210334/rus/14.05.2025
