act_code: '124124'
requisite: Решение Каратальского районного маслихата Алматинской области от 23 июля 2018 года № 37-152. Зарегистрировано Департаментом юстиции Алматинской области 8 августа 2018 года № 4779
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Каратальского района
  kaz: Қаратал ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2018-07-23
approved_by:
- '154009000002'
version_date:
  kaz: 2018-07-23
  rus: 2018-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/124124/kaz/23.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124124/rus/23.07.2018
