act_code: '161170'
requisite: Решение Каратальского районного маслихата Алматинской области от 29 ноября 2021 года № 19-54. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 декабря 2021 года № 25543
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки населенных пунктов Каратальского района
  kaz: Қаратал ауданының жерлерін аймақтарға бөлу жобасын (схемасын), елді мекендердегі бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2021-11-29
approved_by:
- '154009000002'
version_date:
  kaz: 2021-11-29
  rus: 2021-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/161170/kaz/29.11.2021
  rus: https://zan.gov.kz/client/#!/doc/161170/rus/29.11.2021
