act_code: '78440'
requisite: Решение Балхашского районного маслихата Алматинской области от 11 марта 2014 года № 29-122. Зарегистрировано Департаментом юстиции Алматинской области 26 марта 2014 года № 2637
title:
  rus: Об утверждении Регламента Балхашского районного маслихата
  kaz: Балқаш аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-11
approved_by:
- '154014000002'
version_date:
  kaz: 2014-06-02
  rus: 2014-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/78440/kaz/02.06.2014
  rus: https://zan.gov.kz/client/#!/doc/78440/rus/02.06.2014
caused_by:
  code: '80793'
  requisite: Решение Балхашского районного маслихата Алматинской области от 02 июня 2014 года № 34-143. Зарегистрировано Департаментом юстиции Алматинской области 18 июня 2014 года № 2750
  title:
    rus: О внесении дополнений в решение Балхашского районного маслихата 11 марта 2014 года № 29-122 "Об утверждении Регламента Балхашского районного маслихата"
    kaz: Балқаш аудандық мәслихатының 2014 жылғы 11 наурыздағы "Балқаш аудандық мәслихатының Регламентін бекіту туралы" № 29-122 шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/80793/rus
