act_code: '89401'
requisite: Решение Талгарского районного маслихата Алматинской области от 31 марта 2015 года № 41-250. Зарегистрировано Департаментом юстиции Алматинской области 27 апреля 2015 года № 3150. Утратило силу решением Талгарского районного маслихата Алматинской области от 23 апреля 2020 года № 58-247
title:
  rus: Об установлении единовременной денежной компенсации на покрытие расходов за коммунальные услуги и на приобретение топлива для отопления жилых помещений педагогическим  работникам образования,  работаюшим в сельской местности
  kaz: Ауылдық жерде жұмыс істейтін білім берудің педагог қызметкерлеріне коммуналдық қызмет көрсетулерге шығыстарды жабуға және тұрғын үй-жайларды жылыту үшін отын  сатып алуға біржолғы ақшалай  өтемақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-31
approved_by:
- '154013000002'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/89401/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89401/rus/31.03.2015
