act_code: '52271'
requisite: Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2010 жылғы 14 сәуірдегі № 38-4 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 06 мамырда № 2-8-142 тіркелді. Күші жойылды - Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2012 жылғы 22 тамыздағы № 9-1 шешімімен
title:
  rus: Тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
  kaz: Тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '154012000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52271/kaz/14.04.2010
