act_code: '43436'
requisite: Алматы облысы Жамбыл аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 19-76 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2009 жылдың 8 қаңтарында № 2-7-68 тіркелді
title:
  rus: Жамбыл ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Жамбыл ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154018000002'
version_date:
  kaz: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43436/kaz/22.12.2008
