act_code: '192538'
requisite: Решение Жамбылского районного маслихата Алматинской области от 5 января 2024 года № 13-61
title:
  rus: О бюджетах сельских округов Жамбылского района на 2024-2026 годы
  kaz: Жамбыл ауданының ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-05
approved_by:
- '154018000002'
version_date:
  kaz: 2024-07-23
  rus: 2024-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/192538/kaz/23.07.2024
  rus: https://zan.gov.kz/client/#!/doc/192538/rus/23.07.2024
caused_by:
  code: '199415'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 23 июля 2024 года № 21-107
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 05 января 2024 года № 13-61 «О бюджетах сельских округов Жамбылского районана 2024-2026 годы»
    kaz: Жамбыл аудандық мәслихатының 2024 жылғы 05 қаңтардағы № 13-61 «Жамбыл ауданының ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199415/rus
