act_code: '206187'
requisite: Решение Балхашского районного маслихата Алматинской области от 30 декабря 2024 года № 32-123
title:
  rus: О решение Балхашского районного маслихата от 30 декабря 2024 года №32-123 «О бюджете Балхашского района на 2025-2027 годы»
  kaz: Балқаш аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 32-123 «Балқаш ауданының 2025-2027 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '154014000002'
version_date:
  kaz: 2025-10-24
  rus: 2025-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206187/kaz/24.10.2025
  rus: https://zan.gov.kz/client/#!/doc/206187/rus/24.10.2025
caused_by:
  code: '216303'
  requisite: Решение Балхашского районного маслихата Алматинской области от 24 октября 2025 года № 42-145
  title:
    rus: О внесении изменеий в решение Балхашского районного маслихата от 30 декабря 2024 года № 32-123 «О бюджете Балхашского района на 2025-2027 годы»
    kaz: Балқаш аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 32-123 «Балқаш ауданының 2025-2027 жылдарға арналған бюджетіне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/216303/rus
