act_code: '230320'
requisite: Решение акима Чунджинского сельского округа Уйгурского района Алматинской области от 4 августа 2026 года № 8-60
title:
  rus: О переименовании и присвоении наименования улицам в селе Шонжы Шонжынского сельского округа
  kaz: Шонжы ауылының көшелерін қайта атау және атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-04
approved_by:
- '154008014002'
version_date:
  kaz: 2026-08-04
  rus: 2026-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/230320/kaz/04.08.2026
  rus: https://zan.gov.kz/client/#!/doc/230320/rus/04.08.2026
