act_code: '62444'
requisite: Решение маслихата Талгарского района Алматинской области от 21 декабря 2011 года № 53-316. Зарегистрировано Управлением юстиции Талгарского района Департамента юстиции Алматинской области 28 декабря 2011 года № 2-18-136. Утратило силу решением маслихата Талгарского района Алматинской области от 13 мая 2013 года № 17-89
title:
  rus: О районном бюджете Талгарского района на 2012-2014 годы
  kaz: Талғар ауданының 2012-2014 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '154013000002'
version_date:
  kaz: 2012-09-06
  rus: 2012-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/62444/kaz/06.09.2012
  rus: https://zan.gov.kz/client/#!/doc/62444/rus/06.09.2012
caused_by:
  code: '67763'
  requisite: Решение маслихата Талгарского района Алматинской области от 06 сентября 2012 года № 8-46. Зарегистрировано Департаментом юстиции Алматинской области 19 сентября 2012 года № 2110. Утратило силу решением маслихата Талгарского района Алматинской области от 13 мая 2013 года № 17-89
  title:
    rus: О внесении изменений в решение от 21 декабря 2011 года N 53-316 "О районном бюджете Талгарского района на 2012-2014 годы"
    kaz: 2011 жылғы 21 желтоқсандағы "Талғар ауданының 2012-2014 жылдарға арналған аудандық бюджеті туралы" N 53-316 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67763/rus
