act_code: '216294'
requisite: Решение акима Жамбылского сельского округа Жамбылского района Алматинской области от 21 октября 2025 года № 10-78
title:
  rus: Жамбылский сельский округ О присвоении наименований улицам села Жамбыл
  kaz: Жамбыл ауылдық округі Жамбыл ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-21
approved_by:
- '154018008002'
version_date:
  kaz: 2025-10-21
  rus: 2025-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/216294/kaz/21.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216294/rus/21.10.2025
