act_code: '76107'
requisite: Решение маслихата Балхашского района Алматинской области от 05 декабря 2013 года № 26-108. Зарегистрировано Департаментом юстиции Алматинской области 13 декабря 2013 года № 2514. Утратило силу решением маслихата Балхашского района Алматинской области от 10 февраля 2014 года № 28-118
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Балхашского района
  kaz: Балқаш ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2013-12-05
approved_by:
- '154014000002'
version_date:
  kaz: 2013-12-05
  rus: 2013-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/76107/kaz/05.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76107/rus/05.12.2013
