act_code: '71132'
requisite: Решение акима Туздыбастауского сельского округа Талгарского района Алматинской области от 15 января 2013 года № 1, зарегистрировано Департаментом юстиции Алматинской области 19 февраля 2013 года № 2303
title:
  rus: О присвоении наименований новым улицам микрорайонов села Туздыбастау Туздыбастауского сельского округа
  kaz: Тұздыбастау ауылдық округі Тұздыбастау ауылының ықшам аудандарындағы жаңа көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-01-15
approved_by:
- '154013006001'
version_date:
  kaz: 2013-01-15
  rus: 2013-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/71132/kaz/15.01.2013
  rus: https://zan.gov.kz/client/#!/doc/71132/rus/15.01.2013
