act_code: '84876'
requisite: Решение акима Жандосовского сельского округа Карасайского района Алматинской области от 30 октября 2014 года № 10-54. Зарегистрировано Департаментом юстиции Алматинской области 2 декабря 2014 года № 2938
title:
  rus: О переименовании улицы Алатау села Жандосов и присвоении наименований новым улицам в селах Жандосов, Кайрат, Шалкар Жандосовского сельского округа
  kaz: Жандосов ауылдық округіндегі Жандосов, Шалқар, Қайрат ауылдарындағы жаңа көшелерге атау беру және Жандосов ауылының Алатау көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-30
approved_by:
- '154015002001'
version_date:
  kaz: 2014-10-30
  rus: 2014-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/84876/kaz/30.10.2014
  rus: https://zan.gov.kz/client/#!/doc/84876/rus/30.10.2014
