act_code: '90803'
requisite: Решение Карасайского районного маслихата Алматинской области от 27 мая 2015 года № 43-5. Зарегистрировано Департаментом юстиции Алматинской области 18 июня 2015 года № 3233. Утратило силу решением Карасайского районного маслихата Алматинской области от 18 января 2017 года № 11-3
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Карасайского района
  kaz: Қарасай ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-27
approved_by:
- '154015000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/90803/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90803/rus/27.05.2015
