act_code: '229493'
requisite: Решение маслихата города Алатау Алматинской области от 21 августа 2026 года № 34-92
title:
  rus: Об утверждении программы по управлению коммунальными отходами по городу Алатау на 2026-2030 годы
  kaz: Алатау қаласының 2026-2030 жылдарға арналған коммуналдық қалдықтарды басқару бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-21
approved_by:
- '154022000002'
version_date:
  kaz: 2026-08-21
  rus: 2026-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/229493/kaz/21.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229493/rus/21.08.2026
