act_code: '97221'
requisite: Решение Карасайского районного маслихата Алматинской области от 23 декабря 2015 года № 50-3. Зарегистрировано Департаментом юстиции Алматинской области 30 декабря 2015 года № 3657. Утратило силу решением Карасайского районного маслихата Алматинской области от 9 июня 2017 года № 14-6
title:
  rus: О бюджете Карасайского района на 2016-2018 годы
  kaz: Қарасай ауданының 2016-2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '154015000002'
version_date:
  kaz: 2016-03-24
  rus: 2016-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97221/kaz/24.03.2016
  rus: https://zan.gov.kz/client/#!/doc/97221/rus/24.03.2016
caused_by:
  code: '101070'
  requisite: Решение Карасайского районного маслихата Алматинской области от 24 марта 2016 года № 1-11. Зарегистрировано Департаментом юстиции Алматинской области 07 апреля 2016 года № 3779. Утратило силу решением Карасайского районного маслихата Алматинской области от 9 июня 2017 года № 14-6
  title:
    rus: О внесении изменений в решение Карасайского районного маслихата от 23 декабря 2015 года № 50-3 "О бюджете Карасайского района на 2016-2018 годы"
    kaz: Қарасай аудандық мәслихатының 2015 жылғы 23 желтоқсандағы "Қарасай ауданының 2016-2018 жылдарға арналған бюджеті туралы" № 50-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101070/rus
