act_code: '98785'
requisite: Решение Панфиловского районного маслихата Алматинской области от 01 февраля 2016 года № 5-60-398
title:
  rus: 'О признании утратившим силу решения Панфиловского районного маслихата от 28 сентября 2015 года №5-54-366 «О повышении ставок земельного налога и единого земельного налога на не исползуемые земли сельскохозяственного назначения по Панфиловскому району» '
  kaz: 'Панфилов аудандық мәслихатының 2015 жылғы 28 қыркүйектегі «Панфилов ауданы бойынша пайдаланылмайтын ауылшаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарлату туралы»  № 5-54-366 шешімінің күшін жою туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-01
approved_by:
- '154004000002'
version_date:
  kaz: 2016-02-01
  rus: 2016-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/98785/kaz/01.02.2016
  rus: https://zan.gov.kz/client/#!/doc/98785/rus/01.02.2016
