act_code: '40600'
requisite: Алматы облысы Еңбекшіқазақ ауданы Есік қаласы әкімінің 2008 жылғы 2 сәуірдегі № 106 шешімі. Алматы облысының Әділет департаменті Еңбешіқазақ ауданының әділет басқармасында 2008 жылы 7 мамырда № 2-8-76 тіркелді
title:
  rus: Есік қаласындағы "Жаңақұрылыс" аумағындағы жаңа көшеге "Самал" көшесі деп атау беру туралы
  kaz: Есік қаласындағы "Жаңақұрылыс" аумағындағы жаңа көшеге "Самал" көшесі деп атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-02
approved_by:
- '154012026002'
version_date:
  kaz: 2008-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/40600/kaz/02.04.2008
