act_code: '184196'
requisite: Решение акима Умтылского сельского округа Карасайского района Алматинской области от 27 июня 2023 года № 3. Зарегистрировано Департаментом юстиции Алматинской области 29 июня 2023 года № 6019-05
title:
  rus: О присвоении наименования парку в селе Алмалыбак Умтылского сельского округа
  kaz: Ұмтыл ауылдық округінің Алмалыбақ ауылындағы саябаққа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '154015017002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/184196/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/184196/rus/27.06.2023
