act_code: '77979'
requisite: Решение маслихата Балхашского района Алматинской области от 10 февраля 2014 года № 28-117. Зарегистрировано Департаментом юстиции Алматинской области 12 марта 2014 года № 2609. Утратило силу решением Балхашского районного маслихата Алматинской области от 02 июня 2014 года № 34-144
title:
  rus: Об утверждении  Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-10
approved_by:
- '154014000002'
version_date:
  kaz: 2014-02-10
  rus: 2014-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/77979/kaz/10.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77979/rus/10.02.2014
