act_code: '16565'
requisite: Решение маслихата Алматинской области от 15 июля 2003 года № 35-207. Зарегистрировано Управлением юстиции Алматинской области 1 августа 2003 года № 1263. Утратило силу решением маслихата Алматинской области от 17 января 2007 года № 35-267
title:
  rus: О региональной программе капитального ремонта ветхого жилья и сносу аварийных жилых домов по Алматинской области на 2004-2006 годы
  kaz: Алматы облысы бойынша 2004-2006 жылдарға арналған тозығы жеткен тұрғын үйлерді күрделі жөндеуден өткізу және құлағалы тұрған тұрғын үйлерді бұзұ жөніндегі өңірлік бағдарлама туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-07-14
approved_by:
- '154000000002'
version_date:
  kaz: 2003-07-14
  rus: 2003-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/16565/kaz/14.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16565/rus/14.07.2003
