act_code: '39658'
requisite: Алматы облысы мәслихатының 2008 жылғы 10 сәуірдегі № 8-57 шешімі. Алматы облысының Әділет департаментінде 2008 жылғы 20 мамырда № 2008 тіркелген. Күші жойылды - Алматы облыстық мәслихатының 2008 жылғы 29 желтоқсандағы № 16-105 шешімімен
title:
  rus: Жергілікті маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінде және Алматы облысының елді мекендерде орналастырылатын жарнама объектілері бойынша сыртқы (көрнекі) жарнаманы орналастырғаны үшін төлем ставкаларын белгілеу туралы
  kaz: Жергілікті маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінде және Алматы облысының елді мекендерде орналастырылатын жарнама объектілері бойынша сыртқы (көрнекі) жарнаманы орналастырғаны үшін төлем ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-10
approved_by:
- '154000000002'
version_date:
  kaz: 2008-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/39658/kaz/10.04.2008
