act_code: '5201'
requisite: Решение акима Алматинской области от 13 декабря 1999 года № 12-385. Зарегистрировано Управлением юстиции Алматинской области 17 января 2000 года № 136. Утратило силу решением акима Алматинской области от 30 января 2004 года № 1-14
title:
  rus: О нормативах (ставках) платежей за загрязнение окружающей среды на 2000 год
  kaz: Қоршаған ортаны ластағаны үшін алынатын төлемақының 2000 жылға арналған нормативтері (ставкалары) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-13
approved_by:
- '154000000003'
version_date:
  kaz: 1999-12-13
  rus: 1999-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/5201/kaz/13.12.1999
  rus: https://zan.gov.kz/client/#!/doc/5201/rus/13.12.1999
