act_code: '46656'
requisite: Алматы облысы Іле ауданы Чапаев ауылы әкімінің 2009 жылғы 21 мамырдағы № 2 шешімі. Алматы облысының Әділет департаменті Іле ауданының Әділет басқармасында 2009 жылдың 19 маусымында № 2-10-95 тіркелді
title:
  rus: Чапаев ауылындағы Ленин көшесінің атын өзгерту туралы
  kaz: Чапаев ауылындағы Ленин көшесінің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-21
approved_by:
- '154017010002'
version_date:
  kaz: 2009-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/46656/kaz/21.05.2009
