act_code: '47925'
requisite: Алматы облысы Сарқан аудандық мәслихатының 2009 жылғы 6 тамыздағы N 25-145 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының Әділет басқармасында 2009 жылы 9 қыркүйекте N 2-17-76 тіркелді. Күші жойылды - Алматы облысы Сарқан аудандық мәслихатының 2012 жылғы 25 маусымдағы N 7-52 шешімімен
title:
  rus: '"Сарқан ауданының Құрметті азаматы" атағын беру ережесін бекіту туралы'
  kaz: '"Сарқан ауданының Құрметті азаматы" атағын беру ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-06
approved_by:
- '154005000002'
version_date:
  kaz: 2009-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/47925/kaz/06.08.2009
