act_code: '85847'
requisite: Решение Кербулакского районного маслихата Алматинской области от 19 декабря 2014 года № 39-232. Зарегистрировано Департаментом юстиции Алматинской области 13 января 2015 года № 2995. Утратило силу решением Кербулакского районного маслихата Алматинской области от 26 арпеля 2016 года № 03-23
title:
  rus: Об утверждении Положения   государственного  учреждения «Аппарат Кербулакского районного маслихата»
  kaz: «Кербұлақ аудандық мәслихатының  аппараты» мемлекеттік мекемесінің   Ережесін  бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154010000002'
version_date:
  kaz: 2014-12-19
  rus: 2014-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85847/kaz/19.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85847/rus/19.12.2014
