act_code: '53815'
requisite: Алматы облысы Ақсу ауданы Арасан ауылдық округі әкімінің 2010 жылғы 02 шілдедегі № 5 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 03 тамызда № 2-4-117 тіркелді
title:
  rus: Арасан ауылдық округіндегі Қызылжар ауылындағы атауы жоқ көшені Қызылжар көшесі атауын беру туралы
  kaz: Арасан ауылдық округіндегі Қызылжар ауылындағы атауы жоқ көшені Қызылжар көшесі атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-02
approved_by:
- '154011002002'
version_date:
  kaz: 2010-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/53815/kaz/02.07.2010
