act_code: '78195'
requisite: Решение Талгарского районного маслихата Алматинской области от 25 февраля 2014 года N 28-155. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2014 года N 2621. Утратило силу решением Талгарского районного маслихата Алматинской области от 10 июня 2016 года № 5-25
title:
  rus: Об утверждении регламента Талгарского районного маслихата
  kaz: Талғар аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-25
approved_by:
- '154013000002'
version_date:
  kaz: 2014-05-06
  rus: 2014-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/78195/kaz/06.05.2014
  rus: https://zan.gov.kz/client/#!/doc/78195/rus/06.05.2014
caused_by:
  code: '80267'
  requisite: Решение Талгарского районного маслихата Алматинской области от 06 мая 2014 года № 32-176. Зарегистрировано Департаментом юстиции Алматинской области 20 мая 2014 года № 2726.  Утратило силу решением Талгарского районного маслихата Алматинской области от 10 июня 2016 года № 5-25
  title:
    rus: О внесении дополнений в решение Талгарского районного маслихата от 25 февраля 2014 года № 28-155 "Об утверждении регламента Талгарского районного маслихата"
    kaz: Талғар аудандық мәслихатының 2014 жылғы 25 ақпандағы "Талғар аудандық мәслихатының регламентін бекіту туралы" № 28-155 шешіміне толықтырулар  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/80267/rus
