act_code: '18674'
requisite: Решение Алматинского областного маслихата от 25 декабря 2003 года № 3-132. Зарегистрировано Управлением юстиции Алматинской области 6 февраля 2004 года № 1489
title:
  rus: Об индикативном плане социально-экономического развития Алматинской области на 2004-2006 годы
  kaz: Алматы облысының әлеуметтік-экономикалық дамуының 2004-2006 жылдарға арналған индикативтік жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-25
approved_by:
- '154000000002'
version_date:
  kaz: 2003-12-25
  rus: 2003-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/18674/kaz/25.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18674/rus/25.12.2003
