act_code: '152265'
requisite: Решение Жамбылского районного маслихата Алматинской области от 11 января 2021 года № 82-366. Зарегистрировано Департаментом юстиции Алматинской области 19 января 2021 года № 5869
title:
  rus: О бюджетах сельских округов Жамбылского района на 2021-2023 годы
  kaz: Жамбыл ауданының ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-11
approved_by:
- '154018000002'
version_date:
  kaz: 2021-09-06
  rus: 2021-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/152265/kaz/06.09.2021
  rus: https://zan.gov.kz/client/#!/doc/152265/rus/06.09.2021
caused_by:
  code: '158465'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 6 сентября 2021 года № 10-55
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 11 января 2021 года № 82-366 «О бюджетах сельских округов Жамбылского района на 2021-2023 годы»
    kaz: Жамбыл аудандық мәслихатының 2021 жылғы 11 қаңтардағы № 82-366 «Жамбыл ауданының ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158465/rus
