act_code: '55452'
requisite: Алматы облысы Алакөл ауданы Қамысқала ауылдық округі әкімінің 2010 жылғы 13 қазандағы № 9 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 17 қарашада № 2-5-132 тіркелді
title:
  rus: Қамысқала ауылдық округіне қарасты Алакөл және Ұялы ауылдарындағы атаусыз көшелерге ат қою туралы
  kaz: Қамысқала ауылдық округіне қарасты Алакөл және Ұялы ауылдарындағы атаусыз көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-13
approved_by:
- '154003016002'
version_date:
  kaz: 2010-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/55452/kaz/13.10.2010
