act_code: '87188'
requisite: ''
title:
  rus: 'Об установлении повышенных  на двадцать пять процентов окладов  и тарифных ставок специалистам  являющимся гражданскими  служащими и работающим в сельских  населенных пунктах Уйгурского района '
  kaz: 'Ұйғыр ауданының азаматтық  қызметші болып табылатын және  ауылдық елді мекендерде жұмыс  істейтін мамандарына жиырма бес пайызға жоғарылатылған айлықақылар  мен тарифтік ставкалар белгілеу туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-09
approved_by:
- '154008000002'
version_date:
  kaz: 2015-02-09
  rus: 2015-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/87188/kaz/09.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87188/rus/09.02.2015
