act_code: '187139'
requisite: Решение Уйгурского районного маслихата Алматинской области от 11 октября 2023 года № 8-10-52. Зарегистрировано Департаментом юстиции Алматинской области 12 октября 2023 года № 6041-05
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Уйгурского района
  kaz: Ұйғыр ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-11
approved_by:
- '154008000002'
version_date:
  kaz: 2024-12-26
  rus: 2024-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/187139/kaz/26.12.2024
  rus: https://zan.gov.kz/client/#!/doc/187139/rus/26.12.2024
caused_by:
  code: '205056'
  requisite: Решение Уйгурского районного маслихата Алматинской области от 26 декабря 2024 года № 8-34-174. Зарегистрировано Департаментом юстиции Алматинской области 27 декабря 2024 года № 6198-05
  title:
    rus: О внесении изменений и дополнений в решение Уйгурского районного маслихата от 11 октября 2023 года № 8-10-52 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Уйгурского района»
    kaz: Ұйғыр аудандық мәслихатының 2023 жылғы 11 қазандағы «Ұйғыр ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» № 8-10-52 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/205056/rus
