act_code: '187139'
requisite: Решение Уйгурского районного маслихата Алматинской области от 11 октября 2023 года № 8-10-52. Зарегистрировано Департаментом юстиции Алматинской области 12 октября 2023 года № 6041-05
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Уйгурского района
  kaz: Ұйғыр ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-11
approved_by:
- '154008000002'
version_date:
  kaz: 2023-10-11
  rus: 2023-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/187139/kaz/11.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187139/rus/11.10.2023
