act_code: '179857'
requisite: Решение акима КазЦИКовского сельского округа Илийского района Алматинской области от 14 апреля 2023 года № 222. Зарегистрировано Департаментом юстиции Алматинской области 17 апреля 2023 года № 5980-05
title:
  rus: О переименовании улиц села КазЦИК КазЦИКовского сельского округа
  kaz: КазЦИК ауылдық округі КазЦИК ауылы көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-14
approved_by:
- '154017004002'
version_date:
  kaz: 2023-04-14
  rus: 2023-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/179857/kaz/14.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179857/rus/14.04.2023
