act_code: '49783'
requisite: Алматы облысы Ақсу ауданы Матай поселкелік округі әкімінің 2009 жылғы 28 желтоқсандағы № 2 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2010 жылы 13 қаңтарда № 2-4-102 тіркелді
title:
  rus: Матай ауылында Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 көше атауларын Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4 көше атауларына өзгерту туралы
  kaz: Матай ауылында Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 көше атауларын Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4 көше атауларына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '154011014002'
version_date:
  kaz: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49783/kaz/26.12.2014
caused_by:
  code: '86603'
  requisite: Решение акима Матайского сельского округа Аксуского района Алматинской области от 26 декабря 2014 года № 2. Зарегистрировано Департаментом юстиции Алматинской области 06 февраля 2015 года № 3025
  title:
    rus: О внесении изменений в решение акима Матайского поселкового округа от 28 декабря 2009 года № 2 «Об изменении названии улиц Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 в поселке Матай на названии улиц Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4»
    kaz: Матай поселкелік округі әкімінің 2009 жылғы 28 желтоқсандағы «Матай поселкесінде Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 көше атауларын Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4 көше атауларына өзгерту туралы» № 2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86603/rus
