act_code: '49783'
requisite: Алматы облысы Ақсу ауданы Матай поселкелік округі әкімінің 2009 жылғы 28 желтоқсандағы № 2 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2010 жылы 13 қаңтарда № 2-4-102 тіркелді
title:
  rus: Матай ауылында Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 көше атауларын Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4 көше атауларына өзгерту туралы
  kaz: Матай ауылында Западный поселок квартал 1, Западный поселок квартал 2, Западный поселок квартал 3, Западный поселок квартал 4 көше атауларын Батыс орамы 1, Батыс орамы 2, Батыс орамы 3, Батыс орамы 4 көше атауларына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '154011014002'
version_date:
  kaz: 2009-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/49783/kaz/28.12.2009
