act_code: '119753'
requisite: Решение Жамбылского районного маслихата Алматинской области от 5 марта 2018 года № 29-155. Зарегистрировано Департаментом юстиции Алматинской области 19 марта 2018 года № 4576. Утратило силу решением Жамбылского районного маслихата Алматинской области от 28 сентября 2023 года № 7-32
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Жамбылского района
  kaz: Жамбыл ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-03-05
approved_by:
- '154018000002'
version_date:
  kaz: 2020-04-29
  rus: 2020-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/119753/kaz/29.04.2020
  rus: https://zan.gov.kz/client/#!/doc/119753/rus/29.04.2020
caused_by:
  code: '142740'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 29 апреля 2020 года № 70-326. Зарегистрировано Департаментом юстиции Алматинской области 13 мая 2020 года № 5521. Утратило силу решением Жамбылского районного маслихата Алматинской области от 28 сентября 2023 года № 7-32
  title:
    rus: О внесении изменений и дополнения в решение Жамбылского районного маслихата от 5 марта 2018 года № 29-155 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Жамбылского района»
    kaz: Жамбыл аудандық мәслихатының 2018 жылғы 5 наурыздағы № 29-155 «Жамбыл ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142740/rus
