act_code: '48142'
requisite: Алматы облысы Қаратал ауданы Қызылбалық ауылдық округі әкімінің 2009 жылғы 23 қыркүйектегі № 2 шешімі. Алматы облысының әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 13 қазанда № 2-12-128 тіркелді
title:
  rus: Қарақұм ауылының көшелеріне атау беру туралы
  kaz: Қарақұм ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-23
approved_by:
- '154009006002'
version_date:
  kaz: 2009-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/48142/kaz/23.09.2009
