act_code: '118381'
requisite: Решение Жамбылского районного маслихата Алматинской области от 20 декабря 2017 года № 26-141. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2017 года № 4457
title:
  rus: О бюджете Жамбылского района на 2018-2020 года
  kaz: Жамбыл ауданының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '154018000002'
version_date:
  kaz: 2018-08-07
  rus: 2018-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/118381/kaz/07.08.2018
  rus: https://zan.gov.kz/client/#!/doc/118381/rus/07.08.2018
caused_by:
  code: '124376'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 7 августа 2018 года № 42-201. Зарегистрировано Департаментом юстиции Алматинской области 29 августа 2018 года № 4807
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 20 декабря 2017 года № 26-141 «О бюджете Жамбылского района на 2018-2020 года»
    kaz: Жамбыл аудандық мәслихатының 2017 жылғы 20 желтоқсандағы «Жамбыл ауданының 2018-2020 жылдарға арналған бюджеті туралы» № 26-141 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124376/rus
