act_code: '163936'
requisite: Решение Илийского районного маслихата Алматинской области от 30 декабря 2021 года № 15-52
title:
  rus: О бюджетах поселка Боралдай и сельских округов Илийского района на 2022-2024 годы
  kaz: Іле ауданының Боралдай кенті және ауылдық округтерінің 2022-2024 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '154017000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/163936/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163936/rus/15.12.2022
caused_by:
  code: '175547'
  requisite: Решение Илийского районного маслихата Алматинской области от 15 декабря 2022 года № 30-103
  title:
    rus: О внесении изменений в решение Илийского районного маслихата от 30 декабря 2021 года № 15-52 «О бюджетах поселка Боралдай и сельских округов Илийского района на 2022-2024 годы»
    kaz: Іле аудандық мәслихатының 2021 жылғы 30 желтоқсандағы «Іле ауданының Боралдай кенті және ауылдық округтерінің 2022-2024 жылдарға арналған бюджеттері туралы» № 15-52 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175547/rus
