act_code: '118354'
requisite: Решение Панфиловского районного маслихата Алматинской области от 22 декабря 2017 года № 6-27-173. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2017 года № 4454
title:
  rus: О бюджете Панфиловского района на 2018-2020 годы
  kaz: Панфилов ауданының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '154004000002'
version_date:
  kaz: 2018-02-23
  rus: 2018-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/118354/kaz/23.02.2018
  rus: https://zan.gov.kz/client/#!/doc/118354/rus/23.02.2018
caused_by:
  code: '119662'
  requisite: Решение Панфиловского районного маслихата Алматинской области от 23 февраля 2018 года № 6-30-194. Зарегистрировано Департаментом юстиции Алматинской области 13 марта 2018 года № 4547
  title:
    rus: О внесении изменений в решение Панфиловского районного маслихата от 22 декабря 2017 года № 6-27-173 «О бюджете Панфиловского района на 2018-2020 годы»
    kaz: Панфилов аудандық мәслихатының 2017 жылғы 22 желтоқсандағы «Панфилов ауданының 2018-2020 жылдарға арналған бюджеті туралы» № 6-27-173 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119662/rus
