act_code: '41981'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2008 жылғы 15 қазандағы № 11-3 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2008 жылғы 24 қазанда № 2-5-65 тіркелген
title:
  rus: «Өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы Қағиданы бекіту туралы
  kaz: «Өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы Қағиданы бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-15
approved_by:
- '154003000002'
version_date:
  kaz: 2008-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/41981/kaz/15.10.2008
