act_code: '51560'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 26 ақпандағы № 31-189 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 06 сәуірде № 2-4-108 тіркелді. Күші жойылды - Алматы облысы Ақсу ауданы мәслихатының 2012 жылғы 06 қыркүйектегі № 7-62 шешімімен
title:
  rus: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің тәртібі мен мөлшерінің қағидасы туралы
  kaz: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің тәртібі мен мөлшерінің қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-26
approved_by:
- '154011000002'
version_date:
  kaz: 2010-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/51560/kaz/26.02.2010
