act_code: '20090'
requisite: Решение Алматинского областного маслихата от 13 апреля 2004 года № 5-40. Зарегистрировано Департаментом юстиции Алматинской области 27 мая 2004 года № 1646. Утратило силу решением маслихата Алматинской области от 27 декабря 2010 года № 40-230
title:
  rus: Об утверждении регламента Алматинского областного Маслихата
  kaz: Алматы облыстық мәслихатының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-04-12
approved_by:
- '154000000002'
version_date:
  kaz: 2006-10-04
  rus: 2006-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/20090/kaz/04.10.2006
  rus: https://zan.gov.kz/client/#!/doc/20090/rus/04.10.2006
caused_by:
  code: '30304'
  requisite: Решение маслихата Алматинской области от 4 октября 2006 года № 31-245. Зарегистрировано Департаментом юстиции Алматинской области от 13 ноября 2006 года № 1972. Утратило силу решением маслихата Алматинской области от 27 декабря 2010 года № 40-230
  title:
    rus: О внесении изменений в решение Алматинского областного маслихата N 5-40 от 13 апреля 2004 года "Об утверждении Регламента Алматинского областного маслихата"
    kaz: 2004 жылғы 13 сәуірдегі "Алматы облыстық мәслихатының регламентін бекіту туралы" 5-40 нөмірлі шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/30304/rus
