act_code: '20090'
requisite: Решение Алматинского областного маслихата от 13 апреля 2004 года № 5-40. Зарегистрировано Департаментом юстиции Алматинской области 27 мая 2004 года № 1646. Утратило силу решением маслихата Алматинской области от 27 декабря 2010 года № 40-230
title:
  rus: Об утверждении регламента Алматинского областного Маслихата
  kaz: Алматы облыстық мәслихатының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-04-12
approved_by:
- '154000000002'
version_date:
  kaz: 2004-04-12
  rus: 2004-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/20090/kaz/12.04.2004
  rus: https://zan.gov.kz/client/#!/doc/20090/rus/12.04.2004
