act_code: '21393'
requisite: Алматы облыстық Мәслихатының 2004 жылғы 6 қыркүйектегі № 9-63 шешімі. Алматы облыстық әділет департаментінде 2004 жылы 23 қыркүйекте № 1756 тіркелген
title:
  rus: Алматы облыстық Әділет басқармасында 2004 жылғы 9 қаңтарда 1434 нөмiрiмен тiркелген Алматы облыстық Мәслихатының 2003 жылғы 25 желтоқсандағы "Алматы облысының 2004 жылға арналған облыстық бюджетi туралы" N 3-12 шешiмiне өзгерiстер енгiзу туралы
  kaz: Алматы облыстық Әділет басқармасында 2004 жылғы 9 қаңтарда 1434 нөмiрiмен тiркелген Алматы облыстық Мәслихатының 2003 жылғы 25 желтоқсандағы "Алматы облысының 2004 жылға арналған облыстық бюджетi туралы" N 3-12 шешiмiне өзгерiстер енгiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-05
approved_by:
- '154000000002'
version_date:
  kaz: 2004-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/21393/kaz/05.09.2004
