act_code: '139141'
requisite: Решение Аксуского районного маслихата Алматинской области от 9 января 2020 года № 56-254. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2020 года № 5408
title:
  rus: О бюджетах сельских округов Аксуского района на 2020-2022 годы
  kaz: Ақсу ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154011000002'
version_date:
  kaz: 2020-01-09
  rus: 2020-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/139141/kaz/09.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139141/rus/09.01.2020
