act_code: '7036'
requisite: Решение акима Алматинской области от 3 марта 2000 года № 3-63. Зарегистрировано Управлением юстиции Алматинской области от 11 августа 2000 года № 180. Утратило силу решением акима Алматинской области от 30 июля 2004 года № 7-82
title:
  rus: О финансово-кредитной поддержке субъектов малого и среднего бизнеса, а также оптово-торговой заготовительной компании
  kaz: Шағын және орта бизнес субъектілерін, сондай-ақ көтерме сауда-дайындау компаниясын қаржы-несиелік қолдау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-03
approved_by:
- '154000000003'
version_date:
  kaz: 2000-03-03
  rus: 2000-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/7036/kaz/03.03.2000
  rus: https://zan.gov.kz/client/#!/doc/7036/rus/03.03.2000
