act_code: '56481'
requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 36-276 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының Әділет басқармасында 2010 жылы 31 желтоқсанда № 2-13-131 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2011 жылғы 20 желтоқсандағы № 48-360 шешімімен
title:
  rus: Кербұлақ ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Кербұлақ ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '154010000002'
version_date:
  kaz: 2011-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56481/kaz/18.07.2011
caused_by:
  code: '59811'
  requisite: Решение маслихата Кербулакского районного маслихата Алматинской области от 18 июля 2011 года № 42-321. Зарегистрировано Управлением юстиции Кербулакского района Департамента юстиции Алматинской области 27 июля 2011 года № 2-13-140. Утратило силу - Решением маслихата Кербулакского района Алматинской области от 20 декабря 2011 года № 48-360
  title:
    rus: О внесении изменений в решение Кербулакского районного маслихата от 24 декабря 2010 года N 36-276 "О бюджете Кербулакского района на 2011-2013 годы"
    kaz: Кербұлақ аудандық мәслихатының 2010 жылғы 24 желтоқсандағы "Кербұлақ ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" N 36-276 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59811/rus
