act_code: '128643'
requisite: Решение Уйгурского районного маслихата Алматинской области от 28 декабря 2018 года № 6-42-253. Зарегистрировано Департаментом юстиции Алматинской области 16 января 2019 года № 5005
title:
  rus: О бюджете Уйгурского района на 2019-2021 годы
  kaz: Ұйғыр ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '154008000002'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128643/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128643/rus/28.12.2018
