act_code: '50305'
requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 26-185 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының әділет басқармасында 2010 жылы 28 қаңтарда 2-13-104 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2010 жылғы 30 сәуірдегі № 29-218 шешімімен
title:
  rus: Елді мекендердің жерлеріне салынатын базалық салық ставкаларын жоғарылату туралы
  kaz: Елді мекендердің жерлеріне салынатын базалық салық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154010000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50305/kaz/23.12.2009
