act_code: '56428'
requisite: Алматы облысы Жамбыл ауданы мәслихатының 2010 жылғы 23 желтоқсандағы № 46-212 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 31 желтоқсанда № 2-7-113 тіркелді. Күші жойылды - Алматы облысы Жамбыл аудандық мәслихатының 2012 жылғы 26 наурыздағы № 4-47 шешімімен
title:
  rus: Жамбыл ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Жамбыл ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '154018000002'
version_date:
  kaz: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56428/kaz/23.12.2010
