act_code: '30872'
requisite: Алматы облыстық мәслихатының 2006 жылғы 12 желтоқсандағы № 34-250 шешімі. Алматы облыстық Әділет департаментінде 2006 жылғы 26 желтоқсанда № 1976 тіркелген. Күші жойылды - Алматы облыстық мәслихатының 2008 жылғы 29 желтоқсандағы № 16-105 шешімімен
title:
  rus: Алматы облысының 2007 жылға арналған облыстық бюджеті туралы
  kaz: Алматы облысының 2007 жылға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '154000000002'
version_date:
  kaz: 2007-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/30872/kaz/26.11.2007
caused_by:
  code: '36029'
  requisite: Алматы облыстық мәслихатының 2007 жылғы 26 қарашадағы № 4-23 шешімі. Алматы облыстық Әділет департаментінде 2007 жылғы 6 желтоқсанда № 1997 тіркелген. Күші жойылды - Алматы облыстық мәслихатының 2008 жылғы 29 желтоқсандағы № 16-105 шешімімен
  title:
    rus: Алматы облыстық мәслихатының 2006 жылғы 12 желтоқсандағы "Алматы облысының 2007 жылға арналған облыстық бюджеті туралы" N 34-250 шешіміне өзгерістер енгізу туралы
    kaz: Алматы облыстық мәслихатының 2006 жылғы 12 желтоқсандағы "Алматы облысының 2007 жылға арналған облыстық бюджеті туралы" N 34-250 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/36029/rus
