act_code: '43244'
requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 15-107 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының әділет басқармасында 2009 жылы 6 қаңтарда № 2-13-83 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 26-188 шешімімен
title:
  rus: Кербұлақ ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Кербұлақ ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154010000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43244/kaz/22.04.2009
caused_by:
  code: '45465'
  requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 22 сәуірдегі N 20-140 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының әділет басқармаснда 2009 жылы 23 сәуірде N 2-13-93 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 26-188 шешімімен
  title:
    rus: Кербұлақ аудандық мәслихатының 2008 жылғы 22 желтоқсанындағы "Кербұлақ ауданының 2009 жылға арналған аудандық бюджеті туралы" N 15-107 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Кербұлақ аудандық мәслихатының 2008 жылғы 22 желтоқсанындағы "Кербұлақ ауданының 2009 жылға арналған аудандық бюджеті туралы" N 15-107 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45465/rus
