act_code: '220408'
requisite: Решение Балхашского районного маслихата Алматинской области от 25 декабря 2025 года № 46-155
title:
  rus: О решение Балхашского районного маслихата от 25 декабря 2025 года № 46-155 «О бюджете Балхашского района на 2026-2028 годы»
  kaz: Балқаш аудандық мәслихатының 2025 жылғы 25 желтоқсандағы № 46-155 «Балқаш ауданының 2026-2028 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-25
approved_by:
- '154014000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/220408/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/220408/rus/31.03.2026
caused_by:
  code: '223911'
  requisite: Решение Балхашского районного маслихата Алматинской области от 31 марта 2026 года № 48-158
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 25 декабря 2025 года № 46-155 «О районном бюджете Балхашского района на 2026-2028 годы»
    kaz: Балқаш аудандық мәслихатының 2025 жылғы 25 желтоқсандағы № 46-155 «Балқаш ауданының 2026-2028 жылдарға арналған бюджетіне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/223911/rus
