act_code: '199090'
requisite: Решение маслихата города Алатау Алматинской области от 19 июля 2024 года № 6-15
title:
  rus: Об утверждении Положения о территориальном совете местного самоуправления города Алатау Алматинской области
  kaz: Алматы облысы Алатау қаласының жергілікті өзін-өзі басқару аумақтық кеңесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-19
approved_by:
- '154022000002'
version_date:
  kaz: 2024-07-19
  rus: 2024-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/199090/kaz/19.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199090/rus/19.07.2024
