act_code: '72625'
requisite: Решение акима Каракозского сельского округа Аксуского района Алматинской области от 19 апреля 2013 года № 1. Зарегистрировано Департаментом юстиции Алматинской области 13 мая 2013 года № 2352. Утратило силу решением акима Каракозского сельского округа Аксуского района Алматинской области от 16 октября 2013 года № 2
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізе отырып, карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-19
approved_by:
- '154011008001'
version_date:
  rus: 2013-10-16
source:
  rus: https://zan.gov.kz/client/#!/doc/72625/rus/16.10.2013
