act_code: '110820'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 3 марта 2017 года № 12-71. Зарегистрировано Департаментом юстиции Алматинской области 3 апреля 2017 года № 4167. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 13 марта 2018 года № 27-179
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Ескельдинского районного маслихата
  kaz: Ескелді аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2017-03-03
approved_by:
- '154006000002'
version_date:
  kaz: 2017-03-03
  rus: 2017-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/110820/kaz/03.03.2017
  rus: https://zan.gov.kz/client/#!/doc/110820/rus/03.03.2017
