act_code: '46408'
requisite: Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 7 мамырдағы № 24-99 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 10 маусымда № 2-12-108 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 15 қазандағы № 28-128 шешімімен
title:
  rus: 2009 жылға жер салығының базалық ставкаларын жоғарылату туралы
  kaz: 2009 жылға жер салығының базалық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-07
approved_by:
- '154009000002'
version_date:
  kaz: 2009-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/46408/kaz/07.05.2009
