act_code: '116291'
requisite: Решение акима Жайпакского сельского округа Алакольского района Алматинской области от 15 ноября 2017 года № 10. Зарегистрировано Департаментом юстиции Алматинской области 23 ноября 2017 года № 4395. Утратило силу решением акима Жайпакского сельского округа Алакольского района Алматинской области от 8 февраля 2018 года № 2
title:
  rus: Об установлении ограничительных мероприятий на территории Жайпакского сельского округа
  kaz: Жайпақ ауылдық округінің аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-15
approved_by:
- '154003011002'
version_date:
  kaz: 2017-11-15
  rus: 2017-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/116291/kaz/15.11.2017
  rus: https://zan.gov.kz/client/#!/doc/116291/rus/15.11.2017
