act_code: '62033'
requisite: Решение маслихата Алматинской области от 07 декабря 2011 года № 53-296. Зарегистрировано Департаментом юстиции Алматинской области 13 декабря 2011 года № 2081
title:
  rus: Об областном бюджете Алматинской области на 2012-2014 годы
  kaz: Алматы облысының 2012-2014 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-07
approved_by:
- '154000000002'
version_date:
  kaz: 2011-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/62033/kaz/07.12.2011
