act_code: '21758'
requisite: Алматы облыстық әкімінің 2004 жылғы 20 қыркүйектегі № 9-91 шешімі. Алматы облыстық әділет департаментінде 2004 жылғы 15 қазанда № 1778 тіркелген
title:
  rus: Әскер жасына дейінгі жастарды 2004 жылғы кезекті дәрігерлік тексеруден өткізу туралы
  kaz: Әскер жасына дейінгі жастарды 2004 жылғы кезекті дәрігерлік тексеруден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-19
approved_by:
- '154000000003'
version_date:
  kaz: 2004-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/21758/kaz/19.09.2004
