act_code: '37665'
requisite: Алматы облысы Көксу аудандық мәслихатының 2008 жылғы 04 ақпандағы № 9-1 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2008 жылы 12 ақпанда № 2-14-53 тіркелді. Күші жойылды - Алматы облысы Көксу аудандық мәслихатының 2009 жылғы 24 маусымдағы № 27-1 шешімімен
title:
  rus: Тұрмысы төмен отбасыларына тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
  kaz: Тұрмысы төмен отбасыларына тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-04
approved_by:
- '154007000002'
version_date:
  kaz: 2008-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/37665/kaz/04.02.2008
