act_code: '19876'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 16 апреля 2004 года N 10-5. Зарегистрировано Департаментом юстиции Алматинской области 19 мая 2004 года за N 1624. Утратило силу - решением Ескельдинского районного маслихата Алматинской области от 21 февраля 2011 года N 50-304
title:
  rus: О регламенте районного маслихата
  kaz: Аудандық мәслихаттың регламентi туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-04-15
approved_by:
- '154006000002'
version_date:
  rus: 2004-04-15
source:
  rus: https://zan.gov.kz/client/#!/doc/19876/rus/15.04.2004
