act_code: '69182'
requisite: Решение маслихата Уйгурского района Алматинской области от 05 декабря 2012 года № 12-3. Зарегистрировано Департаментом юстиции Алматинской области 13 декабря 2012 года № 2243. Утратило силу решением Уйгурского районного маслихата Алматинской области от 24 ноября 2014 года № 41-3
title:
  rus: Об установлении специалистам здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, работающих в сельских населенных пунктах Уйгурского района повышенные на двадцать пять процентов оклады и тарифные ставки
  kaz: Ұйғыр ауданының ауылдық елді мекендерінде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария мамандарына жиырма бес проценті жоғары айлықақы мен тарифтік ставкалар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-05
approved_by:
- '154008000002'
version_date:
  kaz: 2012-12-05
  rus: 2012-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/69182/kaz/05.12.2012
  rus: https://zan.gov.kz/client/#!/doc/69182/rus/05.12.2012
