act_code: '40902'
requisite: Алматы облысы Ескелді ауданы Сырымбет ауылдық округі әкімінің 2008 жылғы 30 маусымдағы № 23 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2008 жылы 30 шілдеде № 2-9-64 тіркелді
title:
  rus: Алматы облысы, Ескелді ауданы, Сырымбет ауылдық округіне қарасты Сырымбет ауылындағы кейбір көшелерінің атауларын өзгерту туралы
  kaz: Алматы облысы, Ескелді ауданы, Сырымбет ауылдық округіне қарасты Сырымбет ауылындағы кейбір көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-30
approved_by:
- '154006008002'
version_date:
  kaz: 2008-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/40902/kaz/30.06.2008
