act_code: '128731'
requisite: Решение Карасайского районного маслихата Алматинской области от 27 декабря 2018 года № 38-3. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2019 года № 5008
title:
  rus: О бюджете Карасайского района на 2019-2021 годы
  kaz: Қарасай ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '154015000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128731/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128731/rus/27.12.2018
