act_code: '128731'
requisite: Решение Карасайского районного маслихата Алматинской области от 27 декабря 2018 года № 38-3. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2019 года № 5008
title:
  rus: О бюджете Карасайского района на 2019-2021 годы
  kaz: Қарасай ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '154015000002'
version_date:
  kaz: 2019-05-28
  rus: 2019-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128731/kaz/28.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128731/rus/28.05.2019
caused_by:
  code: '132363'
  requisite: Решение Карасайского районного маслихата Алматинской области от 28 мая 2019 года № 43-3. Зарегистрировано Департаментом юстиции Алматинской области 7 июня 2019 года № 5161
  title:
    rus: О внесении изменений в решение Карасайского районного маслихата от 27 декабря 2018 года № 38-3 «О бюджете Карасайского района на 2019-2021 годы»
    kaz: Қарасай аудандық мәслихатының 2018 жылғы 27 желтоқсандағы «Қарасай ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 38-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132363/rus
