act_code: '118443'
requisite: Решение Талгарского районного маслихата Алматинской области от 27 декабря 2017 года № 23-121. Зарегистрировано Департаментом юстиции Алматинской области 9 января 2018 года № 4486
title:
  rus: О бюджетах города Талгар и сельских округов Талгарского района на 2018-2020 годы
  kaz: Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '154013000002'
version_date:
  kaz: 2018-03-06
  rus: 2018-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/118443/kaz/06.03.2018
  rus: https://zan.gov.kz/client/#!/doc/118443/rus/06.03.2018
caused_by:
  code: '120167'
  requisite: Решение Талгарского районного маслихата Алматинской области от 6 марта 2018 года № 26-131. Зарегистрировано Департаментом юстиции Алматинской области 26 марта 2018 года № 4590
  title:
    rus: О внесении изменений в решение Талгарского районного маслихата от 27 декабря 2017 года № 23-121 «О бюджетах города Талгар и сельских округов Талгарского района на 2018-2020 годы»
    kaz: Талғар аудандық мәслихатының 2017 жылғы 27 желтоқсандағы «Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы» № 23-121 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120167/rus
