act_code: '35709'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2007 жылғы 22 қазандағы № 12 шешімі. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2007 жылы 12 қарашада № 2-1-56 тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2010 жылғы 14 сәуірдегі № 173 шешімімен
title:
  rus: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері
  kaz: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-22
approved_by:
- '154002000002'
version_date:
  kaz: 2009-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/35709/kaz/30.06.2009
caused_by:
  code: '49976'
  requisite: Алматы облысы Талдықорған қалалық мәслихатының 2009 жылғы 30 маусымдағы № 119 шешімі. Алматы облысының әділет департаменті Талдықорған қаласының әділет басқармасында 2010 жылы 19 қаңтарда № 2-1-112 тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2010 жылғы 14 сәуірдегі № 173 шешімімен
  title:
    rus: Талдықорған қалалық мәслихатының 2007 жылдың 22 қазанындағы "Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы" N 12 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Талдықорған қалалық мәслихатының 2007 жылдың 22 қазанындағы "Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы" N 12 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49976/rus
