act_code: '214222'
requisite: Решение акима Баканасского сельского округа Балхашского района Алматинской области от 21 августа 2025 года № 01
title:
  rus: О переименовании улицы «Лесная» в селе Ушжарма Баканасского сельского округа
  kaz: Бақанас ауылдық округіне қарасты Үшжарма ауылындағы «Лесная» көшесіне қайта атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-21
approved_by:
- '154014016002'
version_date:
  kaz: 2025-08-21
  rus: 2025-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/214222/kaz/21.08.2025
  rus: https://zan.gov.kz/client/#!/doc/214222/rus/21.08.2025
