act_code: '50088'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2009 жылғы 15 желтоқсандағы № 25-3 шешімі. Алматы облысының әділет департаменті Алакөл ауданының әділет басқармасында 2010 жылы 21 қаңтарда № 2-5-77 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2011 жылғы 19 қаңтардағы № 34-3 шешімімен
title:
  rus: Алакөл аумағында бекітілген базалық ставкалар шегінде бірыңғай салық ставкаларын белгілеу туралы
  kaz: Алакөл аумағында бекітілген базалық ставкалар шегінде бірыңғай салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-15
approved_by:
- '154003000002'
version_date:
  kaz: 2009-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/50088/kaz/15.12.2009
