act_code: '191730'
requisite: Решение Илийского районного маслихата Алматинской области от 29 декабря 2023 года № 18-49
title:
  rus: О бюджете Илийского района на 2024-2026 годы
  kaz: Іле ауданының 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '154017000002'
version_date:
  kaz: 2024-04-18
  rus: 2024-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/191730/kaz/18.04.2024
  rus: https://zan.gov.kz/client/#!/doc/191730/rus/18.04.2024
caused_by:
  code: '195981'
  requisite: Решение Илийского районного маслихата Алматинской области от 18 апреля 2024 года № 23-82
  title:
    rus: О внесении изменений в решение Илийского районного маслихата от 29 декабря 2023 года № 18-49 «О бюджете Илийского района на 2024-2026 годы»
    kaz: Іле аудандық мәслихатының 2023 жылғы 29 желтоқсандағы «Іле ауданының 2024-2026 жылдарға арналған  бюджеті туралы» № 18-49 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195981/rus
