act_code: '108665'
requisite: Решение акима Жолбарыс батыра сельского округа Каратальского района Алматинской области от 12 декабря 2016 года № 19. Зарегистрировано Департаментом юстиции Алматинской области 4 января 2017 года № 4057
title:
  rus: О снятии ограничительных мероприятий на территории села Кальпе сельского округа Жолбарыс батыра
  kaz: Жолбарыс батыр ауылдық округінің Кәлпе ауылы аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-12
approved_by:
- '154009005002'
version_date:
  kaz: 2016-12-12
  rus: 2016-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/108665/kaz/12.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108665/rus/12.12.2016
