act_code: '124106'
requisite: Решение Алматинского областного маслихата от 25 июля 2018 года № 34-176. Зарегистрировано Департаментом юстиции Алматинской области 8 августа 2018 года № 4782. Утратило силу решением Алматинского областного маслихата от 23 октября 2025 года № 42-236 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ставок платы за пользование водными ресурсами из поверхностных источников Алматинской области
  kaz: Алматы облысының жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-25
approved_by:
- '154000000002'
version_date:
  kaz: 2018-07-25
  rus: 2018-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/124106/kaz/25.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124106/rus/25.07.2018
