act_code: '229492'
requisite: Решение маслихата города Алатау Алматинской области от 21 августа 2026 года № 34-91
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат маслихата города Алатау»
  kaz: «Алатау қаласы мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-21
approved_by:
- '154022000002'
version_date:
  kaz: 2026-08-21
  rus: 2026-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/229492/kaz/21.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229492/rus/21.08.2026
