act_code: '78088'
requisite: Решение маслихата Алакольского района Алматинской области от 27 февраля 2014 года № 27-2. Зарегистрировано Департаментом юстиции Алматинской области 19 марта 2014 года № 2617. Утратило силу решением Алакольского районного маслихата Алматинской области от 05 мая 2014 года № 31-7
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Алакольскому району
  kaz: Алакөл ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-02-27
approved_by:
- '154003000002'
version_date:
  kaz: 2014-02-27
  rus: 2014-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78088/kaz/27.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78088/rus/27.02.2014
