act_code: '192338'
requisite: Решение Кегенского районного маслихата Алматинской области от 4 января 2024 года № 16-75
title:
  rus: О бюджетах сельских округов Кегенского района на 2024-2026 годы
  kaz: Кеген ауданының ауылдық округтерінің  2024-2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-04
approved_by:
- '154021000002'
version_date:
  kaz: 2024-12-13
  rus: 2024-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/192338/kaz/13.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192338/rus/13.12.2024
caused_by:
  code: '204597'
  requisite: Решение Кегенского районного маслихата Алматинской области от 13 декабря 2024 года № 28-124
  title:
    rus: О внесении изменений в решение Кегенского районного маслихата от 4 января 2024 года № 16-75 «О бюджетах сельских округов Кегенского района на 2024-2026 годы»
    kaz: Кеген аудандық мәслихатының 2024  жылғы 4 қаңтарындағы «Кеген ауданының ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы» № 16-75 шешімге өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204597/rus
