act_code: '165356'
requisite: Решение Талгарского районного маслихата Алматинской области от 4 марта 2022 года № 21-73. Утратило силу решением Талгарского районного маслихата Алматинской области от 19 января 2023 года № 40-130
title:
  rus: Об утверждении регламента маслихата Талгарского района
  kaz: Талғар ауданы мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2022-03-04
approved_by:
- '154013000002'
version_date:
  kaz: 2022-03-04
  rus: 2022-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/165356/kaz/04.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165356/rus/04.03.2022
