act_code: '70693'
requisite: Решение маслихата Сарканского района Алматинской области от 10 января 2013 года № 13-74, зарегистрировано Департаментом юстиции Алматинской области 30 января 2013 года № 2293. Утратило силу решением Сарканского районного маслихата Алматинской области от 09 февраля 2015 года № 49-251
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Сарканского района на 2013-2014 годы
  kaz: Сарқан ауданы бойынша жүзеге асыратын барлық салық төлеушілер үшін бірыңғай тіркелген салық ставкаларын 2013-2014 жылдарға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-01-10
approved_by:
- '154005000002'
version_date:
  kaz: 2013-01-10
  rus: 2013-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/70693/kaz/10.01.2013
  rus: https://zan.gov.kz/client/#!/doc/70693/rus/10.01.2013
