act_code: '37694'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2008 жылы 30 қаңтардағы № 5-29 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2008 жылы 19 ақпанда № 2-4-63 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 26 ақпандағы № 31-187 шешімімен
title:
  rus: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
  kaz: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-30
approved_by:
- '154011000002'
version_date:
  kaz: 2008-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/37694/kaz/30.01.2008
