act_code: '102140'
requisite: Решение Талдыкорганского городского маслихата Алматинской области от 13 апреля 2016 года № 10. Зарегистрировано Департаментом юстиции Алматинской области 12 мая 2016 года № 3824. Утратило силу решением Талдыкорганского городского маслихата Алматинской области от 22 мая 2018 года № 191
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения по городу Талдыкорган
  kaz: Талдықорған қаласы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-13
approved_by:
- '154002000002'
version_date:
  kaz: 2016-04-13
  rus: 2016-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102140/kaz/13.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102140/rus/13.04.2016
