act_code: '67999'
requisite: Решение акима Кайнарского сельского округа Алакольского района Алматинской области от 10 сентября 2012 года № 4. Зарегистрировано Департаментом юстиции Алматинской области 04 октября 2012 года № 2140. Утратило силу решением акима Кайнарского сельского округа Алакольского района Алматинской области от 6 ноября 2012 года № 6
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізе отырып карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-10
approved_by:
- '154003015002'
version_date:
  kaz: 2012-09-10
  rus: 2012-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/67999/kaz/10.09.2012
  rus: https://zan.gov.kz/client/#!/doc/67999/rus/10.09.2012
