act_code: '126488'
requisite: Решение Кегенского районного маслихата Алматинской области от 27 ноября 2018 года № 9-30. Зарегистрировано Департаментом юстиции Алматинской области 29 ноября 2018 года № 4905. Утратило силу решением Кегенского районного маслихата Алматинской области от 25 декабря 2023 года № 14-68
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Кегенского района
  kaz: Кеген ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ОПРД
- ПОР
- РЕШ
approved_on: 2018-11-27
approved_by:
- '154021000002'
version_date:
  kaz: 2021-12-28
  rus: 2021-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/126488/kaz/28.12.2021
  rus: https://zan.gov.kz/client/#!/doc/126488/rus/28.12.2021
caused_by:
  code: '163203'
  requisite: Решение Кегенского районного маслихата Алматинской области от 28 декабря 2021 года № 22-79. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26370. Утратило силу решением Кегенского районного маслихата Алматинской области от 25 декабря 2023 года № 14-68
  title:
    rus: О внесении изменений в решение Кегенского районного маслихата от 27 ноября 2018 года № 9-30 «Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Кегенского района»
    kaz: Кеген аудандық мәслихатының «Кеген ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы» 2018 жылғы 27 қарашадағы № 9-30 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/163203/rus
