act_code: '47505'
requisite: Алматы облысы Қапшағай қалалық мәслихатының 2009 жылғы 10 тамыздағы № 160-29 шешімі. Алматы облысының Әділет департаменті Қапшағай қаласының Әділет басқармасында 2009 жылдың 25 тамызында № 2-2-89 тіркелді. Күші жойылды - Алматы облысы Қапшағай қалалық мәслихатының 2012 жылғы 08 маусымдағы № 4-32 шешімімен
title:
  rus: «Қапшағай қаласының құрметті азаматы» атағын беру Ережесін бекіту туралы
  kaz: «Қапшағай қаласының құрметті азаматы» атағын беру Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-10
approved_by:
- '154020000002'
version_date:
  kaz: 2009-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/47505/kaz/10.08.2009
