act_code: '31186'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2006 жылғы 20 желтоқсандағы № 52-11 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2007 жылғы 9 қаңтарда № 2-5-38 тіркелген
title:
  rus: Аудан көлемінде автотұрақтар, автокөліктерге май кұю станциялары және базарлар орналасқан жер учаскелеріне 2007 жылы салынатын салық ставкалары туралы
  kaz: Аудан көлемінде автотұрақтар, автокөліктерге май кұю станциялары және базарлар орналасқан жер учаскелеріне 2007 жылы салынатын салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-20
approved_by:
- '154003000002'
version_date:
  kaz: 2006-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/31186/kaz/20.12.2006
