act_code: '151705'
requisite: Решение Жамбылского районного маслихата Алматинской области от 28 декабря 2020 года № 81-364. Зарегистрировано Департаментом юстиции Алматинской области 11 января 2021 года № 5854
title:
  rus: О бюджете Жамбылского района на 2021-2023 годы
  kaz: Жамбыл ауданының 2021-2023 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '154018000002'
version_date:
  kaz: 2021-08-24
  rus: 2021-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/151705/kaz/24.08.2021
  rus: https://zan.gov.kz/client/#!/doc/151705/rus/24.08.2021
caused_by:
  code: '158256'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 24 августа 2021 года № 9-49. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 сентября 2021 года № 24198
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 28 декабря 2020 года № 81-364 «О бюджете Жамбылского района на 2021-2023 годы»
    kaz: Жамбыл аудандық мәслихатының 2020 жылғы 28 желтоқсандағы № 81-364 «Жамбыл ауданының 2021-2023 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158256/rus
