act_code: '47715'
requisite: Алматы облысы Қаратал ауданы Қаңбақты ауылдық округі әкімінің 2009 жылғы 18 тамыздағы № 4 шешімі. Алматы облысының әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 8 қыркүйекте № 2-12-117 тіркелді
title:
  rus: Дөңши ауылының көшелеріне атау беру туралы
  kaz: Дөңши ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-18
approved_by:
- '154009004002'
version_date:
  kaz: 2009-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/47715/kaz/18.08.2009
