act_code: '128877'
requisite: Решение Аксуского районного маслихата Алматинской области от 28 декабря 2018 года № 37-179. Зарегистрировано Департаментом юстиции Алматинской области 22 января 2019 года № 5022
title:
  rus: О бюджетах сельских округов Аксуского района на 2019-2021 годы
  kaz: Ақсу ауданының ауылдық округтерінің 2019-2021 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '154011000002'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128877/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128877/rus/28.12.2018
