act_code: '206207'
requisite: Решение маслихата города Алатау Алматинской области от 27 декабря 2024 года № 14-42
title:
  rus: «О бюджете города Алатау на 2025-2027 годы»
  kaz: «Алатау қаласының 2025-2027 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '154022000002'
version_date:
  kaz: 2025-06-12
  rus: 2025-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/206207/kaz/12.06.2025
  rus: https://zan.gov.kz/client/#!/doc/206207/rus/12.06.2025
caused_by:
  code: '211299'
  requisite: Решение маслихата города Алатау Алматинской области от 12 июня 2025 года № 16-52
  title:
    rus: О внесении изменении в решение маслихата города Алатау от 27 декабря 2024 года № 14-42 «О бюджете города Алатау на 2025-2027 годы»
    kaz: Алатау қаласы мәслихатының 2024 жылдың 27 желтоқсандағы № 14-42 «Алатау қаласының 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211299/rus
