act_code: '43173'
requisite: Алматы облысы Райымбек аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 17-83 шешімі. Алматы облысының әділет департаменті Райымбек ауданының әділет басқармасында 2009 жылғы 8 қаңтарда № 2-15-64 тіркелді. Күші жойылды - Алматы облысы Райымбек аудандық мәслихатының 2010 жылғы 19 наурыздағы № 35-180 шешімімен
title:
  rus: Райымбек ауданының 2009 жылға арналған аудан бюджеті туралы
  kaz: Райымбек ауданының 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154016000002'
version_date:
  kaz: 2009-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/43173/kaz/05.08.2009
caused_by:
  code: '47408'
  requisite: Алматы облысы Райымбек аудандық мәслихатының 2009 жылғы 5 тамыздағы № 28-143 шешімі. Алматы облысының әділет департаменті Райымбек ауданының әділет басқармасында 2009 жылғы 17 тамызда № 2-15-74 тіркелді. Күші жойылды - Алматы облысы Райымбек аудандық мәслихатының 2010 жылғы 19 наурыздағы № 35-180 шешімімен
  title:
    rus: Райымбек аудандық мәслихатының 2008 жылғы 22 желтоқсандағы Райымбек ауданынң 2009 жылға арналған аудан бюджеті туралы N 17-83 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Райымбек аудандық мәслихатының 2008 жылғы 22 желтоқсандағы Райымбек ауданынң 2009 жылға арналған аудан бюджеті туралы N 17-83 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47408/rus
