act_code: '56336'
requisite: Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 24 қарашадағы № 46-277 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2010 жылы 29 желтоқсанда № 2-9-116 тіркелді
title:
  rus: Ескелді ауданының жер учаскелері үшін төлемақының базалық ставкаларын түзету коэффициенттері мен елді мекендердегі аймақтардың шекаралын бекіту туралы
  kaz: Ескелді ауданының жер учаскелері үшін төлемақының базалық ставкаларын түзету коэффициенттері мен елді мекендердегі аймақтардың шекаралын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-24
approved_by:
- '154006000002'
version_date:
  kaz: 2010-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56336/kaz/24.11.2010
