act_code: '220369'
requisite: Решение акима Бесагашского сельского округа Талгарского района Алматинской области от 7 декабря 2025 года № 8
title:
  rus: О переименовании улицы «Аэропортная» в селе Бесагаш Бесагашского сельского округа
  kaz: Бесағаш ауылдық округінің Бесағаш ауылындағы «Аэропортная» көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-07
approved_by:
- '154013005002'
version_date:
  kaz: 2025-12-07
  rus: 2025-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/220369/kaz/07.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220369/rus/07.12.2025
