act_code: '43237'
requisite: Алматы облысы Қарасай аудандық мәслихатының 2008 жылғы 18 желтоқсандағы № 17-3 шешімі. Алматы облысы Қарасай ауданының Әділет басқармасында 2009 жылғы 6 қаңтарда № 2-11-62 тіркелді. Күші жойылды - Алматы облысы Қарасай аудандық мәслихатының 2010 жылғы 03 ақпандағы № 38-9 шешімімен
title:
  rus: Қарасай ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Қарасай ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '154015000002'
version_date:
  kaz: 2009-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43237/kaz/24.02.2009
caused_by:
  code: '44894'
  requisite: Алматы облысы Қарасай аудандық мәслихаттың 2009 жылғы 24 ақпандағы № 21-3 шешімі. Алматы облысының Әділет департаменті Қарасай ауданының Әділет басқармасында 2009 жылы 12 наурызда № 2-11-65 тіркелді. Күші жойылды - Алматы облысы Қарасай аудандық мәслихатының 2009 жылғы 26 қарашадағы № 33-5 шешімімен
  title:
    rus: 2008 жылғы 18 желтоқсандағы "Қарасай ауданының 2009 жылға арналған аудандық бюджеті туралы" N 17-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2008 жылғы 18 желтоқсандағы "Қарасай ауданының 2009 жылға арналған аудандық бюджеті туралы" N 17-3 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44894/rus
