act_code: '228253'
requisite: Решение Алматинского областного маслихата от 23 июля 2026 года № 52-308
title:
  rus: Об утверждении правил присвоения звания «Почетный гражданин Алматинской области (района, города)»
  kaz: «Алматы облысының (қаланың, ауданның) құрметті азаматы» атағын беру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-07-23
approved_by:
- '154000000002'
version_date:
  kaz: 2026-07-23
  rus: 2026-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/228253/kaz/23.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228253/rus/23.07.2026
