act_code: '192231'
requisite: Решение Райымбекского районного маслихата Алматинской области от 27 декабря 2023 года № 16-90
title:
  rus: О районном бюджете Райымбекского района на 2024-2026 годы
  kaz: Райымбек ауданының 2024-2026 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '154016000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/192231/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192231/rus/12.12.2024
caused_by:
  code: '204427'
  requisite: Решение Райымбекского районного маслихата Алматинской области от 12 декабря 2024 года № 35-190
  title:
    rus: О внесении изменений в решение Райымбекского районного маслихата от 27 декабря 2023 года № 16-90 «О бюджете Райымбекского района на 2024-2026 годы»
    kaz: Райымбек аудандық мәслихатының 2023 жылғы 27 желтоқсандағы № 16-90 «Райымбек ауданының 2024-2026 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204427/rus
