act_code: '49778'
requisite: Алматы облысы Балқаш аудандық мәслихатының 2009 жылғы 28 желтоқсандағы № 26-133 шешімі. Алматы облысының Әділет департаменті Балқаш ауданының Әділет басқармасында 2010 жылы 06 ақпанда № 2-6-63 тіркелді. Күші жойылды - Алматы облысы Балқаш аудандық мәслихатының 2011 жылғы 28 наурыздағы № 44-209 шешімімен
title:
  rus: Балқаш ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Балқаш ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '154014000002'
version_date:
  kaz: 2010-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/49778/kaz/19.04.2010
caused_by:
  code: '52061'
  requisite: Алматы облысы Балқаш аудандық мәслихатының 2010 жылғы 19 сәуірдегі № 30-158 шешімі. Алматы облысының Әділет департаменті Балқаш ауданының Әділет басқармасында 2010 жылы 27 сәуірде № 2-6-69 тіркелді. Күші жойылды - Алматы облысы Балқаш аудандық мәслихатының 2011 жылғы 28 наурыздағы № 44-209 шешімімен
  title:
    rus: Балқаш аудандық мәслихаттың 2009 жылғы 28 желтоқсандағы "Балқаш ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 26-133 шешіміне өзгерістер енгізу туралы
    kaz: Балқаш аудандық мәслихаттың 2009 жылғы 28 желтоқсандағы "Балқаш ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 26-133 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52061/rus
