act_code: '161872'
requisite: Решение маслихата Алматинской области от 14 декабря 2021 года № 12-59. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25829
title:
  rus: Об областном бюджете Алматинской области на 2022-2024 годы
  kaz: Алматы облысының 2022-2024  жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-14
approved_by:
- '154000000002'
version_date:
  kaz: 2021-12-14
  rus: 2021-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/161872/kaz/14.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161872/rus/14.12.2021
