act_code: '42598'
requisite: Алматы облысы Көксу аудандық мәслихатының 2008 жылғы 23 қазандағы № 17-4 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2008 жылғы 04 желтоқсанда № 2-14-67 тіркелді. Күші жойылды - Алматы облысы Көксу аудандық мәслихатының 2010 жылғы 04 ақпандағы № 35-4 шешімімен
title:
  rus: Көксу ауданы бойынша жер салығының 2009 жылға арналған ставкасын бекіту туралы
  kaz: Көксу ауданы бойынша жер салығының 2009 жылға арналған ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-23
approved_by:
- '154007000002'
version_date:
  kaz: 2008-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/42598/kaz/23.10.2008
