act_code: '169708'
requisite: Решение маслихата города Қонаев Алматинской области от 28 апреля 2022 года № 23-76. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 мая 2022 года № 28053
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по городу Қонаев
  kaz: Қонаев қаласы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-28
approved_by:
- '154020000002'
version_date:
  kaz: 2022-04-28
  rus: 2022-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/169708/kaz/28.04.2022
  rus: https://zan.gov.kz/client/#!/doc/169708/rus/28.04.2022
