act_code: '76871'
requisite: Решение маслихата Алакольского района Алматинской области от 05 декабря 2013 года N 23-3. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2014 года N 2554. Утратило силу решением Алакольского районного маслихата Алматинской области от 05 мая 2014 года № 31-7
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-05
approved_by:
- '154003000002'
version_date:
  kaz: 2013-12-05
  rus: 2013-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/76871/kaz/05.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76871/rus/05.12.2013
