act_code: '139001'
requisite: Решение Сарканского районного маслихата Алматинской области от 14 января 2020 года № 73-292. Зарегистрировано Департаментом юстиции Алматинской области 21 января 2020 года № 5418
title:
  rus: О бюджетах города Саркан и сельских округов Сарканского района на 2020-2022 годы
  kaz: Сарқан ауданының Сарқан қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-14
approved_by:
- '154005000002'
version_date:
  kaz: 2020-04-20
  rus: 2020-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139001/kaz/20.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139001/rus/20.04.2020
caused_by:
  code: '142383'
  requisite: Решение Сарканского районного маслихата Алматинской области от 20 апреля 2020 года № 79-312. Зарегистрировано Департаментом юстиции Алматинской области 28 апреля 2020 года № 5509
  title:
    rus: О внесении изменений в решение Сарканского районного маслихата от 14 января 2020 года № 73-292 «О бюджетах города Саркан и сельских округов Сарканского района на 2020-2022 годы»
    kaz: Сарқан аудандық мәслихатының 2020 жылғы 14 қаңтардағы № 73-292 «Сарқан ауданының Сарқан қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142383/rus
