act_code: '56339'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2010 жылғы 15 желтоқсандағы № 212 шешімі. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2010 жылы 30 желтоқсанда № 2-1-134 тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2012 жылғы 22 мамырдағы № 44 шешімімен
title:
  rus: Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы
  kaz: Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '154002000002'
version_date:
  kaz: 2011-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/56339/kaz/21.12.2011
caused_by:
  code: '62135'
  requisite: Решение Талдыкорганского городского маслихата Алматинской области от 21 декабря 2011 года № 319. Зарегистрировано Управлением юстиции города Талдыкорган Департамента юстиции Алматинской области 22 декабря 2011 года № 2-1-152. Утратило силу решением Талдыкорганского городского маслихата Алматинской области от 22 мая 2012 года № 44
  title:
    rus: О внесении изменений в решение от 15 декабря 2010 года N 212 "О бюджете города Талдыкорган на 2011-2013 годы"
    kaz: 2010 жылғы 15 желтоқсандағы "Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы" N 212 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/62135/rus
