act_code: '56339'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2010 жылғы 15 желтоқсандағы № 212 шешімі. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2010 жылы 30 желтоқсанда № 2-1-134 тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2012 жылғы 22 мамырдағы № 44 шешімімен
title:
  rus: Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы
  kaz: Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '154002000002'
version_date:
  kaz: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56339/kaz/25.03.2011
caused_by:
  code: '58082'
  requisite: Решение маслихата города Талдыкорган Алматинской области от 25 марта 2011 года № 245. Зарегистрировано Управлением юстиции города Талдыкорган Департамента юстиции Алматинской области 08 апреля 2011 года № 2-1-140. Утратило силу решением Талдыкорганского городского маслихата Алматинской области от 22 мая 2012 года № 44
  title:
    rus: О внесении изменений и дополнений в решение от 15 декабря 2010 года N 212 "О бюджете города Талдыкорган на 2011-2013 годы"
    kaz: 2010 жылғы 15 желтоқсандағы "Талдықорған қаласының 2011-2013 жылдарға арналған бюджеті туралы" N 212 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58082/rus
