act_code: '138820'
requisite: Решение Райымбекского районного маслихата Алматинской области от 8 января 2020 года № 64-302. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2020 года № 5404
title:
  rus: О бюджетах сельских округов Райымбекского района на 2020-2022 годы
  kaz: Райымбек ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '154016000002'
version_date:
  kaz: 2020-04-21
  rus: 2020-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/138820/kaz/21.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138820/rus/21.04.2020
caused_by:
  code: '142372'
  requisite: Решение Райымбекского районного маслихата Алматинской области от 21 апреля 2020 года № 67-326. Зарегистрировано Департаментом юстиции Алматинской области 28 апреля 2020 года № 5507
  title:
    rus: О внесении изменений в решение Райымбекского районного маслихата от 8 января 2020 года № 64-302 «О бюджетах сельских округов Райымбекского района на 2020-2022 годы»
    kaz: Райымбек аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 64-302 «Райымбек ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142372/rus
