act_code: '49672'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2009 жылғы 15 желтоқсандағы № 25-1 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2009 жылы 30 желтоқсанда № 2-5-76 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2011 жылғы 19 қаңтардағы № 34-3 шешімімен
title:
  rus: Алакөл ауданының 2010-2012 жылдарға арналған аудандық бюджетi туралы
  kaz: Алакөл ауданының 2010-2012 жылдарға арналған аудандық бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-15
approved_by:
- '154003000002'
version_date:
  kaz: 2010-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49672/kaz/22.06.2010
caused_by:
  code: '53388'
  requisite: Алматы облысы Алакөл аудандық мәслихатының 2010 жылғы 22 масымдағы № 28-1 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 29 маусымда № 2-5-111 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2011 жылғы 19 қаңтардағы № 34-3 шешімімен
  title:
    rus: Алакөл аудандық мәслихатының 2009 жылғы 15 желтоқсанда қабылданған "Алакөл ауданының 2010-2012 жылдарға арналған аудандық бюджетi туралы" 25-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Алакөл аудандық мәслихатының 2009 жылғы 15 желтоқсанда қабылданған "Алакөл ауданының 2010-2012 жылдарға арналған аудандық бюджетi туралы" 25-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53388/rus
