act_code: '78569'
requisite: Решение маслихата Кербулакского района Алматинской области от 27 марта 2014 года N 28-169. Зарегистрировано Департаментом юстиции Алматинской области 31 марта 2014 года N 2641. Утратило силу решением Кербулакского районного маслихата Алматинской области от 30 мая 2014 года N 31-189
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Кербулакского района
  kaz: Кербұлақ ауданында аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-27
approved_by:
- '154010000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78569/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78569/rus/27.03.2014
