act_code: '97172'
requisite: Решение Коксуского районного маслихата Алматинской области от 21 декабря 2015 года № 49-1. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2015 года № 3642. Утратило силу решением Коксуского районного маслихата Алматинской области 12 июня 2017 года № 17-8
title:
  rus: О бюджете Коксуского района на 2016-2018 годы
  kaz: Көксу ауданының 2016-2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '154007000002'
version_date:
  kaz: 2016-02-05
  rus: 2016-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/97172/kaz/05.02.2016
  rus: https://zan.gov.kz/client/#!/doc/97172/rus/05.02.2016
caused_by:
  code: '98967'
  requisite: Решение Коксуского районного маслихата Алматинской области от 05 февраля 2016 года № 52-1. Зарегистрировано Департаментом юстиции Алматинской области 12 февраля 2016 года № 3709. Утратило силу решением Коксуского районного маслихата Алматинской области 12 июня 2017 года № 17-8
  title:
    rus: О внесении изменений в решение Коксуского районного маслихата от 21 декабря 2015 года № 49-1 "О бюджете Коксуского района на 2016-2018 годы"
    kaz: Көксу ауданы мәслихатының 2015 жылғы 21 желтоқсандағы "Көксу ауданының 2016-2018 жылдарға арналған бюджеті туралы" № 49-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/98967/rus
