act_code: '227861'
requisite: Решение акима Каратурыкского сельского округа Енбекшиказахского района Алматинской области от 29 мая 2026 года № 1-04/05
title:
  rus: О переименовании улиц сел Ащысай и Каратурык Каратурыкского сельского округа
  kaz: Қаратұрық ауылдық округінің Ащысай және Қаратұрық ауылдарының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-29
approved_by:
- '154012012002'
version_date:
  kaz: 2026-05-29
  rus: 2026-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/227861/kaz/29.05.2026
  rus: https://zan.gov.kz/client/#!/doc/227861/rus/29.05.2026
