act_code: '135617'
requisite: Решение Сарканского районного маслихата Алматинской области от 25 октября 2019 года № 68-272. Зарегистрировано Департаментом юстиции Алматинской области 29 октября 2019 года № 5288. Утратило силу решением Сарканского районного маслихата Алматинской области от 9 июня 2020 года № 82-320
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Сарканскому району
  kaz: Сарқан ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-25
approved_by:
- '154005000002'
version_date:
  kaz: 2019-10-25
  rus: 2019-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/135617/kaz/25.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135617/rus/25.10.2019
