act_code: '58078'
requisite: Решение Карасайского районного маслихата от 10 марта 2011 года № 51-4. Зарегистрировано Карасайским районным управлением юстиции от 7 апреля 2011 года за № 2-11-100. Утратило силу решением Карасайского районного маслихата Алматинской области от 18.01.2017 № 11-11
title:
  rus: Об исчислении базовой ставки земельного налога по Карасайскому району
  kaz: Қарасай ауданы аумағында жер салығының базалық ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-10
approved_by:
- '154015000002'
version_date:
  kaz: 2011-03-10
  rus: 2011-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/58078/kaz/10.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58078/rus/10.03.2011
