act_code: '216168'
requisite: Решение акима Первомайского сельского округа Карасайского района Алматинской области от 14 октября 2025 года № 1
title:
  rus: О переименовании улиц села Бекболат Первомайского сельского округа Карасайского района
  kaz: Қарасай ауданы Бірінші Май ауылдық округі Бекболат ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-14
approved_by:
- '154015008002'
version_date:
  kaz: 2025-10-14
  rus: 2025-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/216168/kaz/14.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216168/rus/14.10.2025
