act_code: '57159'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 4-38-239 шешімі. Алматы облысының Әділет департаменті Панфилов ауданының Әділет басқармасында 2011 жылы 27 қаңтарда № 2-16-127 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2013 жылғы 12 сәуірдегі № 5-15-105 шешімімен
title:
  rus: Панфилов ауданының жер учаскелері үшін төлемақының базалық ставкаларын түзету коэффициенттері мен елді мекендердегі аймақтардың шекараларын бекіту туралы
  kaz: Панфилов ауданының жер учаскелері үшін төлемақының базалық ставкаларын түзету коэффициенттері мен елді мекендердегі аймақтардың шекараларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '154004000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/57159/kaz/22.12.2010
