act_code: '214115'
requisite: Решение Алматинского областного маслихата от 27 августа 2025 года № 40-221
title:
  rus: Об утверждении расходов местных исполнительных органов на возмещение организациям по водоснабжению и (или) водоотведению затрат при использовании питьевой воды на пожаротушение в Алматинской области
  kaz: Алматы облысында ауыз суды өрт сөндіруге пайдалану кезіндегі шығындарын сумен жабдықтау және (немесе) су бұру жөніндегі ұйымдарға өтеуге жұмсалатын жергілікті атқарушы органдардың шығыстарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-27
approved_by:
- '154000000002'
version_date:
  kaz: 2025-08-27
  rus: 2025-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/214115/kaz/27.08.2025
  rus: https://zan.gov.kz/client/#!/doc/214115/rus/27.08.2025
