act_code: '176850'
requisite: Решение Талгарского районного маслихата Алматинской области от 29 декабря 2022 года № 39-116
title:
  rus: Об утверждении плана по управлению пастбищами Талгарского района и их использованию на 2023-2024 годы
  kaz: Талғар ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '154013000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/176850/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176850/rus/29.12.2022
