act_code: '56329'
requisite: Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2008 жылғы 24 қаңтардағы N  7-2 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2008 жылы 19 ақпанда N 2-8-68 тіркелді. Күші жойылды -  Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2009 жылғы 31 қаңтардағы N 23-3 шешімімен
title:
  rus: Өздері жылылтатын жеке меншік үйде тұратын тұрмысы төмен отбасыларына тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
  kaz: Өздері жылылтатын жеке меншік үйде тұратын тұрмысы төмен отбасыларына тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-24
approved_by:
- '154012000002'
version_date:
  kaz: 2008-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56329/kaz/24.01.2008
