act_code: '194608'
requisite: Решение акима Талгарского района Алматинской области от 15 марта 2024 года № 03-07. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2024 года № 6099-05. Утратило силу решением акима Талгарского района Алматинской области от 27 марта 2025 года № 03-03 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов в Талгарском районе
  kaz: Талғар ауданында дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-15
approved_by:
- '154013000003'
version_date:
  kaz: 2024-03-15
  rus: 2024-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/194608/kaz/15.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194608/rus/15.03.2024
