act_code: '47718'
requisite: Алматы облысы Қаратал ауданы Бастөбе ауылдық округі әкімінің 2009 жылғы 18 тамыздағы № 14 шешімі. Алматы облысының әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 8 қыркүйекте № 2-12-120 тіркелді
title:
  rus: Бастөбе ауылдық округінің елді мекендеріндегі көшелерге атау беру туралы
  kaz: Бастөбе ауылдық округінің елді мекендеріндегі көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-18
approved_by:
- '154009007002'
version_date:
  kaz: 2009-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/47718/kaz/18.08.2009
