act_code: '56888'
requisite: Алматы облысы Талғар ауданы әкімінің 2010 жылғы 31 желтоқсандағы N 12-321 шешімі. Алматы облысының Әділет департаменті Талғар ауданының Әділет басқармасында 2011 жылы 18 қаңтарда N 2-18-122 тіркелді
title:
  rus: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-31
approved_by:
- '154013000001'
version_date:
  kaz: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/56888/kaz/31.12.2010
