act_code: '139215'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 10 января 2020 года № 58-159. Зарегистрировано Департаментом юстиции Алматинской области 21 января 2020 года № 5416
title:
  rus: О бюджетах города Есик и сельских округов Енбекшиказахского района на 2020-2022 годы
  kaz: Еңбекшіқазақ ауданының Есік қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '154012000002'
version_date:
  kaz: 2020-01-10
  rus: 2020-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/139215/kaz/10.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139215/rus/10.01.2020
