act_code: '139215'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 10 января 2020 года № 58-159. Зарегистрировано Департаментом юстиции Алматинской области 21 января 2020 года № 5416
title:
  rus: О бюджетах города Есик и сельских округов Енбекшиказахского района на 2020-2022 годы
  kaz: Еңбекшіқазақ ауданының Есік қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '154012000002'
version_date:
  kaz: 2020-08-13
  rus: 2020-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/139215/kaz/13.08.2020
  rus: https://zan.gov.kz/client/#!/doc/139215/rus/13.08.2020
caused_by:
  code: '145652'
  requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 13 августа 2020 года № 66-189. Зарегистрировано Департаментом юстиции Алматинской области 19 августа 2020 года № 5615
  title:
    rus: О внесении изменений в решение Енбекшиказахского районного маслихата от 10 января 2020 года № 58-159 «О бюджетах города Есик и сельских округов Енбекшиказахского района на 2020-2022 годы»
    kaz: Еңбекшіқазақ аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 58-159 «Еңбекшіқазақ ауданының Есік қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145652/rus
