act_code: '166834'
requisite: Решение Уйгурского районного акима Алматинской области от 14 апреля 2022 года № 12. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 апреля 2022 года № 27685. Утратило силу решением акима Уйгурского района Алматинской области от 2 июля 2024 года № 233
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-14
approved_by:
- '154008000003'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/166834/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166834/rus/14.04.2022
