act_code: '146234'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 27 августа 2020 года № 68-387. Зарегистрировано Департаментом юстиции Алматинской области 11 сентября 2020 года № 5641
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Ескельдинском районе
  kaz: Ескелді ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-27
approved_by:
- '154006000002'
version_date:
  kaz: 2022-11-10
  rus: 2022-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/146234/kaz/10.11.2022
  rus: https://zan.gov.kz/client/#!/doc/146234/rus/10.11.2022
caused_by:
  code: '173678'
  requisite: Решение Ескельдинского районного маслихата области Жетісу от 10 ноября 2022 года № 39-132. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 ноября 2022 года № 30506
  title:
    rus: О внесении изменений и дополнений в решение Ескельдинского районного маслихата от 27 августа 2020 года № 68-387 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Ескельдинском районе»
    kaz: Ескелді аудандық мәслихатының 2020 жылғы 27 тамыздағы № 68-387 «Ескелді ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173678/rus
