act_code: '88683'
requisite: Решение №1 от 10.03.2015, Акимат Нуринского сельского округа
title:
  rus: 'О переименовании улицы «8 Март» в селе Нура Нуринского сельского округа '
  kaz: 'Нұра ауылдық округінің Нұра ауылындағы «8 Март» көшесін қайта атау туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-10
approved_by:
- '154013011001'
version_date:
  kaz: 2015-03-03
  rus: 2015-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/88683/kaz/03.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88683/rus/03.03.2015
