act_code: '44540'
requisite: Алматы облысы Жамбыл аудандық мәслихатының 2009 жылғы 31 қаңтардағы № 20-85 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2009 жылғы 23 ақпанда № 2-7-71 тіркелді. Күші жойылды - Алматы облысы Жамбыл аудандық мәслихатының 2010 жылғы 6 қаңтардағы № 32-140 шешімімен
title:
  rus: Жамбыл ауданында өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
  kaz: Жамбыл ауданында өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-31
approved_by:
- '154018000002'
version_date:
  kaz: 2009-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/44540/kaz/31.01.2009
