act_code: '222710'
requisite: Решение акима Байтерекского сельского округа Енбекшиказахского района Алматинской области от 29 января 2026 года № 1-02
title:
  rus: Решение акима Байтерекского сельского округа о переименовании улиц в селе Байтерек
  kaz: Бәйтерек ауылдық округінің Бәйтерек ауылындағы көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-29
approved_by:
- '154012016002'
version_date:
  kaz: 2026-01-29
  rus: 2026-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/222710/kaz/29.01.2026
  rus: https://zan.gov.kz/client/#!/doc/222710/rus/29.01.2026
