act_code: '49556'
requisite: Алматы облысы Райымбек аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 32-160 шешімі. Алматы облысы Райымбек ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда № 2-15-77 тіркелді. Күші жойылды - Алматы облысы Райымбек аудандық мәслихатының 2011 жылғы 18 сәуірдегі № 52-253 шешімімен
title:
  rus: Райымбек ауданының 2010-2012 жылдарға арналған аудан бюджеті туралы
  kaz: Райымбек ауданының 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '154016000002'
version_date:
  kaz: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/49556/kaz/06.12.2010
caused_by:
  code: '55965'
  requisite: Алматы облысы Райымбек аудандық мәслихатының 2010 жылғы 6 желтоқсандағы N 43-212 шешімі. Алматы облысы Райымбек ауданының Әділет басқармасында 2010 жылғы 14 желтоқсанда N 2-15-96 тіркелді. Күші жойылды - Алматы облысы Райымбек аудандық мәслихатының 2011 жылғы 18 сәуірдегі N 52-253 шешімімен
  title:
    rus: Райымбек аудандық мәслихатының 2009 жылғы 21 желтоқсандағы «Райымбек ауданының 2010 – 2012 жылдарға арналған аудан бюджеті туралы» № 32-160 шешіміне өзгерістер енгізу туралы
    kaz: Райымбек аудандық мәслихатының 2009 жылғы 21 желтоқсандағы «Райымбек ауданының 2010 – 2012 жылдарға арналған аудан бюджеті туралы» № 32-160 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55965/rus
