act_code: '202890'
requisite: Решение маслихата города Алатау Алматинской области от 12 ноября 2024 года № 11-36. Зарегистрировано Департаментом юстиции Алматинской области 19 ноября 2024 года № 6186-05
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Алатау
  kaz: Алатау қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-12
approved_by:
- '154022000002'
version_date:
  kaz: 2024-11-12
  rus: 2024-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/202890/kaz/12.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202890/rus/12.11.2024
