act_code: '51453'
requisite: Алматы облысы Жамбыл ауданы мәслихатының 2010 жылғы 5 наурыздағы № 35-152 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 26 наурызда № 2-7-92 тіркелді
title:
  rus: 2010 жылға арналған жер салығының базалық ставкаларын нақтылау туралы
  kaz: 2010 жылға арналған жер салығының базалық ставкаларын нақтылау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-05
approved_by:
- '154018000002'
version_date:
  kaz: 2010-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51453/kaz/05.03.2010
