act_code: '117681'
requisite: Решение Талдыкорганского городского маслихата Алматинской области от 21 декабря 2017 года № 149. Зарегистрировано Департаментом юстиции Алматинской области 3 января 2018 года № 4470
title:
  rus: О бюджетах сельских округов города Талдыкорган на 2018-2020 годы
  kaz: Талдықорған қаласының ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '154002000002'
version_date:
  kaz: 2018-04-23
  rus: 2018-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/117681/kaz/23.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117681/rus/23.04.2018
caused_by:
  code: '121708'
  requisite: Решение Талдыкорганского городского маслихата Алматинской области от 23 апреля 2018 года № 182. Зарегистрировано Департаментом юстиции Алматинской области 10 мая 2018 года № 4685
  title:
    rus: О внесении изменений в решение Талдыкорганского городского маслихата от 21 декабря 2017 года № 149 «О бюджетах сельских округов города Талдыкорган на 2018-2020 годы»
    kaz: Талдықорған қалалық мәслихатының 2017 жылғы 21 желтоқсандағы «Талдықорған қаласының ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы» № 149 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121708/rus
