act_code: '103171'
requisite: Решение аппарата акима Сарыбастауского сельского округа Кербулакского района Алматинской области от 20 мая 2016 года № 02. Зарегистрировано Департаментом юстиции Алматинской области 10 июня 2016 года № 3882. Утратило силу решением акима Сарыбастауского сельского округа Кербулакского района Алматинской области от 27 сентября 2016 года № 08
title:
  rus: Об установлении карантина на территории села Сарыбастау Сарыбастауского сельского округа
  kaz: Сарыбастау ауылдық округінің Сарыбастау ауылы аумағында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-20
approved_by:
- '154010011001'
version_date:
  kaz: 2016-05-20
  rus: 2016-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/103171/kaz/20.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103171/rus/20.05.2016
