act_code: '35767'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2007 жылғы 30 қазандағы № 2-8 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2007 жылы 14 қарашада № 2-5-49 тіркелген
title:
  rus: Алакөл ауданы Мәслихатының «Алакөл ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін әлеуметтік қамсыздандыру ұйымдарының әлеуметтік қызметкерлеріне біржолғы әлеуметтік көмек беру туралы»
  kaz: Алакөл ауданы Мәслихатының «Алакөл ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін әлеуметтік қамсыздандыру ұйымдарының әлеуметтік қызметкерлеріне біржолғы әлеуметтік көмек беру туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-30
approved_by:
- '154003000002'
version_date:
  kaz: 2007-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/35767/kaz/30.10.2007
