act_code: '228674'
requisite: Решение акима города Қонаев Алматинской области от 7 августа 2026 года № 8-17
title:
  rus: Об объявлении чрезвычайной ситуации природного характера объектового масштаба
  kaz: Табиғи сипаттағы объектілік ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-07
approved_by:
- '154020000003'
version_date:
  kaz: 2026-08-07
  rus: 2026-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/228674/kaz/07.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228674/rus/07.08.2026
