act_code: '207395'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 18 февраля 2025 года № VIII-38-173
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Енбекшиказахскому району
  kaz: Еңбекшіқазақ ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-18
approved_by:
- '154012000002'
version_date:
  kaz: 2025-02-18
  rus: 2025-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/207395/kaz/18.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207395/rus/18.02.2025
