act_code: '6388'
requisite: Решение Алматинского областного маслихата от 18 декабря 1998 года № 24-186. Зарегистрировано Управлением юстиции Алматинской области 5 марта 1999 года № 96. Утратило силу решением акима Алматинской области от 12 августа 2004 года № 8-62
title:
  rus: О порядке безвозмездной передачи бесхозных и незавершенных строительством объектов социального и хозяйственного назначения в собственность граждан, субъектам малого и среднего бизнеса на территории Алматинской области
  kaz: Алматы облысының аумағында шағын және орта бизнес субъектілеріне, азаматтардың иелігіне иесіз және құрылысы аяқталмаған әлеуметтік және шаруашылық салалары объектілерін өтеусіз беру тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-12-18
approved_by:
- '154000000002'
version_date:
  kaz: 1998-12-18
  rus: 1998-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/6388/kaz/18.12.1998
  rus: https://zan.gov.kz/client/#!/doc/6388/rus/18.12.1998
