act_code: '55554'
requisite: Алматы облысы Іле ауданы КазЦИК ауылдық округінің әкімінің 2010 жылғы 3 қарашадағы № 4 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 25 қарашада № 2-10-131 тіркелді
title:
  rus: КазЦИК елді мекеніндегі жаңа көшеге Атымтай Қисанов есімін беру туралы
  kaz: КазЦИК елді мекеніндегі жаңа көшеге Атымтай Қисанов есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '154017004002'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55554/kaz/03.11.2010
