act_code: '83264'
requisite: Решение Балхашского районного маслихата Алматинской области от 05 августа 2014 года № 36-152. Зарегистрировано Департаментом юстиции Алматинской области 03 сентября 2014 года № 2844. Утратило силу решением Балхашского районного маслихата Алматинской области от 30 марта 2015 года № 42-180
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Балхашского района
  kaz: Балқаш ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-08-05
approved_by:
- '154014000002'
version_date:
  kaz: 2014-08-05
  rus: 2014-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/83264/kaz/05.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83264/rus/05.08.2014
