act_code: '51544'
requisite: Алматы облысы Көксу ауданы Балпық би кенттік округі әкімінің 2010 жылғы 17 наурыздағы № 1 шешімі. Алматы облысының Әділет департаменті Көксу ауданының әділет басқармасында 2010 жылы 2 сәуірде № 2-14-92 тіркелді
title:
  rus: Балпық би кенттік округіне қарасты, Балпық би кентіндегі көшелердің атын өзгерту туралы
  kaz: Балпық би кенттік округіне қарасты, Балпық би кентіндегі көшелердің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-17
approved_by:
- '154007010002'
version_date:
  kaz: 2014-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/51544/kaz/31.12.2014
caused_by:
  code: '86928'
  requisite: Решение акима Балпыкского сельского округа Коксуского района Алматинской области от 31 декабря 2014 года № 4. Зарегистрировано Департаментом юстиции Алматинской области от 10 февраля 2015 года № 3038
  title:
    rus: О внесении изменений в решение акима поселкового округа Балпык би от 17 марта 2010 года № 1 «Об изменении наименований улиц в поселке Балпык би, относящегося к поселковому округу Балпык би»
    kaz: Балпық би кенттік округі әкімінің 2010 жылғы 17 наурыздағы «Балпық би кенттік округіне қарасты, Балпық би кентіндегі көшелердің атын өзгерту туралы» № 1 шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86928/rus
