act_code: '147388'
requisite: Решение акима Жетыгенского сельского округа Илийского района Алматинской области от 8 октября 2020 года № 6. Зарегистрировано Департаментом юстиции Алматинской области 12 октября 2020 года № 5707
title:
  rus: О переименовании улиц Жетыгенского сельского округа
  kaz: Жетіген ауылдық округінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-08
approved_by:
- '154017003002'
version_date:
  kaz: 2020-10-08
  rus: 2020-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/147388/kaz/08.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147388/rus/08.10.2020
