act_code: '50690'
requisite: Алматы облысы Ақсу ауданы әкімінің 2009 жылғы 25 желтоқсандағы № 3 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2010 жылы 12 ақпанда № 2-4-104 тіркелді. Күші жойылды - Алматы облысы Ақсу ауданы әкімінің 2010 жылғы 20 желтоқсандағы № 3 шешімімен
title:
  rus: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
  kaz: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '154011000003'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50690/kaz/25.12.2009
