act_code: '4437'
requisite: Решение акима Алматинской области от 19 мая 1999 года № 5-157. Зарегистрировано Управлением юстиции Алматинской области 20 сентября 1999 года № 120. Утратило силу решением акима Алматинской области от 24 августа 2004 года № 8-87
title:
  rus: О некоторых проблемах предприятий, производящих вино-водочную продукцию
  kaz: Арақ-шарап өнімдерін өндіретін кәсіпорындардың кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-18
approved_by:
- '154000000003'
version_date:
  kaz: 1999-05-18
  rus: 1999-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/4437/kaz/18.05.1999
  rus: https://zan.gov.kz/client/#!/doc/4437/rus/18.05.1999
