act_code: '19724'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2004 жылғы 16 сәуірдегі N 3-6-42 шешімі. Алматы облыстық Әділет департаментінде 2004 жылы 29 сәуірде N 1599 тіркелді. Күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2011 жылғы 08 желтоқсандағы N 4-54-338 шешімімен
title:
  rus: Панфилов аудандық мәслихаттың жұмыс тәртібін (регламент) бекіту туралы
  kaz: Панфилов аудандық мәслихаттың жұмыс тәртібін (регламент) бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-04-15
approved_by:
- '154004000002'
version_date:
  kaz: 2004-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/19724/kaz/15.04.2004
