act_code: '127163'
requisite: Решение акима Балпыкского сельского округа Каратальского района Алматинской области от 12 декабря 2018 года № 13. Зарегистрировано Департаментом юстиции Алматинской области 19 декабря 2018 года № 4964
title:
  rus: О снятии ограничительных мероприятий в селе Жанаталап в улицах Ильина, Кантбай Усенова отара № 2 Балпыкского сельского округа
  kaz: Балпық ауылдық округінің Жаңаталап ауылындағы Ильин, Қантбай Үсенов көшелерінің № 2 отарына шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '154009001002'
version_date:
  kaz: 2018-12-12
  rus: 2018-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127163/kaz/12.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127163/rus/12.12.2018
