act_code: '16177'
requisite: Решение маслихата Алматинской области от 30 мая 2003 года № 34-193. Зарегистрировано Управлением юстиции Алматинской области 10 июня 2003 года № 1191. Утратило силу решением маслихата Алматинской области от 21 декабря 2003 года № 13-89
title:
  rus: О региональной программе функционирования и развития языков на 2003-2004 годы
  kaz: Тілдерді қолдану мен дамытудың 2003-2004 жылдарға арналған
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-05-29
approved_by:
- '154000000002'
version_date:
  kaz: 2003-05-29
  rus: 2003-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/16177/kaz/29.05.2003
  rus: https://zan.gov.kz/client/#!/doc/16177/rus/29.05.2003
