act_code: '69526'
requisite: Решение маслихата Уйгурского района Алматинской области от 05 декабря 2012 года № 12-2. Зарегистрировано Департаментом юстиции Алматинской области 19 декабря 2012 года № 2249. Утратило силу решением маслихата Уйгурского района Алматинской области от 20 декабря 2013 года № 27-10
title:
  rus: О предоставлении подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам сфер здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Уйгурского района на 2013 год
  kaz: 2013 жылы Ұйғыр ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария салаларының мамандарына көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтiк қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-05
approved_by:
- '154008000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/69526/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/69526/rus/20.12.2013
