act_code: '192336'
requisite: Решение Балхашского районного маслихата Алматинской области от 27 декабря 2023 года № 15-50
title:
  rus: О решение Балхашского районного маслихата от 27 декабря 2023 года № 15-50 «О бюджете Балхашского района на 2024-2026 годы»
  kaz: Балқаш аудандық мәслихатының 2023 жылғы 27 желтоқсандағы № 15-50 «Балқаш ауданының 2024-2026 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '154014000002'
version_date:
  kaz: 2024-12-11
  rus: 2024-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/192336/kaz/11.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192336/rus/11.12.2024
caused_by:
  code: '204709'
  requisite: Решение Балхашского районного маслихата Алматинской области от 11 декабря 2024 года № 30-117
  title:
    rus: О внесении изменеий в решение Балхашского районного маслихата от 27 декабря 2023 года № 15-50 «О бюджете Балхашского района на 2024-2026 годы»
    kaz: Балқаш аудандық мәслихатының 2023 жылғы 27 желтоқсандағы № 15-50 «Балқаш ауданының 2024-2026 жылдарға арналған бюджетіне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/204709/rus
