act_code: '49558'
requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 26-181 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының Әділет басқармасында 2009 жылы 29 желтоқсанда 2-13-102 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 36-282 шешімімен
title:
  rus: Кербұлақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Кербұлақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154010000002'
version_date:
  kaz: 2010-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/49558/kaz/15.04.2010
caused_by:
  code: '52229'
  requisite: Алматы облысы Кербұлақ аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 28-213 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының Әділет басқармасында 2010 жылы 06 мамырда № 2-13-113 тіркелді. Күші жойылды - Алматы облысы Кербұлақ аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 36-282 шешімімен
  title:
    rus: Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсанындағы "Кербұлақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 26-181 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Кербұлақ аудандық мәслихатының 2009 жылғы 23 желтоқсанындағы "Кербұлақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" N 26-181 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52229/rus
