act_code: '126789'
requisite: Решение Кегенского районного маслихата Алматинской области от 23 ноября 2018 года № 10-35. Зарегистрировано Департаментом юстиции Алматинской области 29 ноября 2018 года № 4900. Утратило силу решением Кегенского районного маслихата Алматинской области от 19 октября 2023 года № 11-52
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Кегенского района
  kaz: Кеген ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-11-23
approved_by:
- '154021000002'
version_date:
  kaz: 2018-11-23
  rus: 2018-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/126789/kaz/23.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126789/rus/23.11.2018
