act_code: '81730'
requisite: Решение Текелийского городского маслихата Алматинской области от 04 июля 2014 года № 31-198. Зарегистрировано Департаментом юстиции Алматинской области 30 июля 2014 года № 2788. Утратило силу решением Текелийского городского маслихата Алматинской области от 02 августа 2016 года № 7-36
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по городу Текели
  kaz: Текелі қаласы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-04
approved_by:
- '154019000002'
version_date:
  kaz: 2014-07-04
  rus: 2014-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/81730/kaz/04.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81730/rus/04.07.2014
