act_code: '119940'
requisite: Решение Райымбекского районного маслихата Алматинской области от 16 февраля 2018 года № 31-150. Зарегистрировано Департаментом юстиции Алматинской области 6 марта 2018 года № 4536
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Райымбекскому району на 2018-2019 годы
  kaz: Райымбек ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-02-16
approved_by:
- '154016000002'
version_date:
  kaz: 2018-02-16
  rus: 2018-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/119940/kaz/16.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119940/rus/16.02.2018
