act_code: '53794'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 маусымдағы № 35-3 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 30 шілдеде № 2-19-104 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-7 шешімімен
title:
  rus: Ұйғыр ауданының ауылдық (селолық) жерлерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, мәдениет және спорт ұйымдарының қызметкерлеріне отын сатып алу үшін біржолғы әлеуметтік көмек беру туралы
  kaz: Ұйғыр ауданының ауылдық (селолық) жерлерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, мәдениет және спорт ұйымдарының қызметкерлеріне отын сатып алу үшін біржолғы әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-22
approved_by:
- '154008000002'
version_date:
  kaz: 2010-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/53794/kaz/22.06.2010
