act_code: '68501'
requisite: Решение акима Шолаккаргалинского сельского округа Жамбылского района Алматинской области от 17 октября 2012 года № 10-99. Зарегистрировано Департаментом юстиции Алматинской области 12 ноября 2012 года № 2166
title:
  rus: О присвоении наименований новым улицам в селе Касымбек Шолаккаргалинского сельского округа Жамбылского района
  kaz: Жамбыл ауданы, Шолаққарғалы селолық округіне қарасты Қасымбек ауылындағы жаңа көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-17
approved_by:
- '154018023002'
version_date:
  kaz: 2012-10-17
  rus: 2012-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/68501/kaz/17.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68501/rus/17.10.2012
