act_code: '138875'
requisite: Решение Каратальского районного маслихата Алматинской области от 9 января 2020 года № 66-238. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2020 года № 5409
title:
  rus: О бюджетах города Уштобе и сельских округов Каратальского района на 2020-2022 годы
  kaz: Қаратал ауданының Үштөбе қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154009000002'
version_date:
  kaz: 2020-12-14
  rus: 2020-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/138875/kaz/14.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138875/rus/14.12.2020
caused_by:
  code: '150277'
  requisite: Решение Каратальского районного маслихата Алматинской области от 14 декабря 2020 года № 82-281. Зарегистрировано Департаментом юстиции Алматинской области 22 декабря 2020 года № 5829
  title:
    rus: О внесении изменений в решение Каратальского районного маслихата от 9 января 2020 года № 66-238 «О бюджетах города Уштобе и сельских округов Каратальского района на 2020-2022 годы»
    kaz: Қаратал аудандық мәслихатының 2020 жылғы 9 қаңтардағы № 66-238 «Қаратал ауданының Үштөбе қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150277/rus
