act_code: '43756'
requisite: Алматы облысы Сарқан ауданы әкімінің 2009 жылғы 12 қаңтардағы N 1 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының әділет басқармасында 2009 жылғы 26 қаңтарда N 2-17-69 тіркелді. Күші жойылды - Алматы облысы Сарқан ауданы әкімдігінің 2011 жылғы 31 наурыздағы N 114 қаулысымен
title:
  rus: Ақылы қоғамдық жұмыстарды ұйымдастыру туралы
  kaz: Ақылы қоғамдық жұмыстарды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-12
approved_by:
- '154005000001'
version_date:
  kaz: 2009-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/43756/kaz/12.01.2009
