act_code: '56578'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 40-253 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 30 желтоқсанда № 2-4-124 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2012 жылғы 17 ақпандағы № 2-10 шешімімен
title:
  rus: Ақсу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Ақсу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '154011000002'
version_date:
  kaz: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56578/kaz/18.03.2011
caused_by:
  code: '57958'
  requisite: Алматы облысы Ақсу аудандық мәслихатының 2011 жылғы 18 наурыздағы № 44-269 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2011 жылы 31 наурызда № 2-4-130 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2012 жылғы 17 ақпандағы № 2-10 шешімімен
  title:
    rus: Ақсу аудандық мәслихатының 2010 жылғы 24 желтоқсандағы "Ақсу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" 40-253 нөмірлі шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Ақсу аудандық мәслихатының 2010 жылғы 24 желтоқсандағы "Ақсу ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" 40-253 нөмірлі шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57958/rus
