act_code: '97164'
requisite: Решение Сарканского районного маслихата Алматинской области от 22 декабря 2015 года № 62-322. Зарегистрировано Департаментом юстиции Алматинской области 30 декабря 2015 года № 3669. Утратило силу решением Сарканского районного маслихата Алматинской области от 9 июня 2017 года № 19-89
title:
  rus: О бюджете Сарканского района на 2016-2018 годы
  kaz: Сарқан ауданының 2016-2018 жылдарға арналаған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '154005000002'
version_date:
  kaz: 2016-02-03
  rus: 2016-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/97164/kaz/03.02.2016
  rus: https://zan.gov.kz/client/#!/doc/97164/rus/03.02.2016
caused_by:
  code: '99235'
  requisite: Решение Сарканского районного маслихата Алматинской области от 03 февраля 2016 года № 65-335. Зарегистрировано Департаментом юстиции Алматинской области 17 февраля 2016 года № 3727. Утратило силу решением Сарканского районного маслихата Алматинской области от 9 июня 2017 года № 19-89
  title:
    rus: О внесении изменений в решение Сарканского районного маслихата от 22 декабря 2015 года № 62-322 "О бюджете Сарканского района на 2016-2018 годы"
    kaz: Сарқан аудандық мәслихатының 2015 жылғы 22 желтоқсандағы "Сарқан ауданының 2016-2018 жылдарға арналған бюджеті туралы" № 62-322 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99235/rus
