act_code: '49790'
requisite: Алматы облысы Ақсу ауданы Молалы поселкелік округі әкімінің 2010 жылғы 10 қаңтардағы № 1 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 13 қаңтарда № 2-4-101 тіркелді
title:
  rus: Молалы ауылдық округі Ғали Орманов ауылындағы аты жоқ көшеге Ғали Орманов және Қараой разъезіндегі аты жоқ көшеге Қараой атындағы көше атауларын беру туралы
  kaz: Молалы ауылдық округі Ғали Орманов ауылындағы аты жоқ көшеге Ғали Орманов және Қараой разъезіндегі аты жоқ көшеге Қараой атындағы көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-10
approved_by:
- '154011015002'
version_date:
  kaz: 2010-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49790/kaz/26.12.2010
