act_code: '49790'
requisite: Алматы облысы Ақсу ауданы Молалы поселкелік округі әкімінің 2010 жылғы 10 қаңтардағы № 1 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 13 қаңтарда № 2-4-101 тіркелді
title:
  rus: Молалы ауылдық округі Ғали Орманов ауылындағы аты жоқ көшеге Ғали Орманов және Қараой разъезіндегі аты жоқ көшеге Қараой атындағы көше атауларын беру туралы
  kaz: Молалы ауылдық округі Ғали Орманов ауылындағы аты жоқ көшеге Ғали Орманов және Қараой разъезіндегі аты жоқ көшеге Қараой атындағы көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-10
approved_by:
- '154011015002'
version_date:
  kaz: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49790/kaz/26.12.2014
caused_by:
  code: '86615'
  requisite: Решение акима Молалинского сельского округа Аксуского района Алматинской области от 26 декабря 2014 года № 1. Зарегистрировано Департаментом юстиции Алматинской области 06 февраля 2015 года № 3028
  title:
    rus: О внесении изменений в решение акима  Молалинского поселкового округа  от 10 января 2010 года № 1  «О присвоении безымянной улице  в разъезде Караой наименования улицы  Караой и имени Гали Орманова  безымянной улице в селе Гали Орманова  Молалинского поселкового округа»
    kaz: Молалы поселкелік округі әкімінің  2010 жылғы 10 қаңтардағы «Молалы  поселкелік округі Ғали Орманов  ауылындағы аты жоқ көшеге  Ғали Орманов және Қараой резъезіндегі  аты жоқ көшеге Қараой атындағы  көше атауларын беру туралы»  № 1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86615/rus
