act_code: '79765'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 18 апреля 2014 года N 31-12. Зарегистрировано Департаментом юстиции Алматинской области 28 апреля 2014 года N 2684. Утратило силу решением маслихата Енбекшиказахского района Алматинской области от 30 мая 2014 года N 33-5
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Енбекшиказахскому району
  kaz: Еңбекшіқазақ ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-18
approved_by:
- '154012000002'
version_date:
  kaz: 2014-04-18
  rus: 2014-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/79765/kaz/18.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79765/rus/18.04.2014
