act_code: '138764'
requisite: Решение Жамбылского районного маслихата Алматинской области от 9 января 2020 года № 66-306. Зарегистрировано Департаментом юстиции Алматинской области 17 января 2020 года № 5405
title:
  rus: «О бюджетах сельских округов Жамбылского района на 2020-2022 годы»
  kaz: Жамбыл ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154018000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/138764/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138764/rus/15.12.2020
caused_by:
  code: '150121'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 15 декабря 2020 года № 80-361. Зарегистрировано Департаментом юстиции Алматинской области 22 декабря 2020 года № 5823
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 9 января 2020 года № 66-306 «О бюджетах сельских округов Жамбылского района на 2020-2022 годы»
    kaz: Жамбыл аудандық мәслихатының 2020 жылғы 9 қаңтардағы № 66-306 «Жамбыл ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150121/rus
