act_code: '28035'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2006 жылғы 6 мамырдағы № 32-169 қаулысы. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2006 жылы 26 мамырда № 2-4-27 тіркелген
title:
  rus: Ақсу ауданы бойынша ауылдық (селолық) жерлерде тұратын және жұмыс істейтін мемлекеттік білім беру ұйымдарының педагог қызметкерлеріне отын сатып алуға бюджет қаражаты есебінен әлеуметтік көмек беру туралы
  kaz: Ақсу ауданы бойынша ауылдық (селолық) жерлерде тұратын және жұмыс істейтін мемлекеттік білім беру ұйымдарының педагог қызметкерлеріне отын сатып алуға бюджет қаражаты есебінен әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-06
approved_by:
- '154011000002'
version_date:
  kaz: 2006-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/28035/kaz/06.05.2006
