act_code: '80692'
requisite: Решение акима Талдыбулакского сельского округа Кербулакского района Алматинской области от 02 июня 2014 года № 9. Зарегистрировано Департаментом юстиции Алматинской области 10 июня 2014 года № 2745. Утратило силу решением акима Талдыбулакского сельского округа Кербулакского района Алматинской области от 26 сентября 2014 года № 12
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізе отырып, карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-02
approved_by:
- '154010005001'
version_date:
  kaz: 2014-06-02
  rus: 2014-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/80692/kaz/02.06.2014
  rus: https://zan.gov.kz/client/#!/doc/80692/rus/02.06.2014
