act_code: '55451'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2010 жылғы 21 қазандағы № 30-3 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 10 қарашада № 2-5-131 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2012 жылғы 09 маусымдағы № 5-5 шешімімен
title:
  rus: '"Алакөл ауданының Құрметті азаматы" атағын беру Ережесін бекіту туралы'
  kaz: '"Алакөл ауданының Құрметті азаматы" атағын беру Ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-21
approved_by:
- '154003000002'
version_date:
  kaz: 2010-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/55451/kaz/21.10.2010
