act_code: '107671'
requisite: Решение Текелийского городского маслихата Алматинской области от 27 октября 2016 года № 8-44. Зарегистрировано Департаментом юстиции Алматинской области 23 ноября 2016 года № 4015. Утратило силу решением Текелийского городского маслихата Алматинской области от 26 июня 2018 года № 26-167
title:
  rus: О повышении ставок земельного налога по городу Текели
  kaz: Текелі қаласы бойынша жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-27
approved_by:
- '154019000002'
version_date:
  kaz: 2016-10-27
  rus: 2016-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/107671/kaz/27.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107671/rus/27.10.2016
