act_code: '68500'
requisite: Решение маслихата Уйгурского района Алматинской области от 02 октября 2012 года № 10-2. Зарегистрировано Департаментом юстиции Алматинской области 09 ноября 2012 года № 2165. Утратило силу решением Уйгурского районного маслихата Алматинской области от 17 ноября 2021 года № 7-15-72
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Уйгурского района
  kaz: Ұйғыр ауданының елді мекендеріндегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-02
approved_by:
- '154008000002'
version_date:
  kaz: 2012-10-02
  rus: 2012-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/68500/kaz/02.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68500/rus/02.10.2012
