act_code: '95054'
requisite: Решение Алакольского районного маслихата Алматинской области от 21 сентября 2015 года № 53-2. Зарегистрировано Департаментом юстиции Алматинской области 28 октября 2015 года № 3504. Утратило силу решением Алакольского районного маслихата Алматинской области от 01.04.2016 № 2-3
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Алакольскому району
  kaz: Алакөл ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-21
approved_by:
- '154003000002'
version_date:
  kaz: 2015-09-21
  rus: 2015-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/95054/kaz/21.09.2015
  rus: https://zan.gov.kz/client/#!/doc/95054/rus/21.09.2015
