act_code: '46760'
requisite: Алматы облысы Көксу аудандық мәслихатының 2009 жылғы 24 маусымдағы № 27-2 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2009 жылы 8 шілдеде № 2-14-76 тіркелді. Күші жойылды - Алматы облысы Көксу аудандық мәслихатының 2010 жылғы 29 шілдедегі № 42-5 шешімімен
title:
  rus: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
  kaz: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-24
approved_by:
- '154007000002'
version_date:
  kaz: 2009-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46760/kaz/24.06.2009
