act_code: '43751'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 17-6 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының әділет басқармасында 2009 жылғы 26 қаңтарда № 2-19-70 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 05 ақпандағы № 31-6 шешімімен
title:
  rus: Ұйғыр ауданында табысы аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
  kaz: Ұйғыр ауданында табысы аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '154008000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43751/kaz/19.12.2008
