act_code: '52856'
requisite: Алматы облысы Еңбекшіқазақ ауданы Жаңашар селолық округі әкімінің 2010 жылғы 05 мамырдағы № 05-14 шешімі. Алматы облысы Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 27 мамырда № 2-8-149 тіркелді
title:
  rus: Жаңашар селолық округіндегі Жаңашар ауылының Майская көшесін Игібай Ноқабаев атындағы көше, Молодежная көшесін Мырзалы Баекешов атындағы көше, Космос ауылындағы Молодежная көшесін Омархан Рүстембеков атындағы көше деп атауларын өзгерту туралы
  kaz: Жаңашар селолық округіндегі Жаңашар ауылының Майская көшесін Игібай Ноқабаев атындағы көше, Молодежная көшесін Мырзалы Баекешов атындағы көше, Космос ауылындағы Молодежная көшесін Омархан Рүстембеков атындағы көше деп атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-05
approved_by:
- '154012007002'
version_date:
  kaz: 2010-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/52856/kaz/05.05.2010
