act_code: '15427'
requisite: Алматы облыстық Мәслихатының 2003 жылғы 20 наурыздағы № 33-181 шешімі. Алматы облыстық Әділет басқармасында 2003 жылғы 17 сәуірде № 1098 тіркелді
title:
  rus: Алматы облыстық Әдiлет басқармасында 2003 жылғы 9-қаңтарда 971 нөмiрiмен тiркелген Алматы облыстық Мәслихатының 2002 жылғы 26 желтоқсандағы "Алматы облысының 2003 жылға арналған облыстық бюджетi туралы" N 31-160 шешiмiне өзгерiстер енгiзу туралы
  kaz: Алматы облыстық Әдiлет басқармасында 2003 жылғы 9-қаңтарда 971 нөмiрiмен тiркелген Алматы облыстық Мәслихатының 2002 жылғы 26 желтоқсандағы "Алматы облысының 2003 жылға арналған облыстық бюджетi туралы" N 31-160 шешiмiне өзгерiстер енгiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-20
approved_by:
- '154000000002'
version_date:
  kaz: 2003-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/15427/kaz/20.03.2003
