act_code: '192255'
requisite: Решение маслихата города Қонаев Алматинской области от 29 декабря 2023 года № 17-52
title:
  rus: О бюджетах сельских округов города Қонаев на 2024-2026 годы
  kaz: Қонаев қаласының ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '154020000002'
version_date:
  kaz: 2024-07-19
  rus: 2024-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/192255/kaz/19.07.2024
  rus: https://zan.gov.kz/client/#!/doc/192255/rus/19.07.2024
caused_by:
  code: '199055'
  requisite: Решение маслихата города Қонаев Алматинской области от 19 июля 2024 года № 29-100
  title:
    rus: О внесении изменений в решение маслихата города Қонаев от 29 декабря 2023 года № 17-52 «О бюджетах сельских округов города Қонаев на 2024-2026 годы»
    kaz: Қонаев қаласы мәслихатының 2023 жылғы 29 желтоқсандағы «Қонаев қаласының ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы» № 17-52 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199055/rus
