act_code: '52986'
requisite: Алматы облысы Талғар ауданының әкімінің 2010 жылғы 30 сәуірдегі № 04-93 шешімі. Алматы облысы Талғар ауданының Әділет басқармасында 2010 жылғы 7 маусымда № 2-18-105 тіркелді. Күші жойылды - Алматы облысы Талғар ауданы әкімінің 2010 жылғы 31 желтоқсандағы № 12-321 шешімімен
title:
  rus: Талғар ауданы бойынша 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуді ұйымдастыру және қамтамасыз ету туралы
  kaz: Талғар ауданы бойынша 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-30
approved_by:
- '154013000001'
version_date:
  kaz: 2010-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/52986/kaz/30.04.2010
