act_code: '207487'
requisite: Решение маслихата Алматинской области от 25 февраля 2025 года № 33-180. Зарегистрировано Департаментом юстиции Алматинской области 26 февраля 2025 года № 6217-05. Утратило силу решением Алматинского областного маслихата от 4 сентября 2026 года № 54-316 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин Алматинской области (города, района)
  kaz: Алматы облысының (қаласының, ауданының) құрметті азаматы атағын беру Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-25
approved_by:
- '154000000002'
version_date:
  kaz: 2025-02-25
  rus: 2025-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/207487/kaz/25.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207487/rus/25.02.2025
