act_code: '111030'
requisite: Решение Кербулакского районного маслихата Алматинской области 27 февраля 2017 года № 12-76. Зарегистрировано Департаментом юстиции Алматинской области 28 марта 2017 года № 4154. Утратило силу решением Кербулакского районного маслихата Алматинской области от 15 марта 2018 года № 28-152
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Кербулакского районного маслихата
  kaz: Кербұлақ аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2017-02-27
approved_by:
- '154010000002'
version_date:
  kaz: 2017-02-27
  rus: 2017-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/111030/kaz/27.02.2017
  rus: https://zan.gov.kz/client/#!/doc/111030/rus/27.02.2017
