act_code: '38089'
requisite: Алматы облысы Жамбыл аудандық мәслихатының 2008 жылғы 21 ақпандағы № 7-38 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2008 жылғы 29 ақпанда № 2-7-57 тіркелді. Күші жойылды - Алматы облысы Жамбыл аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 19-80 шешімімен
title:
  rus: Жамбыл ауданында өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
  kaz: Жамбыл ауданында өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі мен мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-21
approved_by:
- '154018000002'
version_date:
  kaz: 2008-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/38089/kaz/21.02.2008
