act_code: '56942'
requisite: Решение малихата Алматинской области от 14 декабря 2010 года за № 39-228. Зарегистрировано департаментом юстиции Алматинской области от 18 января 2011 года № 2065. Утратило силу - Решением маслихата Алматинской области от 24 октября 2012 года № 9-56
title:
  rus: Об утверждении Правил присвоения звания "Почетный гражданин Алматинской области"
  kaz: '"Алматы облысының құрметті азаматы" атағын беру Ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '154000000002'
version_date:
  kaz: 2010-12-14
  rus: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56942/kaz/14.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56942/rus/14.12.2010
