act_code: '52459'
requisite: Алматы облысы Талғар ауданы Гүлдала ауылдық округінің әкімінің 2010 жылғы 13 сәуірдегі № 32 шешімі. Алматы облысы Талғар ауданының Әділет басқармасында 2010 жылғы 13 мамырда № 2-18-103 тіркелді
title:
  rus: Гүлдала ауылдық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру мен елді мекендердегі көше атауларын өзгерту туралы
  kaz: Гүлдала ауылдық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру мен елді мекендердегі көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-13
approved_by:
- '154013008001'
version_date:
  kaz: 2010-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/52459/kaz/13.04.2010
