act_code: '148490'
requisite: Решение акима Панфиловского сельского округа Талгарского района Алматинской области от 9 ноября 2020 года № 12. Зарегистрировано Департаментом юстиции Алматинской области 13 ноября 2020 года № 5748
title:
  rus: О присвоении наименований новым улицам и переименований улиц Панфиловского сельского округа
  kaz: Панфилов ауылдық округінің жаңа көшелеріне атау беру және көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-09
approved_by:
- '154013009002'
version_date:
  kaz: 2020-11-09
  rus: 2020-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/148490/kaz/09.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148490/rus/09.11.2020
