act_code: '43439'
requisite: Алматы облысы Талғар аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 15-87 шешімі. Алматы облысының Әділет департаменті Талғар ауданының Әділет басқармасында 2009 жылы 9 қаңтарда № 2-18-79 тіркелді. Күші жойылды - Алматы облысы Талғар аудандық мәслихатының 2010 жылғы 11 ақпандағы № 28-172 шешімімен
title:
  rus: Талғар ауданының 2009 жылға арналған бюджеті туралы
  kaz: Талғар ауданының 2009 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '154013000002'
version_date:
  kaz: 2010-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/43439/kaz/11.02.2010
