act_code: '57251'
requisite: Алматы облысы Текелі қалалық мәслихатының 2010 жылғы 20 желтоқсандағы № 27-202 шешімі. Алматы облысының Әділет департаменті Текелі қаласының Әділет басқармасында 2011 жылы 27 қаңтарда № 2-3-90 тіркелді. Қолданылу мерзімінің аяқталуына байланысты шешімнің күші жойылды - Алматы облысы Текелі қалалық мәслихатының 2013 жылғы 19 шілдедегі № 19-121 шешімімен
title:
  rus: Текелі қаласының мемлекеттік коммуналдық тұрғын үй қорынан тұрғын үйлерді жекешелендіру қағидасын бекіту туралы
  kaz: Текелі қаласының мемлекеттік коммуналдық тұрғын үй қорынан тұрғын үйлерді жекешелендіру қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '154019000002'
version_date:
  kaz: 2011-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/57251/kaz/08.12.2011
caused_by:
  code: '62931'
  requisite: Решение маслихата города Текели Алматинской области от 08 декабря 2011 года № 38-300. Зарегистрировано Управлением юстиции города Текели Департамента юстиции Алматинской области 13 января 2012 года № 2-3-102. Утратило силу решением маслихата города Текели Алматинской области от 20 декабря 2013 года № 25-162
  title:
    rus: О внесении изменений в решение Текелийского городского маслихата  от 20 декабря 2010 года № 27-202 "Об утверждении Правил приватизации жилищ из государственного коммунального жилищного фонда города Текели"
    kaz: Текелі қалалық мәслихатының 2010 жылғы 20 желтоқсандағы N 27-202 "Текелі қаласының мемлекеттік коммуналдық тұрғын үй қорынан ұрғын үйлерді жекешелендіру қағидасын бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/62931/rus
