act_code: '182135'
requisite: Решение акима Ащибулакского сельского округа Илийского района Алматинской области от 25 мая 2023 года № 3. Зарегистрировано Департаментом юстиции Алматинской области 26 мая 2023 года № 6006-05
title:
  rus: О присвоении наименования и переименовании улиц ПКСТ «Ақжол Садовод» Ащибулакского сельского округа
  kaz: Ащыбұлақ ауылдық округінің «Ақжол Садовод» ТКБС-нің көшесіне атау беру және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-25
approved_by:
- '154017001002'
version_date:
  kaz: 2023-05-25
  rus: 2023-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/182135/kaz/25.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182135/rus/25.05.2023
