act_code: '15236'
requisite: Решение акима Алматинской области от 1 апреля 2003 года № 4-70. Зарегистрировано Управлением юстиции Алматинской области 15 апреля 2003 года № 1090. Утратило силу решением акима Алматинской области от 1 апреля 2004 года № 4-37
title:
  rus: Об очередном призыве граждан 1976 -1985 годов рождения на срочную военную службу в апреле-июне и октябре-декабре 2003 года в Вооруженные Силы Республики Казахстан
  kaz: Қазақстан Республикасының Қарулы Күштері қатарындағы мерзімді әскери қызметке 2003 жылғы сәуір-маусым және қазан-желтоқсан айларында 1976-1985 жылдары туылған азаматтарды кезекті шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-31
approved_by:
- '154000000003'
version_date:
  kaz: 2003-03-31
  rus: 2003-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/15236/kaz/31.03.2003
  rus: https://zan.gov.kz/client/#!/doc/15236/rus/31.03.2003
