act_code: '53138'
requisite: Алматы облысы Алакөл ауданы Достық ауылдық округі әкімінің 2010 жылғы 07 маусымдағы № 09 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 10 маусымда № 2-5-104 тіркелді
title:
  rus: Достық ауылдық округіндегі атаусыз көшелерге ат қою туралы
  kaz: Достық ауылдық округіндегі атаусыз көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-07
approved_by:
- '154003006001'
version_date:
  kaz: 2015-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/53138/kaz/09.01.2015
caused_by:
  code: '86522'
  requisite: Решение акима Достыкского сельского округа Алакольского района Алматинской области от 9 января 2015 года № 2. Зарегистрировано Департаментом юстиции Алматинской области 9 февраля 2015 года № 3034
  title:
    rus: О внесении изменений в решение акима Достыкского поселкового округа от 7 июня 2010 года № 9 «О присвоении наименований безымянным улицам Достыкского поселкового округа»
    kaz: Достық кенттік округі әкімінің 2010 жылғы 7 маусымдағы «Достық кенттік округіндегі атаусыз көшелерге ат қою туралы» № 9 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86522/rus
