act_code: '49822'
requisite: Алматы облысы Қапшағай қаласы әкімінің 2009 жылғы 22 желтоқсандағы № 12-9 шешімі. Алматы облысы Қапшағай қаласының Әділет басқармасында 2010 жылғы 12 қаңтарда № 2-2-98 тіркелді
title:
  rus: 1993 жылы туылған азаматтардың әскерге шақыру учаскелерінде тіркеуге алу және жастарды әскери қызметке шақыруды ұйымдастыру туралы
  kaz: 1993 жылы туылған азаматтардың әскерге шақыру учаскелерінде тіркеуге алу және жастарды әскери қызметке шақыруды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '154020000001'
version_date:
  kaz: 2009-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49822/kaz/22.12.2009
