act_code: '126052'
requisite: Решение Каратальского районного маслихата Алматинской области от 21 ноября 2018 года № 44-170. Зарегистрировано Департаментом юстиции Алматинской области 23 ноября 2018 года № 4873. Утратило силу решением Каратальского районного маслихата Алматинской области от 23 апреля 2021 года № 7-30
title:
  rus: О повышении ставок земельного налога по Каратальскому району
  kaz: Қаратал ауданы бойынша жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-21
approved_by:
- '154009000002'
version_date:
  kaz: 2018-11-21
  rus: 2018-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/126052/kaz/21.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126052/rus/21.11.2018
