act_code: '49640'
requisite: Алматы облысы Іле аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 28-99 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда № 2-10-104 тіркелді
title:
  rus: Іле ауданының 2010 жылға арналған аудандық бюджеті туралы
  kaz: Іле ауданының 2010 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154017000002'
version_date:
  kaz: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/49640/kaz/06.12.2010
caused_by:
  code: '56094'
  requisite: Алматы облысы Іле аудандық мәслихатының 2010 жылғы 6 желтоқсандағы № 38-155 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 20 желтоқсанда № 2-10-134 тіркелді
  title:
    rus: Іле ауданы мәслихатының 2009 жылдың 23 желтоқсандағы № 28-99 санды "Іле ауданының 2010-2012 жылдарының бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Іле ауданы мәслихатының 2009 жылдың 23 желтоқсандағы № 28-99 санды "Іле ауданының 2010-2012 жылдарының бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56094/rus
