act_code: '49640'
requisite: Алматы облысы Іле аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 28-99 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда № 2-10-104 тіркелді
title:
  rus: Іле ауданының 2010 жылға арналған аудандық бюджеті туралы
  kaz: Іле ауданының 2010 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154017000002'
version_date:
  kaz: 2010-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49640/kaz/23.06.2010
caused_by:
  code: '53460'
  requisite: Алматы облысы Іле аудандық мәслихатының 2010 жылғы 23 маусымдағы № 33-132 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 29 маусымда № 2-10-122 тіркелді
  title:
    rus: 2009 жылдың 23 желтоқсандағы № 28-99 "Іле ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылдың 23 желтоқсандағы № 28-99 "Іле ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53460/rus
