act_code: '76758'
requisite: Решение маслихата Аксуского района Алматинской области от 21 декабря 2013 года № 26-165. Зарегистрировано Департаментом юстиции Алматинской области 30 декабря 2013 года № 2541
title:
  rus: О районном бюджете Аксуского района на 2014-2016 годы
  kaz: Ақсу ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-21
approved_by:
- '154011000002'
version_date:
  kaz: 2014-02-10
  rus: 2014-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/76758/kaz/10.02.2014
  rus: https://zan.gov.kz/client/#!/doc/76758/rus/10.02.2014
caused_by:
  code: '77636'
  requisite: Решение маслихата Аксуского района Алматинской области от 10 февраля 2014 года № 27-172. Зарегистрировано Департаментом юстиции Алматинской области 19 февраля 2014 года № 2586. Утратило силу решением Аксуского районного маслихата Алматинской области от 17 марта 2017 года № 12-57
  title:
    rus: О внесении изменении в решение Аксуского районного маслихата от 21 декабря 2013 года N 26-165 "О районном бюджете Аксуского района на 2014-2016 годы"
    kaz: Ақсу аудандық мәслихатының 2013 жылғы 21 желтоқсандағы "Ақсу ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы" N 26-165 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/77636/rus
