act_code: '121919'
requisite: Решение Каратальского районного маслихата Алматинской области от 5 мая 2018 года № 34-146. Зарегистрировано Департаментом юстиции Алматинской области 22 мая 2018 года № 4713.  Утратило силу решением Каратальского районного маслихата Алматинской области от 21 ноября 2018 года № 44-169
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Каратальскому району на 2018-2019 годы
  kaz: Қаратал ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-05-05
approved_by:
- '154009000002'
version_date:
  kaz: 2018-05-05
  rus: 2018-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/121919/kaz/05.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121919/rus/05.05.2018
