act_code: '78208'
requisite: Решение маслихата города Капшагай Алматинской области от 26 февраля 2014 года N 29-128. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2014 года N 2634. Утратило силу решением Капшагайского городского маслихата Алматинской области от 19 мая 2016 года № 4-23
title:
  rus: Об утверждении Регламента Капшагайского городского маслихата
  kaz: Қапшағай қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-26
approved_by:
- '154020000002'
version_date:
  kaz: 2014-02-26
  rus: 2014-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/78208/kaz/26.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78208/rus/26.02.2014
