act_code: '121834'
requisite: Решение Талгарского районного маслихата Алматинской области от 28 марта 2018 года № 27-137. Зарегистрировано Департаментом юстиции Алматинской области 24 апреля 2018 года № 4659
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Талгарскому району на 2018-2019 годы
  kaz: Талғар ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-03-28
approved_by:
- '154013000002'
version_date:
  kaz: 2018-03-28
  rus: 2018-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/121834/kaz/28.03.2018
  rus: https://zan.gov.kz/client/#!/doc/121834/rus/28.03.2018
