act_code: '56519'
requisite: Алматы облысы Еңбекшіқазақ ауданы әкімінің 2010 жылғы 03 желтоқсандағы № 12-163 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2011 жылы 07 қаңтарда № 2-8-168 тіркелді. Күші жойылды - Алматы облысы Еңбекшіқазақ ауданы әкімінің 2011 жылғы 13 маусымдағы № 6-51 шешімімен
title:
  rus: 1994 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-03
approved_by:
- '154012000003'
version_date:
  kaz: 2010-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/56519/kaz/03.12.2010
