act_code: '808'
requisite: Решение акима Алматинской области от 24 февраля 1998 года № 2-75. Зарегистрировано Управлением юстиции Алматинской области 26 июня 1998 года № 10. Утратило силу решением акима Алматинской области от 29 сентября 2004 года № 9-96
title:
  rus: О дальнейшем углублении реформ на селе и финансовом оздоровлении сельской экономики
  kaz: Селодағы реформаларды бұдан былай тереңдету және село экономикасын қаржылай сауықтыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-24
approved_by:
- '154000000003'
version_date:
  kaz: 1998-02-24
  rus: 1998-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/808/kaz/24.02.1998
  rus: https://zan.gov.kz/client/#!/doc/808/rus/24.02.1998
