act_code: '165696'
requisite: Решение Аксуского районного маслихата Алматинской области от 31 января 2022 года № 17-70. Утратило силу решением Аксуского районного маслихата области Жетісу от 14 апреля 2023 года № 3-12
title:
  rus: Об утверждении Регламента Аксуского районного маслихата
  kaz: Ақсу аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2022-01-31
approved_by:
- '154011000002'
version_date:
  kaz: 2022-01-31
  rus: 2022-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/165696/kaz/31.01.2022
  rus: https://zan.gov.kz/client/#!/doc/165696/rus/31.01.2022
