act_code: '46407'
requisite: Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 7 мамырдағы № 24-98 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының әділет басқармасында 2009 жылы 10 маусымда № 2-12-107 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2014 жылғы 03 сәуірдегі № 29-125 шешімімен
title:
  rus: Қаратал ауданы аумағында бекітілген базалық ставкалар шегінде бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Қаратал ауданы аумағында бекітілген базалық ставкалар шегінде бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-07
approved_by:
- '154009000002'
version_date:
  kaz: 2009-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/46407/kaz/07.05.2009
