act_code: '227513'
requisite: Решение акима сельского округа Өтеген батыр Илийского района Алматинской области от 07 июля 2026 года № 2-р
title:
  rus: О присвоении наименований улицам в микрорайоне Қуат сельского округа Өтеген батыр
  kaz: Өтеген батыр ауылдық округінің Қуат ықшам ауданындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-07
approved_by:
- '154017011002'
version_date:
  kaz: 2026-07-07
  rus: 2026-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/227513/kaz/07.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227513/rus/07.07.2026
