act_code: '141494'
requisite: Решение акима Сапакского сельского округа Алакольского района Алматинской области от 9 апреля 2020 года № 3. Зарегистрировано Департаментом юстиции Алматинской области 13 апреля 2020 года № 5461
title:
  rus: О присвоении наименования новой улице в селе Бибакан Сапакского сельского округа
  kaz: Сапақ ауылдық округінің Бибақан ауылындағы жаңа көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-09
approved_by:
- '154003005002'
version_date:
  kaz: 2020-04-09
  rus: 2020-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/141494/kaz/09.04.2020
  rus: https://zan.gov.kz/client/#!/doc/141494/rus/09.04.2020
