act_code: '217874'
requisite: Решение акима Талгарского района Алматинской области от 21 ноября 2025 года № 11-07
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера объектового масштаба
  kaz: Объектілік масштабтағы техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-21
approved_by:
- '154013000003'
version_date:
  kaz: 2025-11-21
  rus: 2025-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/217874/kaz/21.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217874/rus/21.11.2025
