act_code: '11441'
requisite: Решение Алматинского областного маслихата от 5 февраля 2002 года № 18-123. Зарегистрировано Управлением юстиции Алматинской области 25 февраля 2002 года № 633. Утратило силу решением маслихата Алматинской области от 1 июля 2005 года № 18-135
title:
  rus: Об областном бюджете Алматинской области на 2002 год
  kaz: Алматы облысының 2002 жылға арналған облыстық бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-05
approved_by:
- '154000000002'
version_date:
  kaz: 2002-02-05
  rus: 2002-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/11441/kaz/05.02.2002
  rus: https://zan.gov.kz/client/#!/doc/11441/rus/05.02.2002
