act_code: '37504'
requisite: Алматы облысы Сарқан аудандық мәслихатының 2008 жылғы 26 қаңтардағы № 8-45 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының әділет басқармасында 2008 жылы 5 ақпанда № 2-17-55 тіркелді. Күші жойылды - Алматы облысы Сарқан аудандық мәслихатының 2010 жылғы 18 наурыздағы № 32-205 шешімімен
title:
  rus: Өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарына) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
  kaz: Өздері жылытатын үйде тұратын тұрмысы төмен отбасыларына (азаматтарына) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-26
approved_by:
- '154005000002'
version_date:
  kaz: 2008-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/37504/kaz/26.01.2008
