act_code: '226620'
requisite: Решение акима Казахстанского сельского округа Енбекшиказахского района Алматинской области от 02 июня 2026 года № 03
title:
  rus: О переименовании улиц в села Ж. Кайыпова и селе Казахстан Казахстанского сельского округа
  kaz: Қазақстан ауылдық округіне қарасты Ж.Қайыпов ауылы және Қазақстан ауылы көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-02
approved_by:
- '154012009002'
version_date:
  kaz: 2026-06-02
  rus: 2026-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/226620/kaz/02.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226620/rus/02.06.2026
