act_code: '68953'
requisite: Решение маслихата Жамбылского района Алматинской области от 05 ноября 2012 года № 11-84. Зарегистрировано Департаментом юстиции Алматинской области 05 декабря 2012 года № 2208. Утратило силу решением Жамбылского районного маслихата Алматинской области от 21 апреля 2021 года № 5-33
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Жамбылского района
  kaz: Жамбыл ауданының елді мекендеріндегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-05
approved_by:
- '154018000002'
version_date:
  kaz: 2012-11-05
  rus: 2012-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/68953/kaz/05.11.2012
  rus: https://zan.gov.kz/client/#!/doc/68953/rus/05.11.2012
