act_code: '138233'
requisite: Решение Кербулакского районного маслихата Алматинской области от 27 декабря 2019 года № 53-305. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2020 года № 5387
title:
  rus: О бюджете Кербулакского района на 2020-2022 годы
  kaz: Кербұлақ ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154010000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138233/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138233/rus/27.12.2019
