act_code: '49823'
requisite: Алматы облысы Қапшағай қалалық мәслихатының 2009 жылғы 23 желтоқсандағы N 174-33 шешімі. Алматы облысы Қапшағай қаласының Әділет басқармасында 2010 жылғы 14 қаңтарда N 2-2-99 тіркелді
title:
  rus: Қапшағай қаласы, Заречный және Шеңгелді ауылдық округтерінің жерлеріне базалық ставкаларын белгілеу туралы
  kaz: Қапшағай қаласы, Заречный және Шеңгелді ауылдық округтерінің жерлеріне базалық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154020000002'
version_date:
  kaz: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49823/kaz/23.12.2009
