act_code: '176188'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 26 декабря 2022 года № 30-147
title:
  rus: О бюджете Енбекшиказахского района на 2023-2025 годы
  kaz: Еңбекшіқазақ ауданының 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '154012000002'
version_date:
  kaz: 2023-07-21
  rus: 2023-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/176188/kaz/21.07.2023
  rus: https://zan.gov.kz/client/#!/doc/176188/rus/21.07.2023
caused_by:
  code: '184482'
  requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 21 июля 2023 года № 30-147
  title:
    rus: О внесении изменений в решение Енбекшиказахского районного маслихата от 26 декабря 2022 года № VIII-30-147 «О бюджете Енбекшиказахского района на 2023-2025 годы»
    kaz: Еңбекшіқазақ аудандық мәслихатының 2022 жылғы 26 желтоқсандағы № VIII-30-147 «Еңбекшіқазақ ауданының 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184482/rus
