act_code: '176825'
requisite: Решение Талгарского районного маслихата Алматинской области от 29 декабря 2022 года № 39-115
title:
  rus: О бюджетах города Талгар и сельских округов Талгарского района на 2023-2025 годы
  kaz: Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '154013000002'
version_date:
  kaz: 2023-08-10
  rus: 2023-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/176825/kaz/10.08.2023
  rus: https://zan.gov.kz/client/#!/doc/176825/rus/10.08.2023
caused_by:
  code: '185107'
  requisite: Решение Талгарского районного маслихата Алматинской области от 10 августа 2023 года № 8-35
  title:
    rus: О внесении изменений в решение Талгарского районного маслихата от 29 декабря 2022 года № 39-115  «О бюджетах города Талгар и сельских округов Талгарского района на 2023-2025 годы»
    kaz: Талғар аудандық мәслихатының 2022 жылғы 29 желтоқсандағы № 39-115 «Талғар ауданының Талғар қаласы мен ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185107/rus
