act_code: '52550'
requisite: Алматы облысы Панфилов ауданы Үшарал ауылдық округі әкімінің 2010 жылғы 07 мамырдағы № 48 шешімі. Алматы облысының Әділет департаменті Панфилов ауданының Әділет басқармасында 2010 жылғы 13 мамырда № 2-16-112 тіркелді
title:
  rus: Үшарал ауылындағы аты жоқ көшеге Саурамбаев Нүсіпбек Қыбырайұлының атын беру туралы
  kaz: Үшарал ауылындағы аты жоқ көшеге Саурамбаев Нүсіпбек Қыбырайұлының атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-07
approved_by:
- '154004012001'
version_date:
  kaz: 2010-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/52550/kaz/07.05.2010
