act_code: '55880'
requisite: Алматы облысы Райымбек ауданы Кеген селолық округінің әкімінің 2010 жылғы 19 қарашадағы N 11-135 шешімі. Алматы облысы Райымбек ауданының Әділет басқармасында 2010 жылғы 13 желтоқсанда N 2-15-94 тіркелді
title:
  rus: Кеген селолық округінің Жаңа Дархан көшесін Игібаев Өміржанның атауына өзгерту туралы
  kaz: Кеген селолық округінің Жаңа Дархан көшесін Игібаев Өміржанның атауына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-19
approved_by:
- '154016023002'
version_date:
  kaz: 2010-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/55880/kaz/19.11.2010
