act_code: '58079'
requisite: Решение Карасайского районного маслихата от 10 марта 2011 года ю 51-5. Зарегистрировано Карасайским районным управлением юстиции от 7 апреля 2011 года за № 2-11-101. Утратило силу решением Карасайского районного маслихата Алматинской области от 26 февраля 2018 года № 25-9
title:
  rus: Об исчислении фиксированного налога в пределах утвержденной базовой ставки по Карасайскому району
  kaz: Қарасай ауданы аумағында бекітілген базалық ставкалар шегінде бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-10
approved_by:
- '154015000002'
version_date:
  kaz: 2011-03-10
  rus: 2011-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/58079/kaz/10.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58079/rus/10.03.2011
