act_code: '85746'
requisite: Решение Сарканского районного маслихата Алматинской области от 19 декабря 2014 года № 47-234. Зарегистрировано Департаментом юстиции Алматинской области 26 декабря 2014 года № 2976. Утратило силу решением Сарканского районного маслихата Алматинской области от 19 января 2016 года № 64-333
title:
  rus: О бюджете Сарканского района на 2015-2017 годы
  kaz: Сарқан ауданының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154005000002'
version_date:
  kaz: 2015-12-09
  rus: 2015-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/85746/kaz/09.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85746/rus/09.12.2015
caused_by:
  code: '96992'
  requisite: Решение Сарканского районного маслихата Алматинской области от 09 декабря 2015 года № 61-303. Зарегистрировано Департаментом юстиции Алматинской области 14 декабря 2015 года № 3612. Утратило силу решением Сарканского районного маслихата Алматинской области от 19 января 2016 года № 64-333
  title:
    rus: О внесении изменений в решение Сарканского районного маслихата от 19 декабря 2014 года № 47-234 "О бюджете Сарканского района на 2015-2017 годы"
    kaz: Сарқан аудандық мәслихатының 2014 жылғы 19 желтоқсандағы "Сарқан ауданының 2015-2017 жылдарға арналған бюджеті туралы" № 47-234 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96992/rus
