act_code: '54536'
requisite: Алматы облысы Алакөл ауданы Жыланды ауылдық округі әкімінің 2010 жылғы 19 тамыздағы № 15 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 16 қыркүйекте № 2-5-114 тіркелді
title:
  rus: Шектеу іс-шараларын енгізе отырып, карантин аймағының ветеринариялық режимін Жыланды ауылдық округінде белгілеу туралы
  kaz: Шектеу іс-шараларын енгізе отырып, карантин аймағының ветеринариялық режимін Жыланды ауылдық округінде белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-19
approved_by:
- '154003012002'
version_date:
  kaz: 2010-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/54536/kaz/19.08.2010
