act_code: '128357'
requisite: Решение Сарканского районного маслихата Алматинской области от 29 декабря 2018 года № 52-215. Зарегистрировано Департаментом юстиции Алматинской области 11 января 2019 года № 4998
title:
  rus: О бюджете Сарканского района на 2019-2021 годы
  kaz: Сарқан ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '154005000002'
version_date:
  kaz: 2018-12-29
  rus: 2018-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128357/kaz/29.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128357/rus/29.12.2018
