act_code: '177580'
requisite: Решение Жамбылского районного маслихата Алматинской области от 4 января 2023 года № 34-163
title:
  rus: О бюджетах сельских округов Жамбылского района на 2023-2025 годы
  kaz: Жамбыл ауданының ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-04
approved_by:
- '154018000002'
version_date:
  kaz: 2023-01-04
  rus: 2023-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/177580/kaz/04.01.2023
  rus: https://zan.gov.kz/client/#!/doc/177580/rus/04.01.2023
