act_code: '50450'
requisite: Алматы облысы Жамбыл ауданы әкімінің 2010 жылғы 11 қаңтардағы № 1-4 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 1 ақпанда № 2-7-84 тіркелді.Күші жойылды - Алматы облысы Жамбыл ауданы әкімдігінің 2010 жылғы 31 желтоқсандағы № 12-100 шешіммен
title:
  rus: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
  kaz: 1993 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуге алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-11
approved_by:
- '154018000003'
version_date:
  kaz: 2010-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/50450/kaz/11.01.2010
