act_code: '194066'
requisite: Решение Карасайского районного маслихата Алматинской области от 27 февраля 2024 года № 17-3
title:
  rus: Об утверждении Регламентов собраний местных сообществ города Каскелен и сельских округов Карасайского района
  kaz: Қарасай ауданының Қаскелең қаласы мен ауылдық округтерінің жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-27
approved_by:
- '154015000002'
version_date:
  kaz: 2024-02-27
  rus: 2024-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/194066/kaz/27.02.2024
  rus: https://zan.gov.kz/client/#!/doc/194066/rus/27.02.2024
