act_code: '208876'
requisite: Решение акима Карасайского района Алматинской области от 20 марта 2025 года № 1. Зарегистрировано Департаментом юстиции Алматинской области 1 апреля 2025 года № 6228-05. Утратило силу решением акима Карасайского района Алматинской области от 21 августа 2026 года № 282 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Карасайскому району
  kaz: Қарасай ауданында дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-20
approved_by:
- '154015000003'
version_date:
  kaz: 2025-03-20
  rus: 2025-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/208876/kaz/20.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208876/rus/20.03.2025
