act_code: '127000'
requisite: Решение акима Бастобинского сельского округа Каратальского района Алматинской области от 12 декабря 2018 года № 56. Зарегистрировано Департаментом юстиции Алматинской области 19 декабря 2018 года № 4963
title:
  rus: О снятии ограничительных мероприятий в селе Жылыбулак в улицах Кабанбай, Молдагуловой, Мира отара № 5 Бастобинского сельского округа
  kaz: Бастөбе ауылдық округінің Жылыбұлақ ауылындағы Қабанбай, Молдағұлова, Мир көшелерінің № 5 отарына шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '154009007002'
version_date:
  kaz: 2018-12-12
  rus: 2018-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127000/kaz/12.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127000/rus/12.12.2018
