act_code: '49784'
requisite: ''
title:
  rus: Матай ауылында Восточный поселок квартал 1, Восточный поселок квартал 2, Восточный поселок квартал 3, Восточный поселок квартал 4, Восточный поселок квартал 5, Восточный поселок квартал 6, Восточный поселок квартал 7 көше атауларын Шығыс орамы 1, Шығыс орамы 2, Шығыс орамы 3, Шығыс орамы 4, Шығыс орамы 5, Шығыс орамы 6, Шығыс орамы 7 көше атауларына өзгерту туралы
  kaz: Матай ауылында Восточный поселок квартал 1, Восточный поселок квартал 2, Восточный поселок квартал 3, Восточный поселок квартал 4, Восточный поселок квартал 5, Восточный поселок квартал 6, Восточный поселок квартал 7 көше атауларын Шығыс орамы 1, Шығыс орамы 2, Шығыс орамы 3, Шығыс орамы 4, Шығыс орамы 5, Шығыс орамы 6, Шығыс орамы 7 көше атауларына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-27
approved_by:
- '154011014001'
version_date:
  kaz: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49784/kaz/26.12.2014
caused_by:
  code: '86600'
  requisite: Решение акима Матайского сельского округа Аксуского района Алматинской области от 26 декабря 2014 года № 1. Зарегистрировано Департаментом юстиции Алматинской области 06 февраля 2015 года № 3026
  title:
    rus: О внесении изменений в решение акима  Матайского поселкового округа  от 28 декабря 2009 года № 1 «Об  изменении названии улиц Восточный  поселок квартал 1, Восточный поселок  квартал 2, Восточный поселок квартал 3,  Восточный поселок квартал 4, Восточный  поселок квартал 5, Восточный поселок  квартал 6, Восточный поселок квартал 7  в поселке Матай на названии улиц Шыгыс  орамы 1, Шыгыс орамы 2, Шыгыс орамы 3,  Шыгыс орамы 4, Шыгыс орамы 5, Шыгыс  орамы 6, Шыгыс орамы 7»
    kaz: Матай поселкелік округі әкімінің  2009 жылғы 28 желтоқсандағы  «Матай поселкесінде  Восточный поселок квартал 1,  Восточный поселок квартал 2,  Восточный поселок квартал 3,  Восточный поселок квартал 4,  Восточный поселок квартал 5,  Восточный поселок квартал 6,  Восточный поселок квартал 7  көше атауларын Шығыс орамы 1,  Шығыс орамы 2, Шығыс орамы 3,  Шығыс орамы 4, Шығыс орамы 5,  Шығыс орамы 6, Шығыс орамы 7  көше атауларына өзгерту туралы»  № 1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86600/rus
