act_code: '177118'
requisite: Решение маслихата города Қонаев Алматинской области от 29 декабря 2022 года № 36-101
title:
  rus: О бюджетах сельских округов города Қонаев на 2023-2025 годы
  kaz: Қонаев қаласы ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '154020000002'
version_date:
  rus: 2023-07-24
source:
  rus: https://zan.gov.kz/client/#!/doc/177118/rus/24.07.2023
caused_by:
  code: '184539'
  requisite: Решение маслихата города Қонаев Алматинской области от 24 июля 2023 года № 8-28
  title:
    rus: О внесении изменений в решение маслихата города Қонаев от 29 декабря 2022 года №36-101 «О бюджетах сельских округов города Қонаев на 2023-2025 годы»
    kaz: «Қонаев қаласы мәслихатының  2022 жылғы 29 желтоқсандағы «Қонаев қаласы ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы» № 36-101 шешіміне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/184539/rus
