act_code: '198024'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 24 июня 2024 года № VIII-24-119. Зарегистрировано Департаментом юстиции Алматинской области 24 июня 2024 года № 6135-05. Утратило силу решением Енбекшиказахского районного маслихата от 18 июня 2025 года № 44-208 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Енбекшиказахском районе
  kaz: Еңбекшіқазақ ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-24
approved_by:
- '154012000002'
version_date:
  kaz: 2024-06-24
  rus: 2024-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/198024/kaz/24.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198024/rus/24.06.2024
