act_code: '40497'
requisite: Алматы облысы Қаратал ауданы Үштөбе қаласы әкімінің 2008 жылғы 10 маусымдағы № 6-142 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының әділет басқармасында 2008 жылы 30 маусымда № 2-12-80 тіркелді
title:
  rus: Үштөбе қаласы Фрунзе учаскесі аумағынан жаңадан бой көтерген шағын аудан атауы "Мерей" шағын ауданы аталуы туралы
  kaz: Үштөбе қаласы Фрунзе учаскесі аумағынан жаңадан бой көтерген шағын аудан атауы "Мерей" шағын ауданы аталуы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-10
approved_by:
- '154009010002'
version_date:
  kaz: 2008-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/40497/kaz/10.06.2008
