act_code: '149107'
requisite: Решение Талдыкорганского городского маслихата Алматинской области от 24 ноября 2020 года № 454. Зарегистрировано Департаментом юстиции Алматинской области 30 ноября 2020 года № 5788
title:
  rus: Об утверждении проекта (схемы) зонирования земель города Талдыкорган, Отенайского и Еркинского сельских округов
  kaz: Талдықорған қаласы, Өтенай және Еркін ауылдық округтері жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-24
approved_by:
- '154002000002'
version_date:
  kaz: 2020-11-24
  rus: 2020-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/149107/kaz/24.11.2020
  rus: https://zan.gov.kz/client/#!/doc/149107/rus/24.11.2020
