act_code: '84434'
requisite: Решение Талгарского районного маслихата Алматинской области от 15 октября 2014 года № 36-214. Зарегистрировано Департаментом юстиции Алматинской области 12 ноября 2014 года № 2914. Утратило силу решением Талгарского районного маслихата Алматинской области от 29 августа 2016 года № 7-42
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и  определения перечня отдельных категорий нуждающихся граждан Талгарского района
  kaz: Талғар ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-10-15
approved_by:
- '154013000002'
version_date:
  kaz: 2014-10-15
  rus: 2014-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/84434/kaz/15.10.2014
  rus: https://zan.gov.kz/client/#!/doc/84434/rus/15.10.2014
