act_code: '146633'
requisite: Решение акима Лепсинского сельского округа Алакольского района Алматинской области от 18 сентября 2020 года № 6. Зарегистрировано Департаментом юстиции Алматинской области 23 сентября 2020 года № 5668
title:
  rus: О присвоении наименований новым улицам в селе Лепсинск Лепсинского сельского округа
  kaz: Лепсі ауылдық округінің Лепсі ауылындағы жаңа көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-18
approved_by:
- '154003018002'
version_date:
  kaz: 2020-09-18
  rus: 2020-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/146633/kaz/18.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146633/rus/18.09.2020
