act_code: '166389'
requisite: Решение Коксуского районного акима Алматинской области от 12 апреля 2022 года № 04-08. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 апреля 2022 года № 27539
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-12
approved_by:
- '154007000003'
version_date:
  kaz: 2022-04-12
  rus: 2022-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/166389/kaz/12.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166389/rus/12.04.2022
