act_code: '16182'
requisite: Алматы облысы Көксу ауданы әкімінің 2003 жылғы 24 маусымдағы N 6-276 шешімі. Алматы облыстық Әділет басқармасында 2003 жылы 25 маусымда N 1229 тіркелді. Күші жойылды - Алматы облысы Көксу ауданы әкімінің 2011 жылғы 12 қаңтардағы N 01 қаулысымен
title:
  rus: Кәмелетке толмағандардың құқықтарын қорғау жөніндегі комиссиясының құрамы туралы
  kaz: Кәмелетке толмағандардың құқықтарын қорғау жөніндегі комиссиясының құрамы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-23
approved_by:
- '154007000001'
version_date:
  kaz: 2003-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/16182/kaz/06.08.2003
caused_by:
  code: '17317'
  requisite: Алматы облысы Көксу ауданы әкімінің 2003 жылғы 7 тамыздағы N 8-300 шешімі. Алматы облыстық Әділет басқармасында 2003 жылы 11 тамызда N 1284 тіркелді. Күші жойылды - Алматы облысы Көксу ауданы әкімінің 2011 жылғы 12 қаңтардағы N 01 қаулысымен
  title:
    rus: Көксу ауданы әкімінің 2003 жылғы 24 маусымдағы "Кәмелетке толмағандардың құқықтарын қорғау жөніндегі комиссиясының құрамы туралы" N 6-276 шешіміне өзгерістер енгізу туралы
    kaz: Көксу ауданы әкімінің 2003 жылғы 24 маусымдағы "Кәмелетке толмағандардың құқықтарын қорғау жөніндегі комиссиясының құрамы туралы" N 6-276 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/17317/rus
