act_code: '77868'
requisite: Решение маслихата Талгарского района Алматинской области от 10 февраля 2014 года № 28-149. Зарегистрировано Департаментом юстиции Алматинской области 07 марта 2014 года № 2604. Утратило силу решением Талгарского районного маслихата Алматинской области от 17 ноября 2014 года № 37-216
title:
  rus: О выплате единовременной денежной компенсации на приобретение топлива для отопления жилых помещений педагогическим работникам образования, работаюшим в сельской местности Талгарского района
  kaz: Талғар ауданының ауылдық жерде жұмыс істейтін білім берудің педагог қызметкерлеріне тұрғын үй-жайларды жылыту үшін отын сатып алуға біржолғы ақшалай өтемақы төлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-10
approved_by:
- '154013000002'
version_date:
  kaz: 2014-02-10
  rus: 2014-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/77868/kaz/10.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77868/rus/10.02.2014
