act_code: '187812'
requisite: Решение маслихата города Қонаев Алматинской области от 24 октября 2023 года № 11-38. Зарегистрировано Департаментом юстиции Алматинской области 1 ноября 2023 года № 6047-05
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Қонаев
  kaz: Қонаев қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-24
approved_by:
- '154020000002'
version_date:
  kaz: 2025-02-21
  rus: 2025-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/187812/kaz/21.02.2025
  rus: https://zan.gov.kz/client/#!/doc/187812/rus/21.02.2025
caused_by:
  code: '207482'
  requisite: Решение маслихата города Қонаев Алматинской области от 21 февраля 2025 года № 39-143. Зарегистрировано Департаментом юстиции Алматинской области 25 февраля 2025 года № 6213-05
  title:
    rus: О внесении изменения в решение маслихата города Қонаев от 24 октября 2023 года № 11-38 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Қонаев»
    kaz: «Қонаев қаласы әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Қонаев қалалық мәслихатының 2023 жылғы 24 қазандағы № 11-38 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207482/rus
