act_code: '187812'
requisite: Решение маслихата города Қонаев Алматинской области от 24 октября 2023 года № 11-38. Зарегистрировано Департаментом юстиции Алматинской области 1 ноября 2023 года № 6047-05
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Қонаев
  kaz: Қонаев қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-24
approved_by:
- '154020000002'
version_date:
  kaz: 2026-04-23
  rus: 2026-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/187812/kaz/23.04.2026
  rus: https://zan.gov.kz/client/#!/doc/187812/rus/23.04.2026
caused_by:
  code: '224576'
  requisite: Решение маслихата города Қонаев Алматинской области от 23 апреля 2026 года № 62-212
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Қонаев от 24 октября 2023 года № 11-38 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Қонаев»
    kaz: Қонаев қаласының мәслихатының 2023 жылғы 24 қазандағы «Қонаев қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» № 11-38 шешіміне өзгерістермен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224576/rus
