act_code: '138846'
requisite: Решение Коксуского районного маслихата Алматинской области от 9 января 2020 года № 58-1. Зарегистрировано Департаментом юстиции Алматинской области 20 января 2020 года № 5410
title:
  rus: О бюджетах сельских округов Коксуского района на 2020-2022 годы
  kaz: Көксу ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154007000002'
version_date:
  kaz: 2020-09-23
  rus: 2020-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/138846/kaz/23.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138846/rus/23.09.2020
caused_by:
  code: '146824'
  requisite: Решение Коксуского районного маслихата Алматинской области от 23 сентября 2020 года № 66-1. Зарегистрировано Департаментом юстиции Алматинской области 29 сентября 2020 года № 5679
  title:
    rus: О внесении изменений в решение маслихата Коксуского района от 9 января 2020 года № 58-1 «О бюджетах сельских округов Коксуского района на 2020-2022 годы»
    kaz: Көксу ауданы мәслихатының 2020 жылғы 9 қаңтардағы «Көксу ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» № 58-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146824/rus
