act_code: '167212'
requisite: Решение Кербулакского районного маслихата Алматинской области от 13 апреля 2022 года № 19-114. Зарегистрировано в Министерстве юстиции Республики Казахстан 3 мая 2022 года № 27850
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Кербулакскому району
  kaz: Кербұлақ ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-13
approved_by:
- '154010000002'
version_date:
  kaz: 2022-04-13
  rus: 2022-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/167212/kaz/13.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167212/rus/13.04.2022
