act_code: '90726'
requisite: Решение Каратальского районного маслихата Алматинской области от 02 июня 2015 года № 47-192. Зарегистрировано Департаментом юстиции Алматинской области 19 июня 2015 года № 3238. Утратило силу решением Каратальского районного маслихата Алматинской области от 17 июня 2016 года № 7-26
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Каратальского районного маслихата»
  kaz: «Қаратал аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-02
approved_by:
- '154009000002'
version_date:
  kaz: 2015-06-02
  rus: 2015-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/90726/kaz/02.06.2015
  rus: https://zan.gov.kz/client/#!/doc/90726/rus/02.06.2015
