act_code: '118447'
requisite: Решение Алакольского районного маслихата Алматинской области от 25 декабря 2017 года № 24-5. Зарегистрировано Департаментом юстиции Алматинской области 9 января 2018 года № 4500
title:
  rus: О бюджетах города Ушарал и сельских округов Алакольского района на 2018-2020 годы
  kaz: Алакөл ауданының Үшарал қаласы мен ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '154003000002'
version_date:
  kaz: 2018-05-02
  rus: 2018-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/118447/kaz/02.05.2018
  rus: https://zan.gov.kz/client/#!/doc/118447/rus/02.05.2018
caused_by:
  code: '122401'
  requisite: Решение Алакольского районного маслихата Алматинской области от 2 мая 2018 года № 34-1. Зарегистрировано Департаментом юстиции Алматинской области 16 мая 2018 года № 4705
  title:
    rus: О внесении изменений и дополнения в решение Алакольского районного маслихата от 25 декабря 2017 года № 24-5 «О бюджетах города Ушарал и сельских округов Алакольского района на 2018-2020 годы»
    kaz: Алакөл аудандық мәслихатының 2017 жылғы 25 желтоқсандағы «Алакөл ауданының Үшарал қаласы мен ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы» № 24-5 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122401/rus
