act_code: '54704'
requisite: Алматы облысы Алакөл ауданы Қабанбай ауылдық округі әкімінің 2010 жылғы 19 тамыздағы № 41 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 01 қазанда № 2-5-118 тіркелді. Күші жойылды - Алматы облысы Алакөл ауданы Қабанбай ауылдық округі әкімінің 2010 жылғы 12 қарашадағы № 58 шешімімен
title:
  rus: Шектеу шараларын енгізе отырып, карантин аймағының ветеринарлық режимін белгілеу туралы
  kaz: Шектеу шараларын енгізе отырып, карантин аймағының ветеринарлық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-19
approved_by:
- '154003014002'
version_date:
  kaz: 2010-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/54704/kaz/19.08.2010
