act_code: '57082'
requisite: Алматы облысы Кербұлақ ауданы әкімінің 2010 жылғы 14 желтоқсандағы N 8 шешімі. Алматы облысының Әділет департаменті Кербұлақ ауданының Әділет басқармасында 2011 жылы 18 қаңтарда 2-13-132 тіркелді
title:
  rus: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '154010000001'
version_date:
  kaz: 2010-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/57082/kaz/14.12.2010
