act_code: '162525'
requisite: Решение Каратальского районного маслихата Алматинской области от 27 декабря 2021 года № 21-58. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26222
title:
  rus: О бюджете Каратальского района на 2022-2024 годы
  kaz: Қаратал ауданының 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '154009000002'
version_date:
  kaz: 2022-09-12
  rus: 2022-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/162525/kaz/12.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162525/rus/12.09.2022
caused_by:
  code: '171641'
  requisite: Решение Каратальского районного маслихата области Жетісу от 12 сентября 2022 года № 32-83
  title:
    rus: О внесении изменений в решение Каратальского районного маслихата от 27 декабря 2021 года № 21-58 «О бюджете Каратальского района на 2022-2024 годы»
    kaz: Қаратал аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 21-58 «Қаратал ауданының 2022-2024 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171641/rus
