act_code: '56762'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 10 желтоқсандағы № 39-242 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2011 жылы 14 қаңтарда № 2-4-125 тіркелді
title:
  rus: Ақсу ауданы бойынша жерлерді аймақтарға бөлу жобасы (схемасы), жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
  kaz: Ақсу ауданы бойынша жерлерді аймақтарға бөлу жобасы (схемасы), жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-10
approved_by:
- '154011000002'
version_date:
  kaz: 2010-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/56762/kaz/10.12.2010
