act_code: '108663'
requisite: Решение Алматинского областного маслихата от 9 декабря 2016 года № 11-54. Зарегистрировано Департаментом юстиции Алматинской области 21 декабря 2016 года № 4030
title:
  rus: Об областном бюджете Алматинской области на 2017-2019 годы
  kaz: Алматы облысының 2017-2019 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '154000000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/108663/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108663/rus/09.12.2016
