act_code: '199059'
requisite: Решение маслихата города Алатау Алматинской области от 19 июля 2024 года № 6-14
title:
  rus: «О бюджете города Алатау на 2024-2026 годы»
  kaz: «Алатау қаласының 2024-2026 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-19
approved_by:
- '154022000002'
version_date:
  kaz: 2024-10-22
  rus: 2024-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/199059/kaz/22.10.2024
  rus: https://zan.gov.kz/client/#!/doc/199059/rus/22.10.2024
caused_by:
  code: '202055'
  requisite: Решение маслихата города Алатау Алматинской области от 22 октября 2024 года № 10-26
  title:
    rus: О внесении изменении в решение маслихата города Алатау от 19 июля 2024 года №6-14 «О бюджете города Алатау на 2024-2026 годы»
    kaz: Алатау қаласы мәслихатының 2024 жылдың 19 шілдесіндегі №6-14 «Алатау қаласының 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202055/rus
