act_code: '79161'
requisite: Решение Текелийского городского маслихата Алматинской области от 28 марта 2014 года N 27-172. Зарегистрировано Департаментом юстиции Алматинской области 17 апреля 2014 года N 2675. Утратило силу решением Текелийского городского маслихата Алматинской области от 20 мая 2016 года № 5-25
title:
  rus: Об утверждении Регламента Текелийского городского маслихата
  kaz: Текелі қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '154019000002'
version_date:
  kaz: 2014-07-04
  rus: 2014-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/79161/kaz/04.07.2014
  rus: https://zan.gov.kz/client/#!/doc/79161/rus/04.07.2014
caused_by:
  code: '81731'
  requisite: Решение Текелийского городского маслихата Алматинской области от 04 июля 2014 года № 31-201. Зарегистрировано Департаментом юстиции Алматинской области 30 июля 2014 года № 2789. Утратило силу решением Текелийского городского маслихата Алматинской области от 20 июля 2016 года № 6-30
  title:
    rus: О внесении дополнений в решение Текелийского городского маслихата от 28 марта 2014 года № 27-172 "Об утверждении Регламента Текелийского городского маслихата"
    kaz: Текелі қалалық мәслихатының 2014 жылғы 28 наурыздағы "Текелі қалалық мәслихатының Регламентін бекіту туралы" № 27-172 шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81731/rus
