act_code: '91677'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 12 июня 2015 года № 53-291. Зарегистрировано Департаментом юстиции Алматинской области от 09 июля 2015 года № 3274. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 2 октября 2020 года № 71-400
title:
  rus: Об установлении единовременной денежной компенсации на покрытие расходов за коммунальные услуги и на приобретение топлива для отопления жилых помещений педагогическим работникам образования, работающим в сельской местности
  kaz: Ауылдық жерде жұмыс істейтін білім берудің педагог қызметкерлеріне коммуналдық қызмет көрсетулерге шығыстарды жабуға және тұрғын үй-жайларды жылыту үшін отын сатып алуға біржолғы ақшалай өтемақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-12
approved_by:
- '154006000002'
version_date:
  kaz: 2015-06-12
  rus: 2015-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/91677/kaz/12.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91677/rus/12.06.2015
