act_code: '53058'
requisite: Решение от 02.06.2010 №17, Акимат Аватского сельского округа
title:
  rus: Октябрь ауылдық округіндегі Байсеит ауылындағы атауы жоқ көшеге жаңа атау беру туралы
  kaz: Октябрь ауылдық округіндегі Байсеит ауылындағы атауы жоқ көшеге жаңа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-02
approved_by:
- '154012001001'
version_date:
  kaz: 2010-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/53058/kaz/03.06.2010
