act_code: '47795'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2009 жылғы 7 тамыздағы № 25-146 қаулысы. Алматы облысының әділет департаменті Ақсу ауданының әділет басқармасында 2009 жылы 9 қыркүйекте № 2-4-90 тіркелді
title:
  rus: Ақсу ауданы бойынша салық салу мақсатында жерлерді аймақтарға бөлу жобасы (схемасы), жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
  kaz: Ақсу ауданы бойынша салық салу мақсатында жерлерді аймақтарға бөлу жобасы (схемасы), жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-07
approved_by:
- '154011000002'
version_date:
  kaz: 2009-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/47795/kaz/07.08.2009
