act_code: '79897'
requisite: Решение акима Илийского района Алматинской области от 07 апреля 2014 года № 3. Зарегистрировано Департаментом юстиции Алматинской области 06 мая 2014 года № 2691. Утратило силу решением акима Илийского района Алматинской области от 05 января 2015 года № 1
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Илийскому  району
  kaz: Іле ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-07
approved_by:
- '154017000003'
version_date:
  kaz: 2014-04-07
  rus: 2014-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/79897/kaz/07.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79897/rus/07.04.2014
