act_code: '128837'
requisite: Решение Алакольского районного маслихата Алматинской области от 28 декабря 2018 года № 45-1. Зарегистрировано Департаментом юстиции Алматинской области 18 января 2019 года № 5016
title:
  rus: О бюджете Алакольского района на 2019-2021 годы
  kaz: Алакөл ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '154003000002'
version_date:
  kaz: 2019-12-06
  rus: 2019-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128837/kaz/06.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128837/rus/06.12.2019
caused_by:
  code: '137068'
  requisite: Решение Алакольского районного маслихата Алматинской области от 6 декабря 2019 года № 60-1. Зарегистрировано Департаментом юстиции Алматинской области 13 декабря 2019 года № 5341
  title:
    rus: О внесении изменений в решение Алакольского районного маслихата от 28 декабря 2018 года № 45-1 «О бюджете Алакольского района на 2019-2021 годы»
    kaz: Алакөл аудандық мәслихатының 2018 жылғы 28 желтоқсандағы «Алакөл ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 45-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137068/rus
