act_code: '108902'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 29 февраля 2016 года № 64-361
title:
  rus: О признании утратившим силу решения Ескельдинского районного маслихата от 21 сентября 2015 года № 57-312 «О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Ескельдинскому району»
  kaz: Ескелді аудандық мәслихатының 2015 жылғы 21 қыркүйектегі «Ескелді ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» №57-312 шешімінің күші жойылды деп танылсын
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-29
approved_by:
- '154006000002'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/108902/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/108902/rus/29.02.2016
