act_code: '37571'
requisite: Алматы облысы Алакөл ауданы әкімінің 2008 жылы 24 қаңтардағы № 1-86 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2008 жылы 12 ақпанда № 2-5-55 тіркелген
title:
  rus: 1991 жылы туылған азаматтарды шақыру учаскесіне тіркеуді жүргізу және жастарды мерзімді әскери қызметке шақыруға дайындық туралы
  kaz: 1991 жылы туылған азаматтарды шақыру учаскесіне тіркеуді жүргізу және жастарды мерзімді әскери қызметке шақыруға дайындық туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-24
approved_by:
- '154003000003'
version_date:
  kaz: 2008-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37571/kaz/24.01.2008
