act_code: '37695'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2008 жылы 18 ақпандағы № 6-36 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2008 жылы 20 ақпанда № 2-4-64 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2012 жылғы 05 қарашадағы № 8-67 шешімімен
title:
  rus: Ауылдық жерлерде тұратын және жұмыс істейтін мемлекеттік мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін бюджет қаражаты есебінен әлеуметтік көмек беру туралы
  kaz: Ауылдық жерлерде тұратын және жұмыс істейтін мемлекеттік мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін бюджет қаражаты есебінен әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-18
approved_by:
- '154011000002'
version_date:
  kaz: 2008-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/37695/kaz/18.02.2008
