act_code: '49673'
requisite: Алматы облысы Сарқан аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 29-183 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының Әділет басқармасында 2009 жылы 29 желтоқсанда № 2-17-79 тіркелді
title:
  rus: Сарқан ауданының 2010-2012 жылдарға арналған бюджеті туралы
  kaz: Сарқан ауданының 2010-2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '154005000002'
version_date:
  kaz: 2010-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/49673/kaz/07.12.2010
caused_by:
  code: '56032'
  requisite: Алматы облысы Сарқан аудандық мәслихатының 2010 жылғы 07 желтоқсандағы № 40-236 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының Әділет басқармасында 2010 жылы 15 желтоқсанда № 2-17-93 тіркелді
  title:
    rus: '"Сарқан ауданының 2010-2012 жылдарға арналған бюджеті туралы" Сарқан аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 29-183 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"Сарқан ауданының 2010-2012 жылдарға арналған бюджеті туралы" Сарқан аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 29-183 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56032/rus
