act_code: '54620'
requisite: Алматы облысы Ескелді ауданы Бақтыбай ауылдық округі әкімінің 2010 жылғы 04 тамыздағы № 153 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2010 жылы 16 қыркүйекте № 2-9-113 тіркелді
title:
  rus: Бақтыбай ауылдық округіне қарасты тұрғын үй салынып, жаңадан пайда болған көшелерге атауын беру туралы
  kaz: Бақтыбай ауылдық округіне қарасты тұрғын үй салынып, жаңадан пайда болған көшелерге атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-04
approved_by:
- '154006002002'
version_date:
  kaz: 2010-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/54620/kaz/04.08.2010
