act_code: '48848'
requisite: Алматы облысы Қаратал аудандық мәслихатының 2009 жылғы 15 қазандағы № 28-128 шешімі. Алматы облысының Әділет департаменті Қаратал ауданының Әділет басқармасында 2009 жылы 26 қарашада № 2-12-133 тіркелді. Күші жойылды - Алматы облысы Қаратал аудандық мәслихатының 2010 жылғы 19 қазандағы № 40-193 шешімімен
title:
  rus: 2010 жылға жер салығының базалық ставкаларын жоғарылату туралы
  kaz: 2010 жылға жер салығының базалық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-15
approved_by:
- '154009000002'
version_date:
  kaz: 2009-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/48848/kaz/15.10.2009
