act_code: '139117'
requisite: Решение Уйгурского районного маслихата Алматинской области от 10 января 2020 года № 6-60-347. Зарегистрировано Департаментом юстиции Алматинской области 20 января 2020 года № 5415
title:
  rus: О бюджетах сельских округов Уйгурского района на 2020-2022 годы
  kaz: Ұйғыр ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '154008000002'
version_date:
  kaz: 2020-04-20
  rus: 2020-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139117/kaz/20.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139117/rus/20.04.2020
caused_by:
  code: '142240'
  requisite: Решение Уйгурского районного маслихата Алматинской области от 20 апреля 2020 года № 6-64-369. Зарегистрировано Департаментом юстиции Алматинской области 28 апреля 2020 года № 5502
  title:
    rus: О внесении изменений в решение Уйгурского районного маслихата от 10 января 2020 года № 6-60-347 «О бюджетах сельских округов Уйгурского района на 2020-2022 годы»
    kaz: Ұйғыр аудандық мәслихатының 2020 жылғы 10 қаңтардағы № 6-60-347 «Ұйғыр ауданының ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы»  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142240/rus
