act_code: '200308'
requisite: Решение маслихата города Алатау Алматинской области от 23 августа 2024 года № 7-21
title:
  rus: Об утверждении состава Общественного совета города Алатау Алматинской области
  kaz: Алматы облысы Алатау қаласының Қоғамдық кеңес құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-23
approved_by:
- '154022000002'
version_date:
  kaz: 2024-08-23
  rus: 2024-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/200308/kaz/23.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200308/rus/23.08.2024
