act_code: '54047'
requisite: Алматы облысы Жамбыл ауданы Шолаққарғалы селолық округі әкімінің 2010 жылғы 23 шілдедегі № 7-38 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 2 тамызда № 2-7-106 тіркелді
title:
  rus: Шолаққарғалы селолық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру туралы
  kaz: Шолаққарғалы селолық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-23
approved_by:
- '154018023002'
version_date:
  kaz: 2010-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54047/kaz/23.07.2010
