act_code: '90408'
requisite: Решение Кербулакского районного маслихата Алматинской области от 13 мая 2015 года № 43-251. Зарегистрировано Департаментом юстиции Алматинской области 10 июня 2015 года № 3218. Утратило силу решением Кербулакского районного маслихата Алматинской области от 10 декабря 2019 года № 52-296
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельских населенных пунктах Кербулакского района
  kaz: Кербұлақ ауданының азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-13
approved_by:
- '154010000002'
version_date:
  kaz: 2015-05-13
  rus: 2015-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/90408/kaz/13.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90408/rus/13.05.2015
