act_code: '47563'
requisite: Алматы облысы Ескелді аудандық мәслихатының 2009 жылғы 5 тамыздағы № 28-174 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2009 жылы 28 тамызда № 2-9-87 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 18 қаңтардағы № 34-205 шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына отын сатып алу үшін 2009 жылы әлеуметтік көмек беру туралы
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына отын сатып алу үшін 2009 жылы әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-05
approved_by:
- '154006000002'
version_date:
  kaz: 2009-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/47563/kaz/05.08.2009
