act_code: '20274'
requisite: Алматы облысы Жамбыл аудандық мәслихаттың 2004 жылғы 05 мамырдағы № 12-43 шешімі. Алматы облысының Әділет департаментінде 2004 жылы 14 маусымда № 1664 тіркелді. Күші жойылды - Алматы облысы Жамбыл аудандық мәслихаттың 2007 жылғы 24 желтоқсандағы № 6-31 шешімімен
title:
  rus: Жамбыл аудандық мәслихатының Регламентін бекіту туралы
  kaz: Жамбыл аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-04
approved_by:
- '154018000002'
version_date:
  kaz: 2004-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/20274/kaz/04.05.2004
