act_code: '78204'
requisite: Решение маслихата Райымбекского района Алматинской области от 25 февраля 2014 года N 25-132. Зарегистрировано Департаментом юстиции Алматинской области 20 марта 2014 года N 2630. Утратило силу решением Райымбекского районного маслихата Алматинской области от 04 июня 2014 года № 32-165
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным  семьям (гражданам) по Райымбекскому району
  kaz: Райымбек ауданы бойынша аз қамтылған отбасыларға (азаматтарға) тұрғын үй  көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-02-25
approved_by:
- '154016000002'
version_date:
  kaz: 2014-02-25
  rus: 2014-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/78204/kaz/25.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78204/rus/25.02.2014
