act_code: '46267'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2009 жылғы 22 сәуірдегі № 4-19-124 шешімі. Алматы облысының Әділет департаменті Панфилов ауданының әділет басқармасында 2009 жылы 3 маусымда № 2-16-87 тіркелді
title:
  rus: Салық салу мақсатында Панфилов ауданының жерлерін аймақтарға бөлудің жобаларын (схемаларын) бекіту туралы
  kaz: Салық салу мақсатында Панфилов ауданының жерлерін аймақтарға бөлудің жобаларын (схемаларын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '154004000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46267/kaz/22.04.2009
