act_code: '53660'
requisite: Алматы облысы Еңбекшіқазақ ауданы Шелек селолық округі әкімінің 2010 жылғы 8 шілдедегі № 65 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 26 шілдеде № 2-8-159 тіркелді
title:
  rus: Шелек селолық округінің Шелек ауылындағы Попов көшесі атауын Садыр Әбішев көшесіне өзгерту туралы
  kaz: Шелек селолық округінің Шелек ауылындағы Попов көшесі атауын Садыр Әбішев көшесіне өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-08
approved_by:
- '154012024002'
version_date:
  kaz: 2010-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/53660/kaz/08.07.2010
