act_code: '56337'
requisite: Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 48-284 шешімі. Алматы облысы Ескелді ауданының Әділет басқармасында 2010 жылы 30 желтоқсанда № 2-9-117 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2012 жылғы 21 мамырдағы № 6-35 шешімімен
title:
  rus: Ескелді ауданының 2011-2013 жылдарға арналған бюджеті туралы
  kaz: Ескелді ауданының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '154006000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/56337/kaz/24.12.2010
