act_code: '43435'
requisite: Алматы облысы Балқаш аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 16-74 шешімі. Алматы облысының Әділет департаменті Балқаш ауданының әділет басқармасында 2009 жылғы 8 қаңтарда № 2-6-52 тіркелді. Күші жойылды - Алматы облысы Балқаш аудандық мәслихатының 2010 жылғы 29 наурыздағы № 29-155 шешімімен
title:
  rus: Балқаш ауданының 2009 жылға арналған бюджеті туралы
  kaz: Балқаш ауданының 2009 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154014000002'
version_date:
  kaz: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43435/kaz/22.12.2008
