act_code: '89928'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 22 апреля 2015 года № 45-2. Зарегистрировано Департаментом юстиции Алматинской области 18 мая 2015 года № 3169. Утратило силу решением Енбекшиказахского районного маслихата Алматинской области от 5 июня 2018 года № 30-45
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Енбекшиказахского района
  kaz: Еңбекшіқазақ ауданындағы аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегiн көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-04-22
approved_by:
- '154012000002'
version_date:
  kaz: 2015-04-22
  rus: 2015-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/89928/kaz/22.04.2015
  rus: https://zan.gov.kz/client/#!/doc/89928/rus/22.04.2015
