act_code: '51413'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 ақпандағы № 32-1 шешімі. Алматы облысының әділет департаменті Ұйғыр ауданының әділет басқармасында 2010 жылы 25 наурызда № 2-19-94 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2011 жылғы 22 маусымдағы № 49-4 шешімімен
title:
  rus: Ұйғыр ауданында табысы аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
  kaz: Ұйғыр ауданында табысы аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-22
approved_by:
- '154008000002'
version_date:
  kaz: 2010-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51413/kaz/22.02.2010
