act_code: '28312'
requisite: Решение маслихата Алматинской области от 25 апреля 2006 года № 27-198. Зарегистрировано Департаментом юстиции Алматинской области от 5 июня 2006 года № 1963
title:
  rus: Об установлении ставок платежей за загрязнение окружающей среды на 2006 год
  kaz: Қоршаған ортаны ластағаны үшін 2006 жылға арналған төлемақы ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-25
approved_by:
- '154000000002'
version_date:
  kaz: 2006-04-25
  rus: 2006-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/28312/kaz/25.04.2006
  rus: https://zan.gov.kz/client/#!/doc/28312/rus/25.04.2006
