act_code: '158597'
requisite: Решение Кербулакского районного маслихата Алматинской области от 6 сентября 2021 года № 11-55
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Кербулакскому району на 2021-2022 годы
  kaz: Кербұлақ ауданы бойынша 2021-2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-06
approved_by:
- '154010000002'
version_date:
  kaz: 2021-09-06
  rus: 2021-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/158597/kaz/06.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158597/rus/06.09.2021
