act_code: '51411'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 05 ақпандағы № 31-4 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2010 жылы 18 наурызда № 2-19-92 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 43-7 шешімімен
title:
  rus: Тіркелген бірыңғай салық ставкаларын бекіту туралы
  kaz: Тіркелген бірыңғай салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-05
approved_by:
- '154008000002'
version_date:
  kaz: 2010-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51411/kaz/05.02.2010
