act_code: '911'
requisite: Решение акима Алматинской области от 23 января 1998 года № 1-18. Зарегистрировано управлением юстиции Алматинской области 16 июля 1998 года № 20. Утратило силу решением акима Алматинской области от 24 августа 2004 года № 8-87
title:
  rus: Об определении государственного заказчика по договорам на оказание услуг по перевозке пассажиров по межобластным и международным автобусным маршрутам
  kaz: Халықаралық және облысаралық автобус бағыттарында қызмет көрсетуге келiсiм-шарт жасау жөнiнде мемлекеттiк тапсырушыны анықтау
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-23
approved_by:
- '154000000003'
version_date:
  kaz: 1998-01-23
  rus: 1998-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/911/kaz/23.01.1998
  rus: https://zan.gov.kz/client/#!/doc/911/rus/23.01.1998
