act_code: '123544'
requisite: Решение Талгарского районного маслихата Алматинской области от 25 июня 2018 года № 31-153. Зарегистрировано Департаментом юстиции Алматинской области 10 июля 2018 года № 4762
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Талгарского района
  kaz: Талғар ауданының Құрмет грамотасымен наградтау туралы ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2018-06-25
approved_by:
- '154013000002'
version_date:
  kaz: 2018-06-25
  rus: 2018-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/123544/kaz/25.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123544/rus/25.06.2018
