act_code: '220836'
requisite: Решение акима Корамского сельского округа Енбекшиказахского района Алматинской области от 24 ноября 2025 года № 9
title:
  rus: Об изменении наименований улиц в селе Корам, Корамского сельского округа
  kaz: Қорам ауылдық округінің, Қорам ауылындардағы көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-24
approved_by:
- '154012013002'
version_date:
  kaz: 2025-11-24
  rus: 2025-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/220836/kaz/24.11.2025
  rus: https://zan.gov.kz/client/#!/doc/220836/rus/24.11.2025
