act_code: '138312'
requisite: Решение Жамбылского районного маслихата Алматинской области от 27 декабря 2019 года № 65-302. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2020 года № 5394
title:
  rus: О бюджете Жамбылского района на 2020-2022 годы
  kaz: Жамбыл ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154018000002'
version_date:
  kaz: 2020-04-07
  rus: 2020-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/138312/kaz/07.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138312/rus/07.04.2020
caused_by:
  code: '141688'
  requisite: Решение Жамбылского районного маслихата Алматинской области от 7 апреля 2020 года № 68-317. Зарегистрировано Департаментом юстиции Алматинской области 14 апреля 2020 года № 5472
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 27 декабря 2019 года № 65-302 «О бюджете Жамбылского района на 2020-2022 годы»
    kaz: Жамбыл аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 65-302 «Жамбыл ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141688/rus
