act_code: '40241'
requisite: Алматы облысы Талғар аудандық мәслихатының 2008 жылғы 5 наурыздағы № 8-37 шешімі. Алматы облысының әділет департаменті Талғар ауданының әділет басқармасында 2008 жылы 17 сәуірде № 2-18-65 тіркелді. Күші жойылды - Талғар аудандық мәслихатының 2008 жылғы 28 шілдедегі № 11-65 шешімімен
title:
  rus: Талғар ауданы аумағындағы тұрғын үйлердің, аулалардың санитарлық жағдайын және көркейтілуін қамтамасыз етудің әкімшілік ережелерін бекіту туралы
  kaz: Талғар ауданы аумағындағы тұрғын үйлердің, аулалардың санитарлық жағдайын және көркейтілуін қамтамасыз етудің әкімшілік ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-05
approved_by:
- '154013000002'
version_date:
  kaz: 2008-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/40241/kaz/05.03.2008
