act_code: '175259'
requisite: Решение Уйгурского районного маслихата Алматинской области от 5 декабря 2022 года № 7-32-152
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию на 2023-2024 годы по Уйгурскому району
  kaz: Ұйғыр ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-05
approved_by:
- '154008000002'
version_date:
  kaz: 2022-12-05
  rus: 2022-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/175259/kaz/05.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175259/rus/05.12.2022
