act_code: '48843'
requisite: Алматы облысы Көксу ауданы Балпық кенттік округі әкімінің 2009 жылғы 3 қарашадағы № 120-11 шешімі. Алматы облысының Әділет департаменті Көксу ауданының әділет басқармасында 2009 жылы 24 қарашада № 2-14-82 тіркелді
title:
  rus: Балпық кенттік округіне қарасты, Ақшатоған ауылындағы көшелердің атын өзгерту туралы
  kaz: Балпық кенттік округіне қарасты, Ақшатоған ауылындағы көшелердің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-03
approved_by:
- '154007000001'
version_date:
  kaz: 2009-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/48843/kaz/03.11.2009
