act_code: '54452'
requisite: Алматы облысы Қапшағай қаласы Шеңгелді ауылдық округінің әкімінің 2010 жылғы 6 тамыздағы № 95 шешімі. Алматы облысы Қапшағай қаласының Әділет басқармасында 2010 жылғы 13 қыркүйекте № 2-2-109 тіркелді
title:
  rus: Ауылшаруашылық малдарының сарып ауруына шалдығуына байланысты Шеңгелді ауылдық округінің «Шеңгелді», «Кербұлақ», «Сарыбұлақ» елді мекендеріне шектеу іс-шараларын енгізе отырып, ветеринарлық режимін белгілеу туралы
  kaz: Ауылшаруашылық малдарының сарып ауруына шалдығуына байланысты Шеңгелді ауылдық округінің «Шеңгелді», «Кербұлақ», «Сарыбұлақ» елді мекендеріне шектеу іс-шараларын енгізе отырып, ветеринарлық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-06
approved_by:
- '154020002001'
version_date:
  kaz: 2010-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/54452/kaz/06.08.2010
