act_code: '50586'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 4-25-167 шешімі. Алматы облысының Әділет департаменті Панфилов ауданының Әділет басқармасында 2010 жылы 28 қаңтарда № 2-16-100 тіркелді. Күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2011 жылғы 8 желтоқсандағы № 4-54-337 шешімімен
title:
  rus: Панфилов ауданы аумағындағы бірыңғай тіркелген салық ставкаларының мөлшерін белгілеу туралы
  kaz: Панфилов ауданы аумағындағы бірыңғай тіркелген салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '154004000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50586/kaz/21.12.2009
