act_code: '78732'
requisite: Решение маслихата Енбекшиказахского района Алматинской области от 21 февраля 2014 года № 28-1. Зарегистрировано Департаментом юстиции Алматинской области 04 апреля 2014 года № 2645. Утратило силу решением Енбекшиказахского районного маслихата Алматинской области от 3 декабря 2021 года № 12-65
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Енбекшиказахском районе
  kaz: Еңбекшіқазақ ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көп пәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-02-21
approved_by:
- '154012000002'
version_date:
  kaz: 2014-02-21
  rus: 2014-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/78732/kaz/21.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78732/rus/21.02.2014
