act_code: '52857'
requisite: Алматы облысы Еңбекшіқазақ ауданы Евгенемаловодный селолық округі әкімінің 2010 жылғы 13 мамырдағы № 9 шешімі. Алматы облысы Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 27 мамырда № 2-8-150 тіркелді
title:
  rus: Евгенемаловодный селолық округінің Маловодное ауылындағы көшелерінің атауларын өзгерту туралы
  kaz: Евгенемаловодный селолық округінің Маловодное ауылындағы көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-13
approved_by:
- '154012006002'
version_date:
  kaz: 2010-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/52857/kaz/13.05.2010
