act_code: '43243'
requisite: Алматы облысы Ақсу аудандық мәслихатының 2008 жылғы 18 желтоқсандағы № 17-97 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2009 жылы 6 қаңтарда № 2-4-82 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 9 ақпандағы № 30-184 шешімімен
title:
  rus: Ақсу ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Ақсу ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '154011000002'
version_date:
  kaz: 2009-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43243/kaz/23.02.2009
caused_by:
  code: '44963'
  requisite: Алматы облысы Ақсу аудандық мәслихатының 2009 жылғы 23 ақпандағы № 20-117 шешімі. Алматы облысының әділет департаменті Ақсу ауданының әділет басқармасында 2009 жылғы 18 наурызда № 2-4-86 тіркелді. Күші жойылды - Алматы облысы Ақсу аудандық мәслихатының 2010 жылғы 09 ақпандағы № 30-184 шешімімен
  title:
    rus: Ақсу аудандық мәслихаттың 2008 жылғы 18 желтоқсандағы "Ақсу ауданының 2009 жылға арналған аудандық бюджеті туралы" 17-97 нөмірлі шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Ақсу аудандық мәслихаттың 2008 жылғы 18 желтоқсандағы "Ақсу ауданының 2009 жылға арналған аудандық бюджеті туралы" 17-97 нөмірлі шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44963/rus
