act_code: '127247'
requisite: Решение акима Каратальского района Алматинской области от 7 декабря 2018 года № 06. Зарегистрировано Департаментом юстиции Алматинской области 13 декабря 2018 года № 4951
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Каратальскому району
  kaz: Қаратал ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-07
approved_by:
- '154009000003'
version_date:
  kaz: 2022-12-30
  rus: 2022-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/127247/kaz/30.12.2022
  rus: https://zan.gov.kz/client/#!/doc/127247/rus/30.12.2022
caused_by:
  code: '177000'
  requisite: Решение акима Каратальского района области Жетісу от 30 декабря 2022 года № 09. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2022 года № 31473
  title:
    rus: О внесении изменения в решение акима Каратальского района от 7 декабря 2018 года №06 «Об образовании избирательных участков для проведения голосования и подсчета голосов по Каратальскому району»
    kaz: «Қаратал ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы» Қаратал ауданы әкімінің 2018 жылғы 7 желтоқсандағы № 06 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/177000/rus
