act_code: '85584'
requisite: Решение №39-225 от 19.12.2014, Маслихат Кербулакского района. Утратило силу решением Кербулакского районного маслихата Алматинской области от 26 арпеля 2016 года № 03-23
title:
  rus: О бюджете Кербулакского района на 2015-2017 год
  kaz: Кербұлақ ауданының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154010000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85584/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/85584/rus/27.05.2015
caused_by:
  code: '90602'
  requisite: Решение от 27.05.2015 №44-256, Маслихат Кербулакского района. Утратило силу решением Кербулакского районного маслихата Алматинской области от 26 арпеля 2016 года № 03-23
  title:
    rus: О внесении изменений в решение Кербулакского районного маслихата от 19 декабря 2014 года № 39-225 «О бюджете  Кербулакского района на 2015-2017 годы»
    kaz: Кербұлақ аудандық мәслихатының 2014 жылғы 19 желтоқсандағы «Кербұлақ ауданының 2015-2017 жылдарға арналған бюджеті туралы» № 39-225 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90602/rus
