act_code: '45656'
requisite: Алматы облысы Қарасай аудандық мәслихатының 2009 жылғы 6 сәуірдегі № 24-3 шешімі. Алматы облысының Әділет департаменті Қарасай ауданының Әділет басқармасында 2009 жылдың 6 мамырында № 2-11-69 тіркелді. Күші жойылды - Алматы облысы Қарасай аудандық мәслихатының 2010 жылғы 16 сәуірдегі № 39-8 шешімімен
title:
  rus: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
  kaz: Табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету тәртібі және мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-06
approved_by:
- '154015000002'
version_date:
  kaz: 2009-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/45656/kaz/06.04.2009
