act_code: '52853'
requisite: Алматы облысы Еңбекшіқазақ ауданы Бәйтерек селолық округі әкімінің 2010 жылғы 24 мамырдағы № 5-18 шешімі. Алматы облысы Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 27 мамырда № 2-8-146 тіркелді
title:
  rus: Бәйтерек селолық округіндегі Бәйтерек селосының Ленин көшесін Әлмерек абыз көшесі деп атын өзгерту туралы
  kaz: Бәйтерек селолық округіндегі Бәйтерек селосының Ленин көшесін Әлмерек абыз көшесі деп атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-24
approved_by:
- '154012016002'
version_date:
  kaz: 2010-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/52853/kaz/24.05.2010
