act_code: '85582'
requisite: Решение Ескельдинского районного маслихата Алматинской области от 19 декабря 2014 года № 47-254. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2014 года № 2983. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 23 мая 2016 года № 4-21
title:
  rus: О бюджете Ескельдинского района на 2015-2017 годы
  kaz: Ескелді ауданының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154006000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85582/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/85582/rus/27.05.2015
caused_by:
  code: '90809'
  requisite: Решение Ескельдинского районного маслихата Алматинской области от 27 мая 2015 года № 52-283. Зарегистрировано Департаментом юстиции Алматинской области 10 июня 2015 года № 3210. Утратило силу решением Ескельдинского районного маслихата Алматинской области от 23 мая 2016 года № 4-21
  title:
    rus: О внесении изменений в решение Ескельдинского районного маслихата от 19 декабря 2014 года № 47-254 «О бюджете Ескельдинского района на 2015-2017 годы»
    kaz: Ескелді аудандық мәслихатының 2014 жылғы 19 желтоқсандағы «Ескелді ауданының 2015-2017 жылдарға арналған бюджеті туралы» № 47-254 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90809/rus
