act_code: '13289'
requisite: Решение акима Алматинской области от 11 сентября 2002 года № 9-229. Зарегистрировано Управлением юстиции Алматинской области 27 сентября 2002 года № 831
title:
  rus: 06 очередном призыве граждан 1975-1984 годов рождения на срочную военную службу в октябре-декабре 2002 года в Вооруженные Силы Республики Казахстан
  kaz: Қазақстан Республикасынын Қарулы Күштері катарына мерзімді әскери кызметке 2002 жылгы казан-желтоксан айларында 1975-1984 жылдары туылған азаматтарды кезекті піакыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-09-10
approved_by:
- '154000000003'
version_date:
  kaz: 2002-09-10
  rus: 2002-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/13289/kaz/10.09.2002
  rus: https://zan.gov.kz/client/#!/doc/13289/rus/10.09.2002
