act_code: '124095'
requisite: Решение Алматинского областного маслихата от 25 июля 2018 года № 34-174. Зарегистрировано Департаментом юстиции Алматинской области 8 августа 2018 года № 4780
title:
  rus: О повышении ставок платы за эмиссии в окружающую среду в Алматинской области
  kaz: Алматы облысында қоршаған ортаға эмиссиялар үшін төлемақы мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-25
approved_by:
- '154000000002'
version_date:
  kaz: 2018-07-25
  rus: 2018-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/124095/kaz/25.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124095/rus/25.07.2018
