act_code: '50516'
requisite: Алматы облысы Балқаш ауданы әкімінің 2009 жылғы 30 желтоқсандағы № 12-14 шешімі. Алматы облысының Әділет департаменті Балқаш ауданының әділет басқармасында 2010 жылы 29 қаңтарда № 2-6-64 тіркелді. Күші жойылды - Алматы облысы Балқаш ауданы әкімінің 2010 жылғы 09 желтоқсандағы № 12-10 шешімімен
title:
  rus: 1993 жылы туылған азаматтарды шақыру учаскелеріне тіркеуге алу туралы
  kaz: 1993 жылы туылған азаматтарды шақыру учаскелеріне тіркеуге алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-30
approved_by:
- '154014000003'
version_date:
  kaz: 2009-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/50516/kaz/30.12.2009
