act_code: '102085'
requisite: Решение Коксуского районного маслихата Алматинской области от 04 апреля 2016 года № 2-1. Зарегистрировано Департаментом юстиции Алматинской области 06 мая 2016 года № 3820. Утратило силу решением Коксуского районного маслихата Алматинской области от 24 июля 2020 года № 62-6
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций в Коксуском районе
  kaz: Көксу ауданында жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-04-04
approved_by:
- '154007000002'
version_date:
  kaz: 2016-04-04
  rus: 2016-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/102085/kaz/04.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102085/rus/04.04.2016
