act_code: '54541'
requisite: Алматы облысы Еңбекшіқазақ ауданы Түрген селолық округі әкімінің 2010 жылғы 24 тамыздағы № 27 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 16 қыркүйекте № 2-8-161 тіркелді
title:
  rus: Түрген селолық округіндегі Түрген селосының Суворов көшесін Тәжметов Дәулеткелді көшесі деп атауын өзгерту туралы
  kaz: Түрген селолық округіндегі Түрген селосының Суворов көшесін Тәжметов Дәулеткелді көшесі деп атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-24
approved_by:
- '154012023002'
version_date:
  kaz: 2010-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/54541/kaz/24.08.2010
