act_code: '15269'
requisite: Решение Алматинского областного маслихата от 20 марта 2003 года № 33-187. Зарегистрировано Управлением юстиции Алматинской области 8 апреля 2003 года № 1070. Утратило силу решением маслихата Алматинской области от 21 декабря 2004 года № 13-89
title:
  rus: О программе занятости населения Алматинской област на 2003 год
  kaz: Алматы облысы халқын жұмыспен қамтудың 2003 жылға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-20
approved_by:
- '154000000002'
version_date:
  kaz: 2003-03-20
  rus: 2003-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/15269/kaz/20.03.2003
  rus: https://zan.gov.kz/client/#!/doc/15269/rus/20.03.2003
