act_code: '54422'
requisite: Алматы облысы Іле ауданы Междуреченск ауылдық округінің әкімінің 2010 жылғы 2 тамыздағы № 04 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 1 қыркүйекте № 2-10-126 тіркелді
title:
  rus: Междуреченск ауылдық округінде жаңадан ашылған ықшам ауданы мен жаңа бөлінген көшелерге атау беру туралы
  kaz: Междуреченск ауылдық округінде жаңадан ашылған ықшам ауданы мен жаңа бөлінген көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-02
approved_by:
- '154017008002'
version_date:
  kaz: 2010-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/54422/kaz/02.08.2010
