act_code: '43634'
requisite: Алматы облысы Ұйғыр ауданы әкімінің 2008 жылғы 22 желтоқсандағы № 12-67 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2009 жылғы 20 қаңтарда № 2-19-69 тіркелді. Күші жойылды - Алматы облысы Ұйғыр ауданы әкімінің 2009 жылғы 04 маусымдағы № 04-36 шешімімен
title:
  rus: Ұйғыр ауданы бойынша 1992 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуді ұйымдастыру және қамтамасыз ету туралы
  kaz: Ұйғыр ауданы бойынша 1992 жылы туылған азаматтарды әскерге шақыру учаскесінде тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154008000001'
version_date:
  kaz: 2009-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/43634/kaz/11.03.2009
caused_by:
  code: '44961'
  requisite: Алматы облысы Ұйғыр ауданы әкімінің 2009 жылғы 11 наурыздағы N 03-30 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2009 жылы 17 наурызда N 2-19-73 тіркелді. Күші жойылды - Алматы облысы Ұйғыр ауданы әкімінің 2009 жылғы 04 маусымдағы N 04-36 шешімімен
  title:
    rus: Аудан әкімінің 2008 жылғы 22 желтоқсандағы "1992 жылы туылған азаматтарды әскерге шақыру учаскесінде тізімге алу және жастарды 2009 жылғы әскери қызметке дайындау туралы" N 12-67 шешіміне өзгерістер енгізу туралы (нормативтік құқықтық актілердің мемлекеттік тіркеу тізілімінде 2009 жылғы 20 қаңтардағы N 2-19-69 нөмірімен тіркелген)
    kaz: Аудан әкімінің 2008 жылғы 22 желтоқсандағы "1992 жылы туылған азаматтарды әскерге шақыру учаскесінде тізімге алу және жастарды 2009 жылғы әскери қызметке дайындау туралы" N 12-67 шешіміне өзгерістер енгізу туралы (нормативтік құқықтық актілердің мемлекеттік тіркеу тізілімінде 2009 жылғы 20 қаңтардағы N 2-19-69 нөмірімен тіркелген)
  link: https://zan.gov.kz/client/#!/doc/44961/rus
