act_code: '138658'
requisite: Решение Текелийского городского маслихата Алматинской области от 9 января 2020 года № 44-265. Зарегистрировано Департаментом юстиции Алматинской области 16 января 2020 года № 5400
title:
  rus: О бюджете сельского округа города Текели на 2020-2022 годы
  kaz: Текелі қаласының ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154019000002'
version_date:
  kaz: 2020-12-20
  rus: 2020-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/138658/kaz/20.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138658/rus/20.12.2020
caused_by:
  code: '150262'
  requisite: Решение Текелийского городского маслихата Алматинской области от 20 декабря 2020 года № 55-326. Зарегистрировано Департаментом юстиции Алматинской области 23 декабря 2020 года № 5831
  title:
    rus: О внесении изменений в решение Текелийского городского маслихата от 9 января 2020 года № 44-265 «О бюджете сельского округа города Текели на 2020-2022 годы»
    kaz: Текелі қалалық мәслихатының 2020 жылғы 9 қаңтардағы № 44-265 «Текелі қаласының ауылдық округінің 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150262/rus
