act_code: '101674'
requisite: Решение Кербулакского районного маслихата Алматинской области от 05 апреля 2016 года № 02-16. Зарегистрировано Департаментом юстиции Алматинской области 27 апреля 2016 года № 3789. Утратило силу решением Кербулакского районного маслихата Алматинской области от 17 марта 2021 года № 03-20
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Кербулакском районе
  kaz: Кербұлақ ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-05
approved_by:
- '154010000002'
version_date:
  kaz: 2016-04-05
  rus: 2016-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/101674/kaz/05.04.2016
  rus: https://zan.gov.kz/client/#!/doc/101674/rus/05.04.2016
