act_code: '144624'
requisite: Решение Талдыкорганского городского маслихата Алматинской области от 25 июня 2020 года № 400. Зарегистрировано Департаментом юстиции Алматинской области 9 июля 2020 года № 5558
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в городе Талдыкорган
  kaz: Талдықорған қаласында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '154002000002'
version_date:
  kaz: 2024-02-12
  rus: 2024-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/144624/kaz/12.02.2024
  rus: https://zan.gov.kz/client/#!/doc/144624/rus/12.02.2024
caused_by:
  code: '193338'
  requisite: Решение маслихата города Талдыкорган области Жетісу от 12 февраля 2024 года № 16-94. Зарегистрировано Департаментом юстиции области Жетісу 14 февраля 2024 года № 136-19
  title:
    rus: О внесении изменений в решение Талдыкорганского городского маслихата от 25 июня 2020 года № 400 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в городе Талдыкорган»
    kaz: Талдықорған қалалық мәслихатының 2020 жылғы 25 маусымдағы«Талдықорған қаласында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптар мен пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» № 400 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193338/rus
