act_code: '85565'
requisite: Решение №36-228 от 19.12.2014, Маслихат г. Текели. Утратило силу решением Текелийского городского маслихата Алматинской области от 28 марта 2016 года № 2-10
title:
  rus: О бюджете города Текели на 2015-2017 годы
  kaz: Текелі қаласының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '154019000002'
version_date:
  kaz: 2015-09-07
  rus: 2015-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/85565/kaz/07.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85565/rus/07.09.2015
caused_by:
  code: '93658'
  requisite: Решение Текелийского городского маслихата Алматинской области от 07 сентября 2015 года № 40-262. Зарегистрировано Департаментом юстиции Алматинской области 11 сентября 2015 года № 3406. Утратило силу решением Текелийского городского маслихата Алматинской области от 28 марта 2016 года № 2-10
  title:
    rus: О внесении изменений в решение Текелийского городского маслихата от 19 декабря 2014 года № 36-228 "О бюджете города Текели на 2015-2017 годы"
    kaz: Текелі қалалық мәслихатының 2014 жылғы 19 желтоқсандағы "Текелі қаласының 2015-2017 жылдарға арналған бюджеті туралы" № 36-228 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93658/rus
