act_code: '1008'
requisite: Решение акима Алматинской области 25 июня 1998 года № 6-214а. Зарегистрировано управлением юстиции Алматинской области 28 июля 1998 года № 26. Утратило силу решением акима Алматинской области от 29 сентября 2004 года № 9-96
title:
  rus: Об утверждении Положения о порядке проведения конкурса на замещение вакантной должности государственной службы
  kaz: Мемлекеттiк қызметтегi бос лауазымға орналастыру конкурсын өткiзу тәртiбi туралы Ереженi бекiту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1998-06-24
approved_by:
- '154000000003'
version_date:
  kaz: 1998-06-24
  rus: 1998-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1008/kaz/24.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1008/rus/24.06.1998
