act_code: '96671'
requisite: Решение от 15.05.2015 №5-48-332, Маслихат Панфиловского района
title:
  rus: 'О признании утративших силу некоторых решений Панфиловского районного маслихата '
  kaz: 'Панфилов аудандық мәслихаттың қабылдаған кейбір шешімдерінің күшін жою туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-15
approved_by:
- '154004000002'
version_date:
  kaz: 2015-05-15
  rus: 2015-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/96671/kaz/15.05.2015
  rus: https://zan.gov.kz/client/#!/doc/96671/rus/15.05.2015
