act_code: '64270'
requisite: Решение Илийского районного маслихата Алматинской области от 5 ноября 2012 года № 11-52
title:
  rus: Об отмене решении Илийского районного маслихата
  kaz: Іле аудандық мәслихаты шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-05
approved_by:
- '154017000002'
version_date:
  kaz: 2012-11-05
  rus: 2012-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/64270/kaz/05.11.2012
  rus: https://zan.gov.kz/client/#!/doc/64270/rus/05.11.2012
