act_code: '69778'
requisite: Решение маслихата города Капчагай Алматинской области от 22 декабря 2012 года № 11-51. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2012 года № 2265. Утратило силу решением Капшагайского городского маслихата Алматинской области от 29 декабря 2014 года № 43-183
title:
  rus: О бюджете города Капчагай на 2013-2015 годы
  kaz: Қапшағай қаласының 2013-2015 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-22
approved_by:
- '154020000002'
version_date:
  kaz: 2013-11-08
  rus: 2013-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/69778/kaz/08.11.2013
  rus: https://zan.gov.kz/client/#!/doc/69778/rus/08.11.2013
caused_by:
  code: '75481'
  requisite: Решение маслихата города Капшагай Алматинской области от 08 ноября 2013 года № 24-107. Зарегистрировано Департаментом юстиции Алматинской области 19 ноября 2013 года № 2466. Утратило силу решением Капшагайского городского маслихата Алматинской области от 29 декабря 2014 года № 43-183
  title:
    rus: О внесении изменений в решение Капшагайского городского маслихата от 22 декабря 2012 года N 11-51 "О бюджете города Капшагай на 2013-2015 годы"
    kaz: Қапшағай қалалық мәслихатының 2012 жылғы 22 желтоқсандағы "Қапшағай қаласының 2013-2015 жылдарға арналған бюджеті туралы" N 11-51 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75481/rus
