act_code: '97244'
requisite: Решение Каратальского районного маслихата Алматинской области от 23 декабря 2015 года № 54-227. Зарегистрировано Департаментом юстиции Алматинской области 29 декабря 2015 года № 3649. Утратило силу решением Каратальского районного маслихата Алматинской области от 8 июня 2017 года № 18-76
title:
  rus: О бюджете Каратальского района на 2016-2018 годы»
  kaz: Қаратал ауданының 2016-2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '154009000002'
version_date:
  kaz: 2016-02-03
  rus: 2016-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/97244/kaz/03.02.2016
  rus: https://zan.gov.kz/client/#!/doc/97244/rus/03.02.2016
caused_by:
  code: '99002'
  requisite: Решение Каратальского районного маслихата Алматинской области от 03 февраля 2016 года № 57-237. Зарегистрировано Департаментом юстиции Алматинской области 12 февраля 2016 года № 3710. Утратило силу решением Каратальского районного маслихата Алматинской области от 8 июня 2017 года № 18-76
  title:
    rus: О внесении изменений в решение Каратальского районного маслихата от 23 декабря 2015 года № 54-227 "О бюджете Каратальского района на 2016-2018 годы"
    kaz: Қаратал аудандық мәслихатының 2015 жылғы 23 желтоқсандағы "Қаратал ауданының 2016-2018 жылдарға арналған бюджеті туралы" № 54-227 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99002/rus
