act_code: '56886'
requisite: Алматы облысы Ескелді ауданы әкімінің 2010 жылғы 31 желтоқсандағы № 24 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2011 жылы 18 қаңтарда № 2-9-118 тіркелді
title:
  rus: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскерге шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-31
approved_by:
- '154006000003'
version_date:
  kaz: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/56886/kaz/31.12.2010
