act_code: '55696'
requisite: Алматы облысы Ақсу ауданы Қызылағаш ауылдық округі әкімінің 2010 жылғы 17 қарашадағы № 1 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының Әділет басқармасында 2010 жылы 06 желтоқсанда № 2-4-122 тіркелді
title:
  rus: Қызылағаш ауылдық округіндегі Воронин көшесінің атауын Жайсан көшесі, Садовая көшесінің атауын Қонаев көшесі, Защитная көшесінің атауын Момышұлы көшесі, Студенттер көшесінің атауын Далғабаев көшесі, Новая 1 көшесінің атауын Дөсет ата көшесі, Новая 2 көшесінің атауын Асар көшесі атауларына өзгерту туралы
  kaz: Қызылағаш ауылдық округіндегі Воронин көшесінің атауын Жайсан көшесі, Садовая көшесінің атауын Қонаев көшесі, Защитная көшесінің атауын Момышұлы көшесі, Студенттер көшесінің атауын Далғабаев көшесі, Новая 1 көшесінің атауын Дөсет ата көшесі, Новая 2 көшесінің атауын Асар көшесі атауларына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-17
approved_by:
- '154011012002'
version_date:
  kaz: 2010-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55696/kaz/17.11.2010
