act_code: '46266'
requisite: Алматы облысы Панфилов аудандық мәслихатының 2009 жылғы 22 сәуірдегі N 4-19-123 шешімі. Алматы облысының Әділет департаменті Панфилов ауданының әділет басқармасында 2009 жылы 2 маусымда N 2-16-86 тіркелді. Күші жойылды - Алматы облысы Панфилов аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 4-25-165 шешімімен
title:
  rus: Панфилов ауданында табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
  kaz: Панфилов ауданында табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '154004000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46266/kaz/22.04.2009
