act_code: '53685'
requisite: Алматы облысы Жамбыл аудандық мәслихатының 2010 жылғы 23 маусымдағы № 39-183 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 28 шілдедегі № 2-7-105 тіркелді. Күші жойылды - Алматы облысы Жамбыл аудандық мәслихатының 2012 жылғы 11 маусымдағы № 8-69 шешімімен
title:
  rus: «Жамбыл ауданының Құрметті Азаматы» атағын беру туралы» Ережені бекіту туралы
  kaz: «Жамбыл ауданының Құрметті Азаматы» атағын беру туралы» Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-23
approved_by:
- '154018000002'
version_date:
  kaz: 2010-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/53685/kaz/23.06.2010
