act_code: '57083'
requisite: Решение от 24.12.2010 №36-280, Маслихат Кербулакского района
title:
  rus: Кербұлақ ауданы аумағында жер салығының базалық ставкаларын жоғарылату туралы
  kaz: Кербұлақ ауданы аумағында жер салығының базалық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '154010000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/57083/kaz/24.12.2010
