act_code: '128702'
requisite: Решение Коксуского районного маслихата Алматинской области от 27 декабря 2018 года № 40-1. Зарегистрировано Департаментом юстиции Алматинской области 15 января 2019 года № 5000
title:
  rus: О бюджете Коксуского района на 2019-2021 годы
  kaz: Көксу ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '154007000002'
version_date:
  kaz: 2019-12-04
  rus: 2019-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/128702/kaz/04.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128702/rus/04.12.2019
caused_by:
  code: '137055'
  requisite: Решение Коксуского районного маслихата Алматинской области от 4 декабря 2019 года № 55-1. Зарегистрировано Департаментом юстиции Алматинской области 12 декабря 2019 года № 5324
  title:
    rus: О внесении изменений в решение маслихата Коксуского района от 27 декабря 2018 года № 40-1 «О бюджете Коксуского района на 2019-2021 годы»
    kaz: Көксу ауданы мәслихатының 2018 жылғы 27 желтоқсандағы «Көксу ауданының 2019-2021 жылдарға арналған бюджеті туралы» № 40-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137055/rus
