act_code: '228492'
requisite: Решение акима Малыбайского сельского округа Енбекшиказахского района Алматинской области от 15 июля 2026 года № 3
title:
  rus: О присвоении наименования безымянной улице в селе Малыбай Малыбайского сельского округа
  kaz: Малыбай ауылдық округінің Малыбай ауылындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-15
approved_by:
- '154012028002'
version_date:
  kaz: 2026-07-15
  rus: 2026-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/228492/kaz/15.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228492/rus/15.07.2026
