act_code: '108887'
requisite: Решение Талдыкорганского городского маслихата Алматинской области от 14 декабря 2016 года № 67. Зарегистрировано Департаментом юстиции Алматинской области 28 декабря 2016 года № 4048
title:
  rus: О бюджете города Талдыкорган на 2017-2019 годы
  kaz: Талдықорған қаласының 2017-2019 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-14
approved_by:
- '154002000002'
version_date:
  kaz: 2017-08-17
  rus: 2017-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/108887/kaz/17.08.2017
  rus: https://zan.gov.kz/client/#!/doc/108887/rus/17.08.2017
caused_by:
  code: '114536'
  requisite: Решение Талдыкорганского городского маслихата Алматинской области от 17 августа 2017 года № 111. Зарегистрировано Департаментом юстиции Алматинской области 25 августа 2017 года № 4306
  title:
    rus: О внесении изменений в решение Талдыкорганского городского маслихата от 14 декабря 2016 года № 67 «О бюджете города Талдыкорган на 2017-2019 годы»
    kaz: Талдықорған қалалық мәслихатының 2016 жылғы 14 желтоқсандағы «Талдықорған қаласының 2017-2019 жылдарға арналған бюджеті туралы» № 67 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114536/rus
