act_code: '138126'
requisite: Решение Каратальского районного маслихата Алматинской области от 27 декабря 2019 года № 65-234. Зарегистрировано Департаментом юстиции Алматинской области 9 января 2020 года № 5379
title:
  rus: О бюджете Каратальского района на 2020-2022 годы
  kaz: Қаратал ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154009000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138126/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138126/rus/27.12.2019
