act_code: '138126'
requisite: Решение Каратальского районного маслихата Алматинской области от 27 декабря 2019 года № 65-234. Зарегистрировано Департаментом юстиции Алматинской области 9 января 2020 года № 5379
title:
  rus: О бюджете Каратальского района на 2020-2022 годы
  kaz: Қаратал ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154009000002'
version_date:
  kaz: 2020-09-10
  rus: 2020-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/138126/kaz/10.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138126/rus/10.09.2020
caused_by:
  code: '146370'
  requisite: Решение Каратальского районного маслихата Алматинской области от 10 сентября 2020 года № 76-269. Зарегистрировано Департаментом юстиции Алматинской области 16 сентября 2020 года № 5656
  title:
    rus: О внесении изменений в решение Каратальского районного маслихата от 27 декабря 2019 года № 65-234 «О бюджете Каратальского района на 2020-2022 годы»
    kaz: Қаратал аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 65-234 «Қаратал ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146370/rus
