act_code: '216224'
requisite: Решение Алматинского областного маслихата от 22 октября 2025 года № 42-234
title:
  rus: Об утверждении Правил выпаса сельскохозяйственных животных по Алматинской области
  kaz: Алматы облысы бойынша ауыл шаруашылығы жануарларын жаю қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-22
approved_by:
- '154000000002'
version_date:
  kaz: 2025-10-22
  rus: 2025-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/216224/kaz/22.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216224/rus/22.10.2025
