act_code: '155892'
requisite: Решение Енбекшиказахского районного маслихата Алматинской области от 30 апреля 2021 года № 6-31. Зарегистрировано Департаментом юстиции Алматинской области 14 мая 2021 года № 5955
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, культуры являющимся гражданскими служащими и работающим в сельских населенных пунктах Енбекшиказахского района
  kaz: Еңбекшіқазақ ауданының азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-30
approved_by:
- '154012000002'
version_date:
  kaz: 2021-04-30
  rus: 2021-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/155892/kaz/30.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155892/rus/30.04.2021
