act_code: '55645'
requisite: Алматы облысы Талғар аудандық мәслихатының 2010 жылғы 20 қазандағы № 38-219 шешімі. Алматы облысы Талғар ауданының Әділет басқармасында 2010 жылғы 1 желтоқсанда № 2-18-116 тіркелді. Күші жойылды - Алматы облысы Талғар аудандық мәслихатының 2011 жылғы 21 қазандағы № 51-307 шешімімен
title:
  rus: Талғар ауданы бойынша 2010 жылға тіркелген салық ставкаларының мөлшерін белгілеу туралы
  kaz: Талғар ауданы бойынша 2010 жылға тіркелген салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-20
approved_by:
- '154013000002'
version_date:
  kaz: 2010-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/55645/kaz/20.10.2010
