act_code: '138375'
requisite: Решение Алакольского районного маслихата Алматинской области от 27 декабря 2019 года № 62-2. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2020 года № 5395
title:
  rus: О бюджете Алакольского района на 2020-2022 годы
  kaz: Алакөл ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154003000002'
version_date:
  kaz: 2020-12-07
  rus: 2020-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/138375/kaz/07.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138375/rus/07.12.2020
caused_by:
  code: '149846'
  requisite: Решение Алакольского районного маслихата Алматинской области от 7 декабря 2020 года № 79-1. Зарегистрировано Департаментом юстиции Алматинской области 11 декабря 2020 года № 5803
  title:
    rus: О внесении изменений в решение Алакольского районного маслихата от 27 декабря 2019 года № 62-2 «О бюджете Алакольского района на 2020-2022 годы»
    kaz: Алакөл аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 62-2 «Алакөл ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149846/rus
