act_code: '56281'
requisite: Решение малихата Алматинской области от 14 декабря 2010 года за № 39-221. Зарегистрировано Департаментом юстиции Алматинской области от 29 декабря 2010 года № 2064
title:
  rus: Об областном бюджете Алматинской области на 2011-2013 годы
  kaz: Алматы облысының 2011-2013 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-14
approved_by:
- '154000000002'
version_date:
  rus: 2011-10-19
source:
  rus: https://zan.gov.kz/client/#!/doc/56281/rus/19.10.2011
