act_code: '11986'
requisite: Решение акима Алматинской области от 11 апреля 2002 года № 4-68. Зарегистрировано Управлением юстиции Алматинской области 23 апреля 2002 года № 682. Утратило силу решением акима Алматинской области от 11 сентября 2002 года № 9-229
title:
  rus: О6 очередном призыве граждан 1975-1984 годов рождения на срочную военную службу в апреле-июне 2002 года в Вооруженные Силы Республики Казахстан
  kaz: ҚР Қарулы Күштері қатарына мерзімді әскери кызметке 2002 жылғы сәуірі-маусым айларында 1975-1984 жылдары туылған азаматтарды кезекті шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-10
approved_by:
- '154000000003'
version_date:
  kaz: 2002-04-10
  rus: 2002-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/11986/kaz/10.04.2002
  rus: https://zan.gov.kz/client/#!/doc/11986/rus/10.04.2002
