act_code: '39480'
requisite: Алматы облысы Ақсу ауданы әкімінің 2008 жылғы 30 сәуірдегі № 1 шешімі. Алматы облысының Әділет департаменті Ақсу ауданының әділет басқармасында 2008 жылы 8 мамырда № 2-4-71 тіркелді
title:
  rus: Жаңалық ауылындағы Жеңістің 40 жылдық көшесінің атауын Шатырбай Бәтенов көшесі атауына өзгерту туралы
  kaz: Жаңалық ауылындағы Жеңістің 40 жылдық көшесінің атауын Шатырбай Бәтенов көшесі атауына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-30
approved_by:
- '154011005002'
version_date:
  kaz: 2008-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/39480/kaz/30.04.2008
