act_code: '38384'
requisite: Алматы облысы Қапшағай қалалық мәслихатының 2008 жылғы 21 ақпандағы № 50-9 шешімі. Алматы облысының Әділет департаменті Қапшағай қаласының Әділет басқармасында 2008 жылдың 18 наурызында № 2-2-61 тіркелді. Күші жойылды - Алматы облысы Қапшағай қалалық мәслихатының 2011 жылғы 28 қарашадағы № 303-61 шешімімен
title:
  rus: Қапшағай қаласы, Заречный және Шеңгелді селолық округтері бойынша табысы аз отбасыларға (азаматтарға) тұрғын үй көмегін көрсету мөлшері және тәртібін бекіту туралы
  kaz: Қапшағай қаласы, Заречный және Шеңгелді селолық округтері бойынша табысы аз отбасыларға (азаматтарға) тұрғын үй көмегін көрсету мөлшері және тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-21
approved_by:
- '154020000002'
version_date:
  kaz: 2009-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/38384/kaz/26.03.2009
caused_by:
  code: '45582'
  requisite: Алматы облысы Қапшағай қалалық мәслихатының 2009 жылғы 26 наурыздағы № 134-24 шешімі. Алматы облысының Әділет департаменті Қапшағай қаласының Әділет басқармасында 2009 жылдың 4 мамырында № 2-2-82 тіркелді. Күші жойылды - Алматы облысы Қапшағай қалалық мәслихатының 2011 жылғы 28 қарашадағы № 303-61 шешімімен
  title:
    rus: Қапшағай қалалық мәслихатының 2008 жылғы 21 ақпандағы  «Қапшағай қаласы, Заречный және Шеңгелді селолық округтері бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету мөлшері  және тәртібін бекіту туралы» № 50-9 шешіміне өзгерістер енгізу туралы
    kaz: Қапшағай қалалық мәслихатының 2008 жылғы 21 ақпандағы  «Қапшағай қаласы, Заречный және Шеңгелді селолық округтері бойынша аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету мөлшері  және тәртібін бекіту туралы» № 50-9 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45582/rus
