act_code: '117374'
requisite: Решение Алматинского областного маслихата от 15 декабря 2017 года № 26-128. Зарегистрировано Департаментом юстиции Алматинской области 27 декабря 2017 года № 4452
title:
  rus: Об областном бюджете Алматинской области на 2018-2020 годы
  kaz: Алматы облысының 2018-2020 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-15
approved_by:
- '154000000002'
version_date:
  kaz: 2018-02-20
  rus: 2018-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117374/kaz/20.02.2018
  rus: https://zan.gov.kz/client/#!/doc/117374/rus/20.02.2018
caused_by:
  code: '119461'
  requisite: Решение Алматинского областного маслихата от 20 февраля 2018 года № 27-136. Зарегистрировано Департаментом юстиции Алматинской области 7 марта 2018 года № 4540
  title:
    rus: О внесении изменений и дополнения в решение Алматинского областного маслихата от 15 декабря 2017 года № 26-128 «Об областном бюджете Алматинской области на 2018-2020 годы»
    kaz: Алматы облыстық мәслихатының 2017 жылғы 15 желтоқсандағы «Алматы облысының 2018-2020 жылдарға арналған облыстық бюджеті туралы» № 26-128  шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119461/rus
