act_code: '54705'
requisite: Алматы облысы Алакөл ауданы Қабанбай ауылдық округі әкімінің 2010 жылғы 27 тамыздағы № 44 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 01 қазанда № 2-5-119 тіркелді
title:
  rus: Қабанбай ауылындағы Абылай хан көшесіндегі саябаққа Әнуар Әлімжановтың атын қою туралы
  kaz: Қабанбай ауылындағы Абылай хан көшесіндегі саябаққа Әнуар Әлімжановтың атын қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-27
approved_by:
- '154003014002'
version_date:
  kaz: 2010-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54705/kaz/27.08.2010
