act_code: '1470'
requisite: Решение акима Алматинской области от 16 июня 1997 года № 6-202. Зарегистрировано Управлением юстиции Алматинской области 17 августа 1998 года № 38. Утратило силу решением акима Алматинской области от 29 сентября 2004 года № 9-96
title:
  rus: О реализации Постановления Правительства Республики Казахстан от 29 мая 1997 года "Об упорядочении применения норм потребления тепла, горячей и холодной воды"
  kaz: Қазақстан Республикасы Үкiметiнiң 1997 жылғы 29 мамырдағы "Жылу, ыстық су және суық суды тұтыну нормаларын пайдалануды ретке келтiру туралы" Қаулысын iске асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-06-15
approved_by:
- '154000000003'
version_date:
  kaz: 1997-06-15
  rus: 1997-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/1470/kaz/15.06.1997
  rus: https://zan.gov.kz/client/#!/doc/1470/rus/15.06.1997
