act_code: '136940'
requisite: Решение акима Балтабайского сельского округа Енбекшиказахского района Алматинской области от 10 декабря 2019 года № 54. Зарегистрировано Департаментом юстиции Алматинской области 11 декабря 2019 года № 5321
title:
  rus: О переименовании улиц в селах Акбастау, Актогай, Балтабай, Бирлик и Куш Балтабайского сельского округа
  kaz: Балтабай ауылдық округінің Ақбастау, Ақтоғай, Балтабай, Бірлік және Күш ауылдарының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-10
approved_by:
- '154012004002'
version_date:
  kaz: 2019-12-10
  rus: 2019-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/136940/kaz/10.12.2019
  rus: https://zan.gov.kz/client/#!/doc/136940/rus/10.12.2019
