act_code: '18764'
requisite: Решение маслихата Алматинской области от 25 декабря 2003 года № 3-19. Зарегистрировано Департаментом юстиции Алматинской области 28 января 2004 года № 1467. Утратило силу решением маслихата Алматинской области от 07 декабря 2012 года № 12-72
title:
  rus: Об установлении ставок платежей за лесные пользования
  kaz: Орманды пайдалану үшін төлем ақы мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-25
approved_by:
- '154000000002'
version_date:
  kaz: 2004-06-23
  rus: 2004-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/18764/kaz/23.06.2004
  rus: https://zan.gov.kz/client/#!/doc/18764/rus/23.06.2004
caused_by:
  code: '20824'
  requisite: Решение маслихата Алматинской области от 24 июня 2004 года № 7-54. Зарегистрировано Департаментом юстиции Алматинской области 30 июля 2004 года № 1714. Утратило силу решением маслихата Алматинской области от 07 декабря 2012 года № 12-72
  title:
    rus: О внесении изменений в решение областного Маслихата N 3-19 от 25 декабря 2003 года "Об установлении ставок платежей за лесные пользования" зарегистрированного в департаменте юстиции N 1467 от 28 января 2004 года
    kaz: Әділет департаментінде 2004 ж. 28 қаңтарда 1467 нөмірмен тіркелген облыстык Мәслихаттың 2003 ж. 25 желтоқсандағы "Орманды пайдалану үшін төлем ақы белгілеу туралы" N 3-19 шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/20824/rus
