act_code: '153867'
requisite: Решение Жамбылского районного маслихата Алматинской области от 15 марта 2021 года № 3-15. Зарегистрировано Департаментом юстиции Алматинской области 29 марта 2021 года № 5904
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, культуры, являющимся гражданскими служащими и работающим в сельских населенных пунктах Жамбылского района
  kaz: Жамбыл ауданының азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-15
approved_by:
- '154018000002'
version_date:
  kaz: 2021-03-15
  rus: 2021-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/153867/kaz/15.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153867/rus/15.03.2021
