act_code: '87430'
requisite: Решение Сарканского районного маслихата Алматинской области от 12 февраля 2015 года № 50-254. Зарегистрировано Департаментом юстиции Алматинской области от 11 марта 2015 года № 3095. Утратило силу решением Сарканского районного маслихата Алматинской области от 19 января 2016 года № 64-333
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам)  Сарканского района
  kaz: Сарқан ауданындағы  аз қамтылған отбасыларға  (азаматтарға) тұрғын үй  көмегін көрсетудің мөлшерін және тәртібін айқындау  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-12
approved_by:
- '154005000002'
version_date:
  kaz: 2015-02-12
  rus: 2015-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/87430/kaz/12.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87430/rus/12.02.2015
