act_code: '59472'
requisite: Решение акима Кегенского сельского округа Райымбекского района Алматинской области от 31 мая 2011 года № 5-53. Зарегистрировано Управлением юстиции Райымбекского района Департамента юстиции Алматинской области 30 июня 2011 № 2-15-105
title:
  rus: О присвоении одной из улиц села Кеген имени Рабата Мамбетова
  kaz: Кеген ауылындағы бір көшеге Рабат Мәмбетовтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-05-31
approved_by:
- '154016023001'
version_date:
  kaz: 2011-05-31
  rus: 2011-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/59472/kaz/31.05.2011
  rus: https://zan.gov.kz/client/#!/doc/59472/rus/31.05.2011
