act_code: '127353'
requisite: Решение Текелийского городского маслихата Алматинской области от 11 декабря 2018 года № 31-191. Зарегистрировано Департаментом юстиции Алматинской области 20 декабря 2018 года № 4967. Утратило силу решением Текелийского городского маслихата Алматинской области от 26 мая 2020 года № 47-282
title:
  rus: Об установлении единых ставок фиксированного налога по городу Текели
  kaz: Текелі қаласы бойынша бірыңғай тіркелген салық мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-11
approved_by:
- '154019000002'
version_date:
  kaz: 2018-12-11
  rus: 2018-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/127353/kaz/11.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127353/rus/11.12.2018
