act_code: '106047'
requisite: Решение Текелийского городского маслихата Алматинской области от 02 августа 2016 года № 7-38. Зарегистрировано Департаментом юстиции Алматинской области 29 августа 2016 года № 3946. Утратило силу решением Текелийского городского маслихата Алматинской области от 27 марта 2018 года № 23-151
title:
  rus: Об утверждении Правил оказания социальной помощи установления размеров и определения перечня отдельных категорий нуждающихся граждан города Текели
  kaz: Текелі қаласының әлеуметтік көмек көрсетудің оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-08-02
approved_by:
- '154019000002'
version_date:
  kaz: 2016-08-02
  rus: 2016-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/106047/kaz/02.08.2016
  rus: https://zan.gov.kz/client/#!/doc/106047/rus/02.08.2016
