act_code: '43238'
requisite: Алматы облысы Сарқан аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 18-105 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының әділет басқармасында 2008 жылғы 26 желтоқсанда № 2-17-66 тіркелді
title:
  rus: Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '154005000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43238/kaz/19.12.2008
