act_code: '43238'
requisite: Алматы облысы Сарқан аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 18-105 шешімі. Алматы облысының Әділет департаменті Сарқан ауданының әділет басқармасында 2008 жылғы 26 желтоқсанда № 2-17-66 тіркелді
title:
  rus: Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '154005000002'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43238/kaz/26.11.2009
caused_by:
  code: '48932'
  requisite: Алматы облысы Сарқан аудандық мәслихатының 2009 жылғы 26 қарашадағы N 28-180 шешімі. Алматы облысының Әдідет департаменті Сарқан ауданының Әділет басқармасында 2009 жылы 2 желтоқсанда N 2-17-78 тіркелді
  title:
    rus: '"Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы" Сарқан аудандық мәслихатының 2008 жылғы 19 желтоқсандағы N 18-105 шешіміне өзгерістер енгізу туралы'
    kaz: '"Сарқан ауданының 2009 жылға арналған аудандық бюджеті туралы" Сарқан аудандық мәслихатының 2008 жылғы 19 желтоқсандағы N 18-105 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48932/rus
