act_code: '226541'
requisite: Решение акима Карасуского сельского округа Аксуского района области Жетісу от 11 июня 2026 года № 7
title:
  rus: Карасуский сельский округ, село Кенжыра о присвоении наименования улице Туыстастык
  kaz: Қарасу ауылдық округі, Кеңжыра ауылы Туыстастық көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-11
approved_by:
- '154011009002'
version_date:
  kaz: 2026-06-11
  rus: 2026-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/226541/kaz/11.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226541/rus/11.06.2026
