act_code: '221720'
requisite: Решение акима Аватского сельского округа Уйгурского района Алматинской области от 8 января 2026 года № 01-01
title:
  rus: О присвоении наименования улице села Ават, Аватского сельского округа
  kaz: Ават ауылдық округі Ават ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-08
approved_by:
- '154008001002'
version_date:
  kaz: 2026-01-08
  rus: 2026-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/221720/kaz/08.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221720/rus/08.01.2026
