act_code: '54557'
requisite: Алматы облысы Жамбыл ауданы Жамбыл селолық округінің әкімінің 2010 жылғы 13 қыркүйектегі № 9-140 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 20 қыркүйекте № 2-7-110 тіркелді
title:
  rus: Жамбыл селолық округіне қарасты жаңа құрылыс жерлеріне жаңадан көше атауларын беру туралы
  kaz: Жамбыл селолық округіне қарасты жаңа құрылыс жерлеріне жаңадан көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-13
approved_by:
- '154018008002'
version_date:
  kaz: 2010-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/54557/kaz/13.09.2010
