act_code: '56429'
requisite: Алматы облысы Қапшағай аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 242-48 шешімі. Алматы облысы Қапшағай қаласының Әділет басқармасында 2010 жылдың 30 желтоқсанда № 2-2-114 тіркелді. Күші жойылды - Алматы облысы Қапшағай аудандық мәслихатының 2012 жылғы 09 қазандағы № 7-44 шешімімен
title:
  rus: Қапшағай қаласының 2011-2013 жылдарға арналған қалалық бюджеті туралы
  kaz: Қапшағай қаласының 2011-2013 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '154020000002'
version_date:
  kaz: 2011-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56429/kaz/18.03.2011
caused_by:
  code: '57887'
  requisite: Решение Капчагайского городского маслихата от 18 марта 2011 года № 256-53. Зарегистрировано Управлением юстиции города Капшагай 31 марта 2011 года за № 2-2-118. Утратило силу - Решением Капчагайского городского маслихата от 09 октября 2012 года № 7-44
  title:
    rus: О внесении изменений в решение городского маслихата от 22 декабря 2010 года N 242-48 "О городском бюджете города Капшагай на 2011-2013 годы"
    kaz: '"Қапшағай қаласының 2011-2013 жылдарға арналған қалалық бюджеті туралы" қалалық мәслихаттың 2010 жылғы 22 желтоқсандағы N 242-48 шешіміне өзгертулер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57887/rus
