act_code: '54048'
requisite: Алматы облысы Іле ауданы Чапаев ауылының әкімінің 2010 жылғы 27 шілдедегі № 2 шешімі. Алматы облысы Іле ауданының Әділет басқармасында 2010 жылғы 9 тамызда № 2-10-123 тіркелді
title:
  rus: Чапаев ауылының жаңа көшелеріне атауларын беру туралы
  kaz: Чапаев ауылының жаңа көшелеріне атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-27
approved_by:
- '154017010002'
version_date:
  kaz: 2010-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54048/kaz/27.07.2010
