act_code: '56478'
requisite: Алматы облысы Балқаш аудандық мәслихатының 2010 жылғы 27 желтоқсандағы № 41-192 шешімі. Алматы облысының Әділет департаменті Балқаш ауданының Әділет басқармасында 2010 жылы 31 желтоқсанда № 2-6-78 тіркелді
title:
  rus: Балқаш ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Балқаш ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-27
approved_by:
- '154014000002'
version_date:
  kaz: 2011-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56478/kaz/15.04.2011
caused_by:
  code: '58395'
  requisite: Решение маслихата Балхашского района Алматинской области от 15 апреля 2011 года № 46-216. Зарегистрировано Управлением юстиции Балхашского района Департамента юстиции Алматинской области 19 апреля 2011 года № 2-6-85
  title:
    rus: О внесении изменений в решение Балхашского районного маслихата от 27 декабря 2010 года N 41-192 "О районном бюджете Балхашского района на 2011-2013 годы"
    kaz: Балқаш аудандық мәслихатының 2010 жылғы 27 желтоқсандағы "Балқаш ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" N 41-192 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58395/rus
