act_code: '96819'
requisite: Решение акима Коксуского района Алматинской области от 11 декабря 2015 года № 12-27. Зарегистрировано Департаментом юстиции Алматинской области 23 декабря 2015 года № 3635. Утратило силу решением акима Коксуского района Алматинской области от 28 декабря 2018 года № 12-189
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Коксускому району
  kaz: Көксу ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '154007000001'
version_date:
  kaz: 2015-12-11
  rus: 2015-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/96819/kaz/11.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96819/rus/11.12.2015
