act_code: '159703'
requisite: Решение Кегенского районного маслихата Алматинской области от 30 сентября 2021 года № 15-56
title:
  rus: Об утверждении Регламентов собраний местных сообществ сельских округов Кегенского района
  kaz: Кеген ауданының ауылдық округтерінің  жергілікті қоғамдастық жиналыстарының регламенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2021-09-30
approved_by:
- '154021000002'
version_date:
  kaz: 2021-09-30
  rus: 2021-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/159703/kaz/30.09.2021
  rus: https://zan.gov.kz/client/#!/doc/159703/rus/30.09.2021
