act_code: '138646'
requisite: Решение Панфиловского районного маслихата Алматинской области от 9 января 2020 года № 6-66-381. Зарегистрировано Департаментом юстиции Алматинской области 16 января 2020 года № 5399
title:
  rus: О бюджетах города Жаркент и сельских округов Панфиловского района на 2020-2022 годы
  kaz: Панфилов ауданының Жаркент қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '154004000002'
version_date:
  kaz: 2020-11-20
  rus: 2020-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/138646/kaz/20.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138646/rus/20.11.2020
caused_by:
  code: '149016'
  requisite: Решение Панфиловского районного маслихата Алматинской области от 20 ноября 2020 года № 6-79-436. Зарегистрировано Департаментом юстиции Алматинской области 26 ноября 2020 года № 5768
  title:
    rus: О внесении изменений в решение Панфиловского районного маслихата от 9 января 2020 года № 6-66-381 «О бюджетах города Жаркент и сельских округов Панфиловского района  на 2020-2022 годы»
    kaz: Панфилов аудандық мәслихатының 2020 жылғы 9 қаңтардағы № 6-66-381 «Панфилов ауданының Жаркент қаласы мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149016/rus
