act_code: '48262'
requisite: Алматы облысы Талғар ауданы Алатау ауылдық округі әкімінің 2009 жылғы 28 қыркүйектегі № 73 шешімі. Алматы облысы Талғар ауданының Әділет басқармасында 2009 жылдың 19 қазанында № 2-18-93 тіркелді
title:
  rus: Алатау ауылдық округінің елді мекендеріндегі көшелердің аттарын бекіту туралы
  kaz: Алатау ауылдық округінің елді мекендеріндегі көшелердің аттарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-28
approved_by:
- '154013001001'
version_date:
  kaz: 2009-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/48262/kaz/28.09.2009
