act_code: '206401'
requisite: Решение Кегенского районного маслихата Алматинской области от 30 декабря 2024 года № 29-127
title:
  rus: «О бюджете Кегенского района на 2025-2027 годы"
  kaz: «Кеген ауданының 2025-2027 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '154021000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206401/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206401/rus/30.12.2024
