act_code: '52850'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2010 жылғы 14 сәуірдегі № 173 шешімі. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2010 жылы 20 мамырда № 2-1-122 тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2012 жылғы 25 шілдедегі № 60 шешімімен
title:
  rus: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '154002000002'
version_date:
  kaz: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52850/kaz/14.04.2010
