act_code: '206474'
requisite: Решение Райымбекского районного маслихата Алматинской области от 8 января 2025 года № 37-200
title:
  rus: О бюджетах сельских округов Райымбекского района на 2025-2027 годы
  kaz: Райымбек ауданының ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-08
approved_by:
- '154016000002'
version_date:
  kaz: 2025-01-08
  rus: 2025-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/206474/kaz/08.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206474/rus/08.01.2025
