act_code: '53141'
requisite: Алматы облысы Алакөл ауданы Теректі ауылдық округі әкімінің 2010 жылғы 19 мамырдағы № 11 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 10 маусымда № 2-5-107 тіркелді
title:
  rus: Теректі ауылындағы көше атауларын өзгерту туралы
  kaz: Теректі ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-19
approved_by:
- '154003019002'
version_date:
  kaz: 2010-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/53141/kaz/19.05.2010
