act_code: '53144'
requisite: Алматы облысы Алакөл ауданы Үшбұлақ ауылдық округі әкімінің 2010 жылғы 10 маусымдағы № 02 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 16 маусымда № 2-5-110 тіркелді
title:
  rus: Үшбұлақ ауылындағы көше атауларын өзгерту туралы
  kaz: Үшбұлақ ауылындағы көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-10
approved_by:
- '154003021002'
version_date:
  kaz: 2010-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/53144/kaz/10.06.2010
