act_code: '4328'
requisite: Решение акима Алматинской области от 26 апреля 1999 года № 4-122. Зарегистрировано Управлением юстиции Алматинской области 20 сентября 1999 года № 121. Утратило силу решением акима Алматинской области от 21 октября 2003 года № 10-157
title:
  rus: О присвоении категории оптово-розничному рынку «Мамыр» Карасайского района
  kaz: Қарасай ауданының "Мамыр" кұтерме-бұлшек сауда базарына категория беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-25
approved_by:
- '154000000003'
version_date:
  kaz: 1999-04-25
  rus: 1999-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/4328/kaz/25.04.1999
  rus: https://zan.gov.kz/client/#!/doc/4328/rus/25.04.1999
