act_code: '55785'
requisite: Алматы облысы Еңбекшіқазақ ауданы Бөлек селолық округі әкімінің 2010 жылғы 03 желтоқсандағы № 15 шешімі. Алматы облысы Еңбекшіқазақ ауданының Әділет басқармасында 2010 жылы 09 желтоқсанда № 2-8-166 тіркелді
title:
  rus: Бөлек селолық округінің Бөлек ауылындағы көшелерінің атауларын өзгерту туралы
  kaz: Бөлек селолық округінің Бөлек ауылындағы көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-03
approved_by:
- '154012005002'
version_date:
  kaz: 2010-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55785/kaz/03.12.2010
