act_code: '14177'
requisite: Алматы облысы әкімінің 2002 жылғы 27 желтоқсандағы № 12-334 шешімі. Алматы облыстық Әділет басқармасында 2003 жылғы 10 қаңтарда № 973 тіркелді
title:
  rus: 1986 жылы туылған азаматтарды шақыру учаскелеріне тізімге алу және жастарды жедел әскери қызметке шақыруға дайындау туралы
  kaz: 1986 жылы туылған азаматтарды шақыру учаскелеріне тізімге алу және жастарды жедел әскери қызметке шақыруға дайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-27
approved_by:
- '154000000003'
version_date:
  kaz: 2002-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/14177/kaz/27.12.2002
