act_code: '49937'
requisite: Алматы облысы Ескелді аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 33-197 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2009 жылы 30 желтоқсанда № 2-9-92 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2011 жылғы 24 маусымдағы № 54-322 шешімімен
title:
  rus: Ескелді ауданының 2010-2012 жылдарының бюджеті туралы
  kaz: Ескелді ауданының 2010-2012 жылдарының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '154006000002'
version_date:
  kaz: 2010-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49937/kaz/23.08.2010
caused_by:
  code: '54233'
  requisite: Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 23 тамыздағы № 42-260 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының Әділет басқармасында 2010 жылы 27 тамызда № 2-9-112 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2011 жылғы 24 маусымдағы № 54-322 шешімімен
  title:
    rus: Ескелді ауданы мәслихатының 2009 жылғы 21 желтоқсандағы 33-197 санды "Ескелді ауданының 2010-2012 жылдарының бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Ескелді ауданы мәслихатының 2009 жылғы 21 желтоқсандағы 33-197 санды "Ескелді ауданының 2010-2012 жылдарының бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54233/rus
