act_code: '148397'
requisite: Решение Илийского районного маслихата Алматинской области от 5 ноября 2020 года № 65-261. Зарегистрировано Департаментом юстиции Алматинской области 9 ноября 2020 года № 5734
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Илийском районе
  kaz: Іле ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-05
approved_by:
- '154017000002'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/148397/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/148397/rus/13.06.2023
caused_by:
  code: '183086'
  requisite: Решение Илийского районного маслихата Алматинской области от 13 июня 2023 года № 6-21. Зарегистрировано Департаментом юстиции Алматинской области 15 июня 2023 года № 6016-05
  title:
    rus: О внесении изменений и дополнения в решение Илийского районного маслихата от 5 ноября 2020 года № 65-261 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Илийском районе»
    kaz: Іле аудандық мәслихатының 2020 жылғы 5 қарашадағы № 65-261 «Іле ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183086/rus
