act_code: '149374'
requisite: Решение акима Карасайского района Алматинской области от 27 ноября 2020 года № 8. Зарегистрировано Департаментом юстиции Алматинской области 30 ноября 2020 года № 5783. Утратило силу решением акима Карасайского района Алматинской области от 20 марта 2025 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Карасайскому району
  kaz: Қарасай ауданында дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-27
approved_by:
- '154015000003'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/149374/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/149374/rus/29.12.2022
caused_by:
  code: '176821'
  requisite: Решение акима Карасайского района Алматинской области от 29 декабря 2022 года № 4. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2022 года № 31462. Утратило силу решением акима Карасайского района Алматинской области от 20 марта 2025 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Карасайского района от 27 ноября 2020 года № 8 «Об образовании избирательных участков для проведения голосования и подсчета голосов по Карасайскому району»
    kaz: Қарасай ауданы әкімінің 2020 жылғы 27 қарашадағы № 8 «Қарасай ауданында дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176821/rus
