act_code: '43347'
requisite: Алматы облысы Ескелді аудандық мәслихат хатшысының 2008 жылғы 22 желтоқсандағы № 18-107 шешімі. Алматы облысының Әділет департаменті Ескелді ауданының әділет басқармасында 2009 жылғы 8 қаңтарда № 2-9-73 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 14 мамырдағы № 39-244 шешімімен
title:
  rus: Ескелді ауданының 2009 жылға арналған аудандық бюджеті туралы
  kaz: Ескелді ауданының 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '154006000002'
version_date:
  kaz: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43347/kaz/22.04.2009
caused_by:
  code: '45429'
  requisite: Алматы облысы Ескелді аудандық мәслихатының 2009 жылғы 22 сәуірдегі № 24-154 шешімі. Алматы облысының әділет департаменті Ескелді ауданының әділет басқармасында 2009 жылы 23 сәуірде № 2-9-83 тіркелді. Күші жойылды - Алматы облысы Ескелді аудандық мәслихатының 2010 жылғы 14 мамырдағы № 39-244 шешімімен
  title:
    rus: Ескелді ауданы мәслихатының 2008 жылғы 22 желтоқсандағы 18-107 санды "Ескелді ауданының 2009 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Ескелді ауданы мәслихатының 2008 жылғы 22 желтоқсандағы 18-107 санды "Ескелді ауданының 2009 жылға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45429/rus
