act_code: '97440'
requisite: Решение от 18.01.2016 , Аким Арасанского сельского округа. Зарегистрировано Департаментом юстиции Алматинской области 30 декабря 2015 года № 3667
title:
  rus: 'О переименовании улиц «Бейбитшилик», «Садовая», «Арычная» и улицу «Жансугурова» с № 39 по № 50 в селе Арасан Арасанского сельского округа '
  kaz: Арасан ауылдық округінің Арасан ауылындағы «Бейбітшілік», «Садовая», «Арычная» көшелері және «Жансүгіров» көшесі № 39 дан № 50 ге дейінгі аралықты қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '154011002001'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97440/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97440/rus/24.12.2015
