act_code: '103232'
requisite: Решение Талгарского районного маслихата Алматинской области от 06 мая 2016 года № 3-17. Зарегистрировано Департаментом юстиции Алматинской области 03 июня 2016 года № 3879. Утратило силу решением Талгарского районного маслихата Алматинской области от 3 марта 2021 года № 3-14
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Талгарском районе
  kaz: Талғар ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2016-05-06
approved_by:
- '154013000002'
version_date:
  kaz: 2016-05-06
  rus: 2016-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/103232/kaz/06.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103232/rus/06.05.2016
