act_code: '138473'
requisite: Решение Уйгурского районного маслихата Алматинской области от 27 декабря 2019 года № 6-59-340. Зарегистрировано Департаментом юстиции Алматинской области 10 января 2020 года № 5388
title:
  rus: О бюджете Уйгурского района на 2020-2022 годы
  kaz: Ұйғыр ауданының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '154008000002'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138473/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138473/rus/08.09.2020
caused_by:
  code: '146368'
  requisite: Решение Уйгурского районного маслихата Алматинской области от 8 сентября 2020 года № 6-68-392. Зарегистрировано Департаментом юстиции Алматинской области 16 сентября 2020 года № 5661
  title:
    rus: О внесений изменений в решение Уйгурского районного маслихата от 27 декабря 2019 года № 6-59-340 «О бюджете Уйгурского района на 2020-2022 годы»
    kaz: Ұйғыр аудандық мәслихатының 2019 жылғы 27 желтоқсандағы № 6-59-340 «Ұйғыр ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146368/rus
