act_code: '79763'
requisite: Решение Коксуского районного маслихата Алматинской области от 11 апреля 2014 года N 28-4. Зарегистрировано Департаментом юстиции Алматинской области 28 апреля 2014 года N 2686. Утратило силу решением Коксуского районного маслихата области Жетісу от 6 октября 2023 года № 11-48
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества  и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Коксуском районе
  kaz: Көксу ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2014-04-11
approved_by:
- '154007000002'
version_date:
  kaz: 2014-04-11
  rus: 2014-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/79763/kaz/11.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79763/rus/11.04.2014
