act_code: '9194'
requisite: Решение акима Алматинской области от 3 мая 2001 года № 5-113. Зарегистрировано Управлением юстиции Алматинской области 24 мая 2001 года № 366. Утратило силу решением акима Алматинской области от 30 июня 2004 года № 6-64
title:
  rus: О мерах по усилению государственного контроля за охраной растительного мира
  kaz: Өсімдіктер дүниесін қорғауға мемлекеттік бақылауды күшейту шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-02
approved_by:
- '154000000003'
version_date:
  kaz: 2001-05-02
  rus: 2001-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/9194/kaz/02.05.2001
  rus: https://zan.gov.kz/client/#!/doc/9194/rus/02.05.2001
