act_code: '34969'
requisite: Алматы облысы Іле аудандық мәслихатының 2007 жылғы 10 шілдедегі № 58-213 шешімі. Алматы облысының Әділет департаменті Іле ауданының Әділет басқармасында 2007 жылы 21 тамызда № 2-10-59 тіркелген
title:
  rus: Іле ауданы жерлерінің қала құрылысы аумақтарын (аумақтарға бөлу сызбасын) дамытудың схемасын бекіту туралы
  kaz: Іле ауданы жерлерінің қала құрылысы аумақтарын (аумақтарға бөлу сызбасын) дамытудың схемасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2007-07-10
approved_by:
- '154017000002'
version_date:
  kaz: 2007-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/34969/kaz/10.07.2007
