act_code: '106016'
requisite: Решение Уйгурского районного маслихата Алматинской области от 20 июля 2016 года № 6-5-36. Зарегистрировано Департаментом юстиции Алматинской области 18 августа 2016 года № 3933. Утратило силу решением Уйгурского районного маслихата Алматинской области от 2 апреля 2018 года № 6-29-177
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Уйгурского района
  kaz: Ұйғыр ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-07-20
approved_by:
- '154008000002'
version_date:
  kaz: 2016-07-20
  rus: 2016-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/106016/kaz/20.07.2016
  rus: https://zan.gov.kz/client/#!/doc/106016/rus/20.07.2016
