act_code: '26430'
requisite: Решение маслихата Алматинской области от 6 декабря 2005 года № 24-166. Зарегистрировано Департаментом юстиции Алматинской области 13 января 2006 года № 1957. Утратило силу решением маслихата Алматинской области от 29 декабря 2008 года № 16-105
title:
  rus: Об утверждении ставок акциза на игорный бизнес
  kaz: Ойын бизнесінің акциз ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '154000000002'
version_date:
  kaz: 2005-12-06
  rus: 2005-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26430/kaz/06.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26430/rus/06.12.2005
