act_code: '170408'
requisite: Решение акима Уйгурского района Алматинской области от 1 августа 2022 года № 21. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 августа 2022 года № 28997. Утратило силу решением акима Уйгурского района Алматинской области от 2 июля 2024 года № 233
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-01
approved_by:
- '154008000003'
version_date:
  kaz: 2022-08-01
  rus: 2022-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/170408/kaz/01.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170408/rus/01.08.2022
