act_code: '1811'
requisite: Решение акима Алматинской области от 2 апреля 1997 года № 4-94. Зарегистрировано Управлением юстиции Алматинской области 20 августа 1998 года № 43. Утратило силу решением акима Алматинской области от 8 мая 2001 года № 5-120
title:
  rus: О мерах по обеспечению в области безопасной эксплуатации газового оборудования на производстве и в быту
  kaz: Облыста газ жабдықтарын өндіріс пен тұрмыста пайдаланудың қауіпсіздігін қамтамасыз ету жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-04-01
approved_by:
- '154000000003'
version_date:
  kaz: 1997-04-01
  rus: 1997-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/1811/kaz/01.04.1997
  rus: https://zan.gov.kz/client/#!/doc/1811/rus/01.04.1997
