act_code: '97601'
requisite: Решение акима Казахстанского сельского округа Таскалинского района Западно-Казахстанской области от 25 декабря 2015 года № 7
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '154012009001'
version_date:
  kaz: 2015-12-25
  rus: 2015-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/97601/kaz/25.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97601/rus/25.12.2015
