act_code: '56885'
requisite: Алматы облысы Көксу ауданы әкімінің 2010 жылғы 15 желтоқсандағы № 12-25 шешімі. Алматы облысының Әділет департаменті Көксу ауданының Әділет басқармасында 2011 жылы 18 қаңтарда № 2-14-103 тіркелді. Күші жойылды - Алматы облысы Көксу ауданы әкімінің 2011 жылғы 28 желтоқсандағы № 12-48 шешімімен
title:
  rus: 1994 жылы туылған азаматтарды әскери шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
  kaz: 1994 жылы туылған азаматтарды әскери шақыру учаскелерінде тіркеуге алуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '154007000001'
version_date:
  kaz: 2010-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56885/kaz/15.12.2010
