act_code: '179445'
requisite: Решение акима Белбулакского сельского округа Талгарского района Алматинской области от 30 марта 2023 года № 03. Зарегистрировано Департаментом юстиции Алматинской области 4 апреля 2023 года № 5975-05
title:
  rus: О переименовании и присвоении новых наименований улиц в населенных пунктах Белбулакского сельского округа
  kaz: Белбұлақ ауылдық округінің елді мекендерінің көшелеріне қайта атау және жаңа атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-30
approved_by:
- '154013002002'
version_date:
  kaz: 2023-03-30
  rus: 2023-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/179445/kaz/30.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179445/rus/30.03.2023
