act_code: '206003'
requisite: Решение Карасайского районного маслихата Алматинской области от 30 декабря 2024 года № 30-3
title:
  rus: О бюджетах города, сельских округов Карасайского района на 2025-2027 годы
  kaz: Қарасай ауданының қала, ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '154015000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206003/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206003/rus/30.12.2024
