act_code: '213396'
requisite: Решение Уйгурского районного маслихата Алматинской области от 8 августа 2025 года № 8-45-215
title:
  rus: О повышении базовых ставок земельного налога по Уйгурскому району
  kaz: Ұйғыр ауданы бойынша жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-08
approved_by:
- '154008000002'
version_date:
  kaz: 2025-08-08
  rus: 2025-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/213396/kaz/08.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213396/rus/08.08.2025
