act_code: '62130'
requisite: Решение маслихата Панфиловского района Алматинской области от 8 декабря 2011 года № 4-54-337. Зарегистрировано Управлением юстиции Панфиловского района Департамента юстиции Алматинской области 14 декабря 2011 года № 2-16-144. Утратило силу решением маслихата Панфиловского района Алматинской области от 05 декабря 2012 года № 5-24-165
title:
  rus: Об установлении единых ставок фиксированного налога по Панфиловскому району на 2012-2013 года
  kaz: Панфилов ауданы бойынша бірыңғай тіркелген салық ставкаларын 2012-2013 жылдарға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-08
approved_by:
- '154004000002'
version_date:
  kaz: 2011-12-08
  rus: 2011-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/62130/kaz/08.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62130/rus/08.12.2011
