act_code: '226265'
requisite: Решение акима Баканасского сельского округа Балхашского района Алматинской области от 9 июня 2026 года № 01
title:
  rus: О наименовании новых улиц в Баканасском сельском округе
  kaz: Бақанас ауылдық округіндегі жаңа көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-09
approved_by:
- '154014016002'
version_date:
  kaz: 2026-06-09
  rus: 2026-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/226265/kaz/09.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226265/rus/09.06.2026
