act_code: '93510'
requisite: Решение акима Карасайского района Алматинской области от 03 августа 2015 года № 8-15. Зарегистрировано Департаментом юстиции Алматинской области 02 сентября 2015 года № 3373. Утратило силу решением акима Карасайского района Алматинской области от 13 декабря 2018 года № 7
title:
  rus: Об образовании избирательных участков для проведения голосования и подсчета голосов по Карасайскому району
  kaz: Қарасай ауданы бойынша дауыс беруді өткізу және дауыс санау үшін сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-08-03
approved_by:
- '154015000001'
version_date:
  kaz: 2015-08-03
  rus: 2015-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/93510/kaz/03.08.2015
  rus: https://zan.gov.kz/client/#!/doc/93510/rus/03.08.2015
