act_code: '38329'
requisite: Алматы облысы Ұйғыр аудандық мәслихатының 2008 жылғы 6 ақпандағы № 6-2 шешімі. Алматы облысының Әділет департаменті Ұйғыр ауданының Әділет басқармасында 2008 жылдың 12 наурызында № 2-19-53 тіркелді. Күші жойылды - Алматы облысы Ұйғыр аудандық мәслихатының 2009 жылғы 08 қаңтардағы № 18-6 шешімімен
title:
  rus: Ұйғыр ауданында аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
  kaz: Ұйғыр ауданында аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-06
approved_by:
- '154008000002'
version_date:
  kaz: 2008-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/38329/kaz/06.02.2008
