act_code: '91068'
requisite: Решение акима Алматинской области от 18 мая 2015 года № 5-5. Зарегистрировано Департаментом юстиции Алматинской области 18 июня 2015 № 3237
title:
  rus: Об определении объема субсидий по подаче воды сельскохозяйственным товаропроизводителям на 2015 год
  kaz: Ауыл шаруашылығы тауарын өндірушілерге 2015 жылға арналған су беру жөніндегі субсидия көлемін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-18
approved_by:
- '154000000003'
version_date:
  kaz: 2015-05-18
  rus: 2015-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/91068/kaz/18.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91068/rus/18.05.2015
