act_code: '44634'
requisite: Алматы облысы Талғар аудандық мәслихатының 2009 жылғы 30 қаңтардағы № 16-97 шешімі. Алматы облысының Әділет департаменті Талғар ауданының Әділет басқармасында 2009 жылы 3 наурызда № 2-18-80 тіркелді
title:
  rus: Талғар ауданы бойынша 2009 жылға арналған жер салығының базалық ставкаларын белгілеу туралы
  kaz: Талғар ауданы бойынша 2009 жылға арналған жер салығының базалық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '154013000002'
version_date:
  kaz: 2009-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/44634/kaz/30.01.2009
