act_code: '49559'
requisite: Решение маслихата Алматинской области от 9 декабря 2009 года № 26-162. Зарегистрировано Департаментом юстиции Алматинской области 25 декабря 2009 года № 2041
title:
  rus: Об областном бюджете Алматинской области на 2010-2012 годы
  kaz: Алматы облысының 2010-2012 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-09
approved_by:
- '154000000002'
version_date:
  kaz: 2010-03-25
  rus: 2010-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49559/kaz/25.03.2010
  rus: https://zan.gov.kz/client/#!/doc/49559/rus/25.03.2010
caused_by:
  code: '51521'
  requisite: Решение маслихата Алматинской области № 31-185 от 25 марта 2010 года. Зарегистрировано департаментом юстиции Алматинской области 30 марта 2010 года № 2047
  title:
    rus: О внесении изменений и дополнений в решение Алматинского областного маслихата от 9 декабря 2009 года N 26-162 "Об областном бюджете Алматинской области на 2010-2012 годы"
    kaz: Алматы облыстық мәслихатының 2009 жылғы 9 желтоқсандағы "Алматы облысының 2010-2012 жылдарға арналған облыстық бюджеті туралы" N 26-162 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51521/rus
