act_code: '56340'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 33-1 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 31 желтоқсанда № 2-5-136 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2012 жылғы 09 маусымдағы № 5-5 шешімімен
title:
  rus: Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджетi туралы
  kaz: Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '154003000002'
version_date:
  kaz: 2011-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/56340/kaz/13.04.2011
caused_by:
  code: '58448'
  requisite: Решение маслихата Алакольского района Алматинской области от 13 апреля 2011 года № 40-1. Зарегистрировано Управлением юстиции Алакольского района Департамента юстиции Алматинской области 25 апреля 2011 года № 2-5-147. Утратило силу - Решением маслихата Алакольского района Алматинской области от 09 июня 2012 года № 5-5
  title:
    rus: О внесении изменений и дополнений в решение Алакольского районного маслихата от 23 декабря 2010 г N 33-1 "О районном бюджете Алакольского района на 2011-2013 годы"
    kaz: Алакөл аудандық мәслихатының 2010 жылғы 23 желтоқсанындағы "Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" N 33-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58448/rus
