act_code: '56340'
requisite: Алматы облысы Алакөл аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 33-1 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 31 желтоқсанда № 2-5-136 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2012 жылғы 09 маусымдағы № 5-5 шешімімен
title:
  rus: Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджетi туралы
  kaz: Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджетi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '154003000002'
version_date:
  kaz: 2011-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/56340/kaz/18.02.2011
caused_by:
  code: '57384'
  requisite: Алматы облысы Алакөл аудандық мәслихатының 2011 жылғы 18 ақпандағы № 36-1 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2011 жылы 23 ақпанда № 2-5-143 тіркелді. Күші жойылды - Алматы облысы Алакөл аудандық мәслихатының 2012 жылғы 09 маусымдағы № 5-5 шешімімен
  title:
    rus: Алакөл аудандық мәслихатының 2010 жылғы 23 желтоқсанда қабылданған "Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" 33-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Алакөл аудандық мәслихатының 2010 жылғы 23 желтоқсанда қабылданған "Алакөл ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" 33-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57384/rus
