act_code: '152279'
requisite: Решение Сарканского районного маслихата Алматинской области от 13 января 2021 года № 94-360. Зарегистрировано Департаментом юстиции Алматинской области 19 января 2021 года № 5871
title:
  rus: О бюджетах города Саркан и сельских округов Сарканского района на 2021-2023 годы
  kaz: Сарқан ауданының Сарқан қаласы мен ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-13
approved_by:
- '154005000002'
version_date:
  kaz: 2021-09-14
  rus: 2021-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/152279/kaz/14.09.2021
  rus: https://zan.gov.kz/client/#!/doc/152279/rus/14.09.2021
caused_by:
  code: '158621'
  requisite: Решение Сарканского районного маслихата Алматинской области от 14 сентября 2021 года № 10-47
  title:
    rus: О внесении изменений в решение Сарканского районного маслихата от 13 января 2021 года № 94-360  «О бюджетах города Саркан и сельских округов Сарканского района на 2021-2023 годы»
    kaz: Сарқан аудандық мәслихатының 2021 жылғы 13 қаңтардағы № 94-360  «Сарқан ауданының Сарқан қаласы мен ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158621/rus
