act_code: '44079'
requisite: Алматы облысы маслихатының 2008 жылғы 29 желтоқсандағы № 16-101 шешімі. Алматы облысы Әділет департаментінде 2009 жылғы 6 ақпанда № 2026 тіркелді. Күші жойылды - Алматы облыстық мәслихатының 2018 жылғы 25 шілдедегі № 34-174 шешімімен
title:
  rus: Алматы облысында қоршаған ортаға эмиссиялар үшін төлемақы ставкаларын арттыру туралы
  kaz: Алматы облысында қоршаған ортаға эмиссиялар үшін төлемақы ставкаларын арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-29
approved_by:
- '154000000002'
version_date:
  kaz: 2008-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44079/kaz/29.12.2008
