act_code: '32514'
requisite: Алматы облысы Талдықорған қалалық мәслихатының 2007 жылғы 6 наурыздағы № 357 шешімі. Алматы облысының Әділет департаменті Талдықорған қаласының Әділет басқармасында 2007 жылы 29 наурызда № 2-1-41 болып тіркелді. Күші жойылды - Алматы облысы Талдықорған қалалық мәслихатының 2018 жылғы 28 ақпандағы № 156 шешімімен
title:
  rus: «Жер салығын қамтамсыз ету мақсатында жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы»
  kaz: «Жер салығын қамтамсыз ету мақсатында жерді аймақтарға бөлу жобасын (схемасын) бекіту туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-03-06
approved_by:
- '154002000002'
version_date:
  kaz: 2007-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/32514/kaz/06.03.2007
