act_code: '21004'
requisite: Решение маслихата Алматинской области от 3 июня 2004 года № 6-46. Зарегистрировано Департаментом юстиции Алматинской области 7 июля 2004 года № 1677. Утратило силу решением маслихата Алматинской области от 29 декабря 2008 года № 16-105
title:
  rus: О программе развития жилищного строительства в Алматинской области на 2005-2007 годы
  kaz: Алматы облысында 2005-2007 жылдары тұрғын үй құрылысын дамыту бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2004-06-02
approved_by:
- '154000000002'
version_date:
  kaz: 2004-12-21
  rus: 2004-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/21004/kaz/21.12.2004
  rus: https://zan.gov.kz/client/#!/doc/21004/rus/21.12.2004
caused_by:
  code: '22699'
  requisite: Решение маслихата Алматинской области от 21 декабря 2004 года № 13-87. Зарегистрировано Департаментом юстиции Алматинской области 21 января 2005 горда № 1846. Утратило силу решением маслихата Алматинской области от 29 декабря 2008 года № 16-105
  title:
    rus: О внесении изменений в решение № 6-46 от 03.06.2004 года областного Маслихата "О программе развития жилищного строительства в Алматинской области на 2005-2007 годы" зарегистрированного в департаменте юстиции за № 1677 от 17.07.2004 г.
    kaz: Әділет департаментінде 2004 жылдың 17-ші шілдесінде № 1677 болып тіркелген облыстық Мәслихаттың 2005-2007 жылдарға арналған Алматы облысында тұрғын үй құрылысын дамыту бағдарламасы туралы» 2004 жылғы 3-ші маусымдағы № 6-46 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/22699/rus
