act_code: '206173'
requisite: Решение Талгарского районного маслихата Алматинской области от 26 декабря 2024 года № 35-128
title:
  rus: О бюджете Талгарского района на 2025-2027 годы
  kaz: Талғар ауданының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '154013000002'
version_date:
  kaz: 2025-12-17
  rus: 2025-12-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/206173/kaz/17.12.2025
  rus: https://zan.gov.kz/client/#!/doc/206173/rus/17.12.2025
caused_by:
  code: '219615'
  requisite: Решение Талгарского районного маслихата Алматинской области от 17 декабря 2025 года № 51-206
  title:
    rus: О внесении изменений в решение Талгарского районного маслихата от 26 декабря 2024 года № 35-128 «О бюджете Талгарского района на 2025-2027 годы»
    kaz: «Талғар ауданының 2025-2027 жылдарға арналған бюджеті туралы» Талғар аудандық мәслихатының 2024 жылғы 26 желтоқсандағы № 35-128 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/219615/rus
