act_code: '51165'
requisite: Алматы облысы Жамбыл ауданы Қарғалы ауылдық округінің әкімінің 2010 жылғы 19 ақпандағы № 2-16 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 11 наурызда № 2-7-90 тіркелді
title:
  rus: Қарғалы ауылдық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру туралы
  kaz: Қарғалы ауылдық округіне қарасты жаңа құрылыс жерлерінде жаңадан көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-19
approved_by:
- '154018024002'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/51165/kaz/19.02.2010
