act_code: '46189'
requisite: Алматы облысы Еңбекшіқазақ ауданы Балтабай селолық округі әкімінің 2009 жылғы 8 мамырдағы № 61 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2009 жылы 28 мамырда № 2-8-111 тіркелді
title:
  rus: Еңбек селосындағы "Школьная" атындағы көшенің атауын "Жүнісбай Әлиасқаров" көшесі деп өзгерту туралы
  kaz: Еңбек селосындағы "Школьная" атындағы көшенің атауын "Жүнісбай Әлиасқаров" көшесі деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-07
approved_by:
- '154012004002'
version_date:
  kaz: 2009-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/46189/kaz/08.05.2009
