act_code: '49492'
requisite: Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 33-1 шешімі. Алматы облысының Әділет департаменті Еңбекшіқазақ ауданының Әділет басқармасында 2009 жылы 28 желтоқсанда № 2-8-132 тіркелді. Күші жойылды - Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2011 жылғы 17 қаңтардағы № 44-3 шешімімен
title:
  rus: Еңбекшіқазақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Еңбекшіқазақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '154012000002'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/49492/kaz/19.02.2010
caused_by:
  code: '50778'
  requisite: Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2010 жылғы 19 ақпандағы № 37-2 шешімі. Алматы облысының әділет департаменті Еңбекшіқазақ ауданының әділет басқармасында 2010 жылы 19 ақпанда № 2-8-137 тіркелді. Күші жойылды - Алматы облысы Еңбекшіқазақ аудандық мәслихатының 2011 жылғы 17 қаңтардағы № 44-3 шешімімен
  title:
    rus: 23 желтоқсан 2009 жылғы N 33-1 "Еңбекшіқазақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
    kaz: 23 желтоқсан 2009 жылғы N 33-1 "Еңбекшіқазақ ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50778/rus
