act_code: '51417'
requisite: Алматы облысы Іле ауданы Первомай кенттік округі әкімінің 2010 жылғы 03 наурыздағы № 02 шешімі. Алматы облысының Әділет департаменті Іле ауданының Әділет басқармасында 2010 жылғы 19 наурызда № 2-10-116 тіркелді
title:
  rus: Первомай кенттік округіндегі жаңа мөлтек ауданға және Қоян-Құс ауылының жаңа көшелеріне атауларын беру туралы
  kaz: Первомай кенттік округіндегі жаңа мөлтек ауданға және Қоян-Құс ауылының жаңа көшелеріне атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-03
approved_by:
- '154017009002'
version_date:
  kaz: 2010-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/51417/kaz/03.03.2010
