act_code: '37724'
requisite: Алматы облысы Іле аудандық мәслихатының 2008 жылғы 29 қаңтардағы № 6-20 шешімі. Алматы облысының Әділет департаменті Іле ауданының әділет басқармасында 2008 жылдың 19 ақпанында № 2-10-71 тіркелді. Күші жойылды - Іле ауданы мәслихатының 2010 жылғы 22 сәуірдегі № 32-121 шешімімен
title:
  rus: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету тәртiбi және мөлшерi туралы
  kaz: Тұрмысы төмен отбасыларына (азаматтарға) тұрғын үй көмегiн көрсету тәртiбi және мөлшерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-29
approved_by:
- '154017000002'
version_date:
  kaz: 2008-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/37724/kaz/29.01.2008
