act_code: '200022'
requisite: Решение Райымбекского районного маслихата Алматинской области от 20 августа 2024 года № 29-161. Зарегистрировано Департаментом юстиции Алматинской области 22 августа 2024 года № 6151-05
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Райымбекском районе
  kaz: Райымбек ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-20
approved_by:
- '154016000002'
version_date:
  kaz: 2024-08-20
  rus: 2024-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/200022/kaz/20.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200022/rus/20.08.2024
