act_code: '89459'
requisite: Решение маслихата Алматинской области от 27 марта 2015 года № 43-250. Зарегистрировано Департаментом юстиции Алматинской области 29 апреля 2015 года № 3151. Утратило силу решением Алматинского областного маслихата от 15.07.2016 № 7-43
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Алматинского областного маслихата»
  kaz: «Алматы облыстық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-03-27
approved_by:
- '154000000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/89459/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89459/rus/27.03.2015
