act_code: '179764'
requisite: Решение акима Междуреченского сельского округа Илийского района Алматинской области от 13 апреля 2023 года № 01-38/118. Зарегистрировано Департаментом юстиции Алматинской области 14 апреля 2023 года № 5979-05
title:
  rus: О переименовании улиц Междуреченского сельского округа
  kaz: Междуреченск ауылдық округінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-13
approved_by:
- '154017008002'
version_date:
  kaz: 2023-04-13
  rus: 2023-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/179764/kaz/13.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179764/rus/13.04.2023
