act_code: '181655'
requisite: Решение Илийского районного маслихата Алматинской области от 16 мая 2023 года № 4-13. Зарегистрировано Департаментом юстиции Алматинской области 17 мая 2023 года № 6000-05
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Илийскому району на 2023 год
  kaz: Іле ауданы бойынша 2023 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-16
approved_by:
- '154017000002'
version_date:
  kaz: 2023-05-16
  rus: 2023-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/181655/kaz/16.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181655/rus/16.05.2023
