act_code: '93904'
requisite: Решение Капшагайского городского маслихата Алматинской области от 15 июля 2015 года № 50-207. Зарегистрировано Департаментом юстиции Алматинской области 11 августа № 3334. Утратило силу решением Капшагайского городского маслихата Алматинской области от 25 февраля 2020 года № 66-235
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельских населенных пунктах города Капшагай
  kaz: Қапшағай қаласының азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-15
approved_by:
- '154020000002'
version_date:
  kaz: 2015-07-15
  rus: 2015-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/93904/kaz/15.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93904/rus/15.07.2015
