act_code: '95188'
requisite: Решение Уйгурского районного маслихата Алматинской области от 01 октября 2015 года № 51-3. Зарегистрировано Департаментом юстиции Алматинской области 06 ноября 2015 года № 3538. Утратило силу решением Уйгурского районного маслихата Алматинской области от 1 февраля 2016 года № 56-5
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Уйгурскому району
  kaz: Ұйғыр ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-01
approved_by:
- '154008000002'
version_date:
  kaz: 2015-10-01
  rus: 2015-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/95188/kaz/01.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95188/rus/01.10.2015
