act_code: '102084'
requisite: Решение Коксуского районного маслихата Алматинской области от 04 апреля 2016 года № 2-2. Зарегистрировано Департаментом юстиции Алматинской области 06 мая 2016 года № 3813. Утратило силу решением Коксуского районного маслихата Алматинской области от 3 марта 2017 года № 14-9
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса "Б" аппарата Коксуского районного маслихата
  kaz: Көксу ауданы мәслихаты аппаратының "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-04-04
approved_by:
- '154007000002'
version_date:
  kaz: 2016-04-04
  rus: 2016-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/102084/kaz/04.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102084/rus/04.04.2016
