act_code: '95322'
requisite: Решение от 09.10.2015 №46-1, Маслихат Коксуского района. Утратило силу решением Коксуского районного маслихата Алматинской области от 05 февраля 2016 года № 52-3
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Коксускому району
  kaz: Көксу ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-09
approved_by:
- '154007000002'
version_date:
  kaz: 2015-10-09
  rus: 2015-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/95322/kaz/09.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95322/rus/09.10.2015
