act_code: '204913'
requisite: Решение маслихата Алматинской области от 18 декабря 2024 года № 31-160
title:
  rus: Об областном бюджете Алматинской области на 2025-2027 годы
  kaz: Алматы облысының 2025-2027 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-18
approved_by:
- '154000000002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204913/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204913/rus/18.12.2024
