act_code: '210469'
requisite: Решение Карасайского районного маслихата Алматинской области от 15 мая 2025 года № 35-10
title:
  rus: Об утверждении нормы образования и накопления коммунальных отходов и тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Карасайскому району
  kaz: Қарасай ауданы бойынша коммуналдық қалдықтарды түзу және жинақтау нормалары мен қатты тұрмыстық қалдықтарды жинауға, тасымалдауға және көму бойынша тұрғындар үшін арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-15
approved_by:
- '154015000002'
version_date:
  kaz: 2025-05-15
  rus: 2025-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/210469/kaz/15.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210469/rus/15.05.2025
