act_code: '52845'
requisite: Алматы облысы Алакөл ауданы Жыланды ауылдық округі әкімінің 2010 жылғы 29 сәуірдегі № 05 шешімі. Алматы облысының Әділет департаменті Алакөл ауданының Әділет басқармасында 2010 жылы 02 маусымда № 2-5-91 тіркелді
title:
  rus: Жыланды ауылдық округіне қарасты Шынжылы ауылындағы атаусыз көшеге Есім Төре атын қою туралы
  kaz: Жыланды ауылдық округіне қарасты Шынжылы ауылындағы атаусыз көшеге Есім Төре атын қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-29
approved_by:
- '154003012002'
version_date:
  kaz: 2010-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/52845/kaz/29.04.2010
