act_code: '207486'
requisite: Решение маслихата Алматинской области от 25 февраля 2025 года № 33-178. Зарегистрировано Департаментом юстиции Алматинской области 26 февраля 2025 года № 6216-05
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Алатау Алматинской области
  kaz: Алматы облысы Алатау қаласындағы бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-25
approved_by:
- '154000000002'
version_date:
  kaz: 2025-02-25
  rus: 2025-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/207486/kaz/25.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207486/rus/25.02.2025
