act_code: '200861'
requisite: Решение маслихата города Қонаев Алматинской области от 20 сентября 2024 года № 32-117
title:
  rus: Об утверждении регламента собрания местного сообщества Шенгельдинского сельского округа города Қонаев
  kaz: Қонаев қаласы Шеңгелді ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-20
approved_by:
- '154020000002'
version_date:
  kaz: 2024-09-20
  rus: 2024-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/200861/kaz/20.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200861/rus/20.09.2024
