act_code: '222314'
requisite: Решение акима Аватского сельского округа Уйгурского района Алматинской области от 17 февраля 2026 года № 02-08
title:
  rus: О присвоении наименований улицам села Ават, Аватского сельского округа
  kaz: Ават ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-17
approved_by:
- '154008001002'
version_date:
  kaz: 2026-02-17
  rus: 2026-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/222314/kaz/17.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222314/rus/17.02.2026
