act_code: '51454'
requisite: Алматы облысы Жамбыл ауданы мәслихатының 2010 жылғы 5 наурыздағы № 35-153 шешімі. Алматы облысы Жамбыл ауданының Әділет басқармасында 2010 жылғы 26 наурызда № 2-7-93 тіркелді
title:
  rus: Кәсіпкерлік қызметтің тіркелген салық ставкаларын 2010 жылға белгілеу туралы
  kaz: Кәсіпкерлік қызметтің тіркелген салық ставкаларын 2010 жылға белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-05
approved_by:
- '154018000002'
version_date:
  kaz: 2010-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51454/kaz/05.03.2010
